// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-11-24 12:57:32
//     功能: Email仓储实现类
//     架构: 遵循Orleans最佳实践，继承SqlSugarRepository
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using SqlSugar;
using FakeMicro.DatabaseAccess;
using FakeMicro.DatabaseAccess.Interfaces;
using FakeMicro.Entities;
using FakeMicro.Interfaces.Models;
using FakeMicro.Shared.Exceptions;

namespace FakeMicro.DatabaseAccess.Repositories
{
    /// <summary>
    /// Email仓储实现类
    /// 继承SqlSugarRepository，遵循Orleans架构最佳实践
    /// </summary>
    public class EmailRepository : SqlSugarRepository<Email, long>, IEmailRepository
    {
        private readonly ILogger<EmailRepository> _logger;

        /// <summary>
        /// Email仓储构造函数
        /// </summary>
        /// <param name="db">SqlSugar数据库客户端</param>
        /// <param name="logger">日志记录器</param>
        public EmailRepository(ISqlSugarClient db, ILogger<EmailRepository> logger)
            : base(db, logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        #region 基类方法重写

        /// <summary>
        /// 重写获取Email方法，添加性能优化
        /// </summary>
        /// <param name="id">主键值</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>Email实体</returns>
        public new async virtual Task<Email?> GetByIdAsync(long id, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                // 使用SqlSugar的查询优化，添加WITH(NOLOCK)提示
                return await GetSqlSugarClient().Queryable<Email>()
                    .With(SqlWith.NoLock)
                    .Where(entity => entity.Id == id)
                    .FirstAsync(cancellationToken);
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "获取Email失败: {Id}", id);
                throw new DataAccessException("获取Email失败: " + id, ex);
            }
        }

        /// <summary>
        /// 创建Email并返回创建后的实体
        /// </summary>
        /// <param name="entity">Email实体</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>创建后的Email实体</returns>
        public async virtual Task<Email?> CreateAndReturnAsync(Email entity, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (entity == null) throw new ArgumentNullException(nameof(entity));
            
            try
            {
                var result = await GetSqlSugarClient().Insertable(entity).ExecuteReturnEntityAsync();
                _logger.LogInformation("成功创建Email: {Id}", typeof(Email).Name, result.Id);
                return result;
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "创建Email失败");
                throw new DataAccessException("创建Email失败", ex);
            }
        }

        /// <summary>
        /// 更新Email并返回更新后的实体
        /// </summary>
        /// <param name="entity">Email实体</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>更新后的Email实体</returns>
        public async virtual Task<Email?> UpdateAndReturnAsync(Email entity, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (entity == null) throw new ArgumentNullException(nameof(entity));
            
            try
            {
                var result = await GetSqlSugarClient().Updateable(entity).ExecuteReturnEntityAsync();
                _logger.LogInformation("成功更新Email: {Id}", typeof(Email).Name, entity.Id);
                return result;
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "更新Email失败");
                throw new DataAccessException("更新Email失败", ex);
            }
        }

        /// <summary>
        /// 批量创建Email并返回创建后的实体列表
        /// </summary>
        /// <param name="entities">Email实体集合</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>创建后的Email实体列表</returns>
        public async virtual Task<IEnumerable<Email>?> CreateRangeAndReturnAsync(IEnumerable<Email> entities, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (entities == null) throw new ArgumentNullException(nameof(entities));
            var entityList = entities.ToList();
            if (!entityList.Any()) return Enumerable.Empty<Email>();
            
            try
            {
                var affectedRows = await GetSqlSugarClient().Insertable(entityList).ExecuteCommandAsync(cancellationToken);
                _logger.LogInformation("成功批量创建Email，数量: {Count}", affectedRows);
                return entityList;
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "批量创建Email失败，数量: {Count}", entityList.Count);
                throw new DataAccessException("批量创建Email失败", ex);
            }
        }

        #endregion

        #region Orleans Grain特定操作

        /// <summary>
        /// 通过Grain ID获取Email（Orleans特定）
        /// </summary>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>Email实体</returns>
        public async virtual Task<Email?> GetByGrainIdAsync(CancellationToken cancellationToken = default)
        {
            // 注意：此方法在Grain实现中会被重写，用于通过Grain的ID获取实体
            // 默认实现返回null，实际使用时应在Grain上下文中根据具体ID策略实现
            return null;
        }

        /// <summary>
        /// 创建Email（Orleans特定）
        /// </summary>
        /// <param name="entity">Email实体</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>创建后的Email实体</returns>
        public async virtual Task<Email> CreateAsync(Email entity, CancellationToken cancellationToken = default)
        {
            return await CreateAndReturnAsync(entity, cancellationToken);
        }

        #endregion

        #region 同步方法包装

        /// <summary>
        /// 同步更新方法（包装异步方法）
        /// </summary>
        public void Update(Email entity)
        {
            UpdateAsync(entity).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步批量更新方法（包装异步方法）
        /// </summary>
        public void UpdateRange(IEnumerable<Email> entities)
        {
            UpdateRangeAsync(entities).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步删除方法（包装异步方法）
        /// </summary>
        public void Delete(Email entity)
        {
            DeleteAsync(entity).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步批量删除方法（包装异步方法）
        /// </summary>
        public void DeleteRange(IEnumerable<Email> entities)
        {
            DeleteRangeAsync(entities).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步部分更新方法（包装异步方法）
        /// </summary>
        public void UpdatePartial(Email entity, params Expression<Func<Email, object>>[] properties)
        {
            UpdatePartialAsync(entity, properties).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 基于属性的同步方法适配器
        /// </summary>
        /// <summary>
        /// 同步获取Email（根据title）
        /// </summary>
        public Email? GetBytitle(string title)
        {
            return GetBytitleAsync(title).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步检查title是否存在
        /// </summary>
        public bool titleExists(string title, long excludeId = default)
        {
            return titleExistsAsync(title, excludeId).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步获取Email（根据sendTo）
        /// </summary>
        public Email? GetBysendTo(string sendto)
        {
            return GetBysendToAsync(sendto).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步检查sendTo是否存在
        /// </summary>
        public bool sendToExists(string sendto, long excludeId = default)
        {
            return sendToExistsAsync(sendto, excludeId).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步获取Email（根据Major）
        /// </summary>
        public Email? GetByMajor(string major)
        {
            return GetByMajorAsync(major).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步检查Major是否存在
        /// </summary>
        public bool MajorExists(string major, long excludeId = default)
        {
            return MajorExistsAsync(major, excludeId).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步获取Email（根据Description）
        /// </summary>
        public Email? GetByDescription(string description)
        {
            return GetByDescriptionAsync(description).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步检查Description是否存在
        /// </summary>
        public bool DescriptionExists(string description, long excludeId = default)
        {
            return DescriptionExistsAsync(description, excludeId).GetAwaiter().GetResult();
        }

        #endregion

        #region 分页查询方法

        /// <summary>
        /// 分页查询Email（Orleans接口兼容）
        /// </summary>
        /// <param name="pageNumber">页码（从1开始）</param>
        /// <param name="pageSize">页大小</param>
        /// <param name="orderBy">排序表达式（可选）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>分页结果</returns>
        public async virtual Task<PagedResult<Email>> GetPagedAsync(int pageNumber, int pageSize, 
            Expression<Func<Email, object>>? orderBy = null, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (pageNumber < 1) pageNumber = 1;
            if (pageSize < 1) pageSize = 20;
            
            try
            {
                // 使用基类的分页方法
                var orderByExpression = orderBy ?? (x => x.Id);
                var result = await base.GetPagedAsync(pageNumber, pageSize, orderByExpression, false, cancellationToken);
                _logger.LogInformation("成功获取Email分页数据，页码: {PageNumber}, 页大小: {PageSize}", pageNumber, pageSize);
                return result;
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "获取Email分页数据失败，页码: {PageNumber}, 页大小: {PageSize}", pageNumber, pageSize);
                throw new DataAccessException("获取Email分页数据失败", ex);
            }
        }

        /// <summary>
        /// 条件分页查询Email（Orleans接口兼容）
        /// </summary>
        /// <param name="predicate">查询条件</param>
        /// <param name="pageNumber">页码（从1开始）</param>
        /// <param name="pageSize">页大小</param>
        /// <param name="orderBy">排序表达式（可选）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>分页结果</returns>
        public async virtual Task<PagedResult<Email>> GetPagedByConditionAsync(
            Expression<Func<Email, bool>> predicate, int pageNumber, int pageSize,
            Expression<Func<Email, object>>? orderBy = null, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (pageNumber < 1) pageNumber = 1;
            if (pageSize < 1) pageSize = 20;
            if (predicate == null) throw new ArgumentNullException(nameof(predicate));
            
            try
            {
                // 使用基类的条件分页方法
                var orderByExpression = orderBy ?? (x => x.Id);
                var result = await base.GetPagedByConditionAsync(predicate, pageNumber, pageSize, orderByExpression, false, cancellationToken);
                _logger.LogInformation("成功获取Email条件分页数据，页码: {PageNumber}, 页大小: {PageSize}", pageNumber, pageSize);
                return result;
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "获取Email条件分页数据失败，页码: {0}, 页大小: {1}", pageNumber, pageSize);
                throw new DataAccessException("获取Email条件分页数据失败", ex);
            }
        }

        #endregion

        #region 业务查询方法

        /// <summary>
        /// 根据title查询Email
        /// </summary>
        /// <param name="title">title</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>Email实体</returns>
        public async Task<Email?> GetBytitleAsync(string title, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                return await GetSqlSugarClient().Queryable<Email>()
                    .Where(entity => entity.title == title)
                    .FirstAsync();
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"根据title获取Email失败: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// 检查title是否存在
        /// </summary>
        /// <param name="title">title</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        public async Task<bool> titleExistsAsync(string title, long excludeId = default, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                var query = GetSqlSugarClient().Queryable<Email>()
                    .Where(entity => entity.title == title);
                
                if (!excludeId.Equals(default(long)))
                {
                    query = query.Where(entity => entity.Id != excludeId);
                }
                
                var count = await query.CountAsync();
                return count > 0;
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"检查Emailtitle是否存在失败: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// 根据sendTo查询Email
        /// </summary>
        /// <param name="sendto">sendTo</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>Email实体</returns>
        public async Task<Email?> GetBysendToAsync(string sendto, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                return await GetSqlSugarClient().Queryable<Email>()
                    .Where(entity => entity.sendTo == sendto)
                    .FirstAsync();
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"根据sendTo获取Email失败: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// 检查sendTo是否存在
        /// </summary>
        /// <param name="sendto">sendTo</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        public async Task<bool> sendToExistsAsync(string sendto, long excludeId = default, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                var query = GetSqlSugarClient().Queryable<Email>()
                    .Where(entity => entity.sendTo == sendto);
                
                if (!excludeId.Equals(default(long)))
                {
                    query = query.Where(entity => entity.Id != excludeId);
                }
                
                var count = await query.CountAsync();
                return count > 0;
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"检查EmailsendTo是否存在失败: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// 根据Major查询Email
        /// </summary>
        /// <param name="major">Major</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>Email实体</returns>
        public async Task<Email?> GetByMajorAsync(string major, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                return await GetSqlSugarClient().Queryable<Email>()
                    .Where(entity => entity.Major == major)
                    .FirstAsync();
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"根据Major获取Email失败: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// 检查Major是否存在
        /// </summary>
        /// <param name="major">Major</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        public async Task<bool> MajorExistsAsync(string major, long excludeId = default, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                var query = GetSqlSugarClient().Queryable<Email>()
                    .Where(entity => entity.Major == major);
                
                if (!excludeId.Equals(default(long)))
                {
                    query = query.Where(entity => entity.Id != excludeId);
                }
                
                var count = await query.CountAsync();
                return count > 0;
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"检查EmailMajor是否存在失败: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// 根据Description查询Email
        /// </summary>
        /// <param name="description">Description</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>Email实体</returns>
        public async Task<Email?> GetByDescriptionAsync(string description, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                return await GetSqlSugarClient().Queryable<Email>()
                    .Where(entity => entity.Description == description)
                    .FirstAsync();
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"根据Description获取Email失败: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// 检查Description是否存在
        /// </summary>
        /// <param name="description">Description</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        public async Task<bool> DescriptionExistsAsync(string description, long excludeId = default, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                var query = GetSqlSugarClient().Queryable<Email>()
                    .Where(entity => entity.Description == description);
                
                if (!excludeId.Equals(default(long)))
                {
                    query = query.Where(entity => entity.Id != excludeId);
                }
                
                var count = await query.CountAsync();
                return count > 0;
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"检查EmailDescription是否存在失败: {ex.Message}", ex);
            }
        }

        #endregion

    }
}