//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由代码生成器生成。
//     运行时版本: 9.0.11
//     生成时间: 2025-11-24 12:57:32
//     </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text.RegularExpressions;
using Orleans.Concurrency;
using Orleans;
using FakeMicro.Entities.Enums;

namespace FakeMicro.Interfaces.Models.Requests
{
    /// <summary>
    /// 创建Email请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class CreateEmailRequest
    {
        /// <summary>
        /// 主题
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [MaxLength(100, ErrorMessage = "{0}长度不能超过100个字符")]
        [Id(0)]
        public string? title { get; set; }

        /// <summary>
        /// 发送给谁
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [MaxLength(20, ErrorMessage = "{0}长度不能超过20个字符")]
        [Id(1)]
        public string? sendTo { get; set; }

        /// <summary>
        /// 专业
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [MaxLength(100, ErrorMessage = "{0}长度不能超过100个字符")]
        [Id(2)]
        public string? Major { get; set; }

        /// <summary>
        /// 状态(1:正常,2:停课,3:毕业)
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [Id(3)]
        public int status { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        [MaxLength(500, ErrorMessage = "{0}长度不能超过500个字符")]
        [Id(4)]
        public string? Description { get; set; }

        /// <summary>
        /// 手动验证请求数据
        /// </summary>
        /// <returns>验证结果</returns>
        public (bool IsValid, List<string> Errors) Validate()
        {
            var errors = new List<string>();

            if (string.IsNullOrWhiteSpace(title))
                errors.Add("title是必需的");

            if (title?.Length > 100)
                errors.Add("title长度不能超过100个字符");

            if (string.IsNullOrWhiteSpace(sendTo))
                errors.Add("sendTo是必需的");

            if (sendTo?.Length > 20)
                errors.Add("sendTo长度不能超过20个字符");

            if (string.IsNullOrWhiteSpace(Major))
                errors.Add("Major是必需的");

            if (Major?.Length > 100)
                errors.Add("Major长度不能超过100个字符");

            if (status == null)
                errors.Add("status是必需的");

            if (Description?.Length > 500)
                errors.Add("Description长度不能超过500个字符");

            return (errors.Count == 0, errors);
        }
    }

    /// <summary>
    /// 更新Email请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class UpdateEmailRequest
    {
        /// <summary>
        /// 唯一标识
        /// </summary>
        [Id(0)]
        public long Id { get; set; }

        /// <summary>
        /// 主题
        /// </summary>
        [Id(1)]
        public string? title { get; set; }

        /// <summary>
        /// 发送给谁
        /// </summary>
        [Id(2)]
        public string? sendTo { get; set; }

        /// <summary>
        /// 专业
        /// </summary>
        [Id(3)]
        public string? Major { get; set; }

        /// <summary>
        /// 状态(1:正常,2:停课,3:毕业)
        /// </summary>
        [Id(4)]
        public int? status { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        [Id(5)]
        public string? Description { get; set; }

    }

    /// <summary>
    /// 批量操作Email请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class BatchEmailRequest
    {
        /// <summary>
        /// 唯一标识列表
        /// </summary>
        [Id(0)]
        public List<long> Ids { get; set; } = new();

        /// <summary>
        /// 操作类型
        /// </summary>
        [Id(1)]
        public BatchOperationType OperationType { get; set; }

    }

    /// <summary>
    /// 查询Email请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class QueryEmailRequest
    {
        /// <summary>
        /// 唯一标识
        /// </summary>
        [Id(0)]
        public long Id { get; set; }

        /// <summary>
        /// 是否包含软删除的记录
        /// </summary>
        [Id(1)]
        public bool IncludeDeleted { get; set; } = false;

    }

    /// <summary>
    /// 搜索Email请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class SearchEmailRequest
    {
        /// <summary>
        /// 搜索关键词
        /// </summary>
        [Id(0)]
        public string Keyword { get; set; } = string.Empty;

        /// <summary>
        /// 页码（从1开始）
        /// </summary>
        [Id(1)]
        public int Page { get; set; } = 1;

        /// <summary>
        /// 每页大小
        /// </summary>
        [Id(2)]
        public int PageSize { get; set; } = 20;

        /// <summary>
        /// 排序字段
        /// </summary>
        [Id(3)]
        public string SortBy { get; set; } = "CreatedAt";

        /// <summary>
        /// 排序方向
        /// </summary>
        [Id(4)]
        public SortDirection SortDirection { get; set; } = SortDirection.Descending;

        /// <summary>
        /// 过滤条件
        /// </summary>
        [Id(5)]
        public Dictionary<string, object> Filters { get; set; } = new();

    }
}
