// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-11-24 12:57:32
// </auto-generated>

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.RegularExpressions;
using Orleans.Serialization;
using Orleans;
using System.Collections.Generic;
using System.Linq;

namespace FakeMicro.Interfaces.Models
{
    /// <summary>
    /// Email数据传输对象
    /// </summary>
[GenerateSerializer]
    public class EmailDto
    {
        /// <summary>
        /// 唯一标识
        /// </summary>
        [Id(0)]
        [Required]
        public long Id { get; set; }

        /// <summary>
        /// 主题
        /// </summary>
        [Id(1)]
        [MaxLength(100)]
        public string title { get; set; } = string.Empty;

        /// <summary>
        /// 发送给谁
        /// </summary>
        [Id(2)]
        [MaxLength(20)]
        public string sendTo { get; set; } = string.Empty;

        /// <summary>
        /// 专业
        /// </summary>
        [Id(3)]
        [MaxLength(100)]
        public string Major { get; set; } = string.Empty;

        /// <summary>
        /// 状态(1:正常,2:停课,3:毕业)
        /// </summary>
        [Id(4)]
        [Required]
        public int status { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        [Id(5)]
        [MaxLength(500)]
        public string? Description { get; set; } = string.Empty;

        /// <summary>
        /// 验证DTO数据
        /// </summary>
        /// <returns>验证结果</returns>
        public (bool IsValid, List<string> Errors) Validate()
        {
            var errors = new List<string>();

            if (Id == null)
                errors.Add("Id 是必需的");

            if (string.IsNullOrWhiteSpace(title))
                errors.Add("title 是必需的");

            if (string.IsNullOrWhiteSpace(sendTo))
                errors.Add("sendTo 是必需的");

            if (string.IsNullOrWhiteSpace(Major))
                errors.Add("Major 是必需的");

            if (status == null)
                errors.Add("status 是必需的");

            if (Description?.Length > 500)
                errors.Add("Description 长度不能超过 500 个字符");

            return (errors.Count == 0, errors);
        }

        /// <summary>
        /// 克隆DTO对象
        /// </summary>
        /// <returns>克隆的EmailDto对象</returns>
        public EmailDto Clone()
        {
            return new EmailDto
            {
                Id = this.Id,
                title = this.title,
                sendTo = this.sendTo,
                Major = this.Major,
                status = this.status,
                Description = this.Description,
            };
        }

        /// <summary>
        /// 转换为字符串表示
        /// </summary>
        /// <returns>字符串表示</returns>
        public override string ToString()
        {
            return $"EmailDto Id = {Id},title = {title},sendTo = {sendTo},Major = {Major},status = {status},Description = {Description}";
        }

    }

    #region 请求和响应DTO

    /// <summary>
    /// 创建Email请求
    /// </summary>
     [GenerateSerializer] 
    public class CreateEmailRequest
    {
        /// <summary>
        /// title
        /// </summary>
        [Id(0)]
        [MaxLength(100)]
        public string title { get; set; } = string.Empty;

        /// <summary>
        /// sendTo
        /// </summary>
        [Id(1)]
        [MaxLength(20)]
        public string sendTo { get; set; } = string.Empty;

        /// <summary>
        /// Major
        /// </summary>
        [Id(2)]
        [MaxLength(100)]
        public string Major { get; set; } = string.Empty;

        /// <summary>
        /// status
        /// </summary>
        [Id(3)]
        [Required]
        public int status { get; set; }

        /// <summary>
        /// Description
        /// </summary>
        [Id(4)]
        [MaxLength(500)]
        public string? Description { get; set; }

    }

    /// <summary>
    /// 更新Email请求
    /// </summary>
     [GenerateSerializer]
    public class UpdateEmailRequest
    {
        /// <summary>
        /// title
        /// </summary>
        [Id(0)]
        public string? title { get; set; }

        /// <summary>
        /// sendTo
        /// </summary>
        [Id(1)]
        public string? sendTo { get; set; }

        /// <summary>
        /// Major
        /// </summary>
        [Id(2)]
        public string? Major { get; set; }

        /// <summary>
        /// status
        /// </summary>
        [Id(3)]
        public int? status { get; set; }

        /// <summary>
        /// Description
        /// </summary>
        [Id(4)]
        public string? Description { get; set; }

    }

    /// <summary>
    /// 查询Email请求
    /// </summary>
[GenerateSerializer]
    public class QueryEmailRequest
    {
        [Id(0)]
        public int PageIndex { get; set; } = 1;
        [Id(1)]
        public int PageSize { get; set; } = 20;
        [Id(2)]
        public string? Keyword { get; set; }

        [Id(3)]
        public string? title { get; set; }

        [Id(4)]
        public string? sendTo { get; set; }

        [Id(5)]
        public string? Major { get; set; }

        [Id(6)]
        public string? Description { get; set; }

    }

    #endregion
}
