// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-11-22 21:03:51
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
 using FakeMicro.Interfaces;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using System;
using FakeMicro.Interfaces.Models;
using FakeMicro.DatabaseAccess;
using Microsoft.Extensions.Logging;
using Orleans;
using Orleans.Runtime;
using FakeMicro.Interfaces.Models.Results;

namespace FakeMicro.Entities.Api.Controllers
{
    /// <summary>
    /// FakeNews控制器
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Authorize]
    public class FakeNewsController : ControllerBase
    {
        private readonly IClusterClient _clusterClient;
        private readonly ILogger<FakeNewsController> _logger;

        public FakeNewsController(IClusterClient clusterClient, ILogger<FakeNewsController> logger)
        {
            this._clusterClient = clusterClient;
            _logger = logger;
        }

        /// <summary>
        /// 获取FakeNews
        /// </summary>
        [HttpGet("{Id}")]
        public async Task<ActionResult<FakeNewsDto>> GetFakeNews(long Id, CancellationToken cancellationToken = default)
        {
            try
            {
                // 输入验证
                if (Id == default(long))
                {
                    return BadRequest(new { Error = "FakeNewsID不能为空" });
                }

                var grain = _clusterClient.GetGrain<IFakeNewsGrain>("fakenews");
                var result = await grain.GetAsync(cancellationToken);
                if (result == null)
                    return NotFound(new { Message = "未找到指定的{entity.EntityDescription}" });
                return Ok(result);
            }
            catch (InvalidOperationException ex)
            {
                _logger.LogWarning(ex, "获取FakeNews时业务逻辑错误: {Id}", Id);
                return NotFound(new { Message = ex.Message });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "获取FakeNews时发生系统错误: {Id}", Id);
                return StatusCode(500, new { Error = "系统内部错误，请稍后重试" });
            }
        }

        /// <summary>
        /// 获取FakeNews列表
        /// </summary>
        [HttpGet]
        public async Task<ActionResult<PagedResult<FakeNewsDto>>> GetFakeNewsList([FromQuery] int page = 1, [FromQuery] int pageSize = 20, CancellationToken cancellationToken = default)
        {
            try
            {
                // 参数验证
                if (page <= 0)
                {
                    return BadRequest(new { Error = "页码必须大于0" });
                }
                if (pageSize <= 0 || pageSize > 1000)
                {
                    return BadRequest(new { Error = "页大小必须在1-1000之间" });
                }

                var grain = _clusterClient.GetGrain<IFakeNewsGrain>("list"); // 使用固定ID访问列表方法
                var items = await grain.GetListAsync(page, pageSize, cancellationToken);
                var totalCount = await grain.GetCountAsync(cancellationToken);
                var result = new PagedResult<FakeNewsDto>
                {
                    Items = items,
                    TotalCount = totalCount,
                    PageIndex = page,
                    PageSize = pageSize,
                    TotalPages = (int)Math.Ceiling((double)totalCount / pageSize)
                };
                return Ok(result);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "获取FakeNews列表时发生系统错误: Page={page}, PageSize={pageSize}", page, pageSize);
                return StatusCode(500, new { Error = "系统内部错误，请稍后重试" });
            }
        }

        /// <summary>
        /// 创建FakeNews
        /// </summary>
        [HttpPost]
        public async Task<ActionResult<CreateFakeNewsResult>> CreateFakeNews([FromBody] CreateFakeNewsRequest request, CancellationToken cancellationToken = default)
        {
            try
            {
                // 输入验证
                if (request == null)
                {
                    return BadRequest(new { Error = "请求数据不能为空" });
                }

                // TODO: 添加 FluentValidation 验证器
                // var validator = new Create{entity.EntityName}RequestValidator();
                // var validationResult = await validator.ValidateAsync(request, cancellationToken);
                // if (!validationResult.IsValid)
                // {
                //     return BadRequest(validationResult.Errors);
                // }

                var grain = _clusterClient.GetGrain<IFakeNewsGrain>("Guid.NewGuid()"); // 使用新ID创建
                var result = await grain.CreateAsync(request, cancellationToken);
                if (result.Success)
                    return CreatedAtAction(nameof(GetFakeNews), new { Id = result?.Id }, result);
                return BadRequest(result);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "创建FakeNews时发生系统错误");
                return StatusCode(500, new { Error = "系统内部错误，请稍后重试" });
            }
        }

        /// <summary>
        /// 更新FakeNews
        /// </summary>
        [HttpPut("{Id}")]
        public async Task<ActionResult<UpdateFakeNewsResult>> UpdateFakeNews(long Id, [FromBody] UpdateFakeNewsRequest request, CancellationToken cancellationToken = default)
        {
            try
            {
                // 主键验证
                if (Id == default(long))
                {
                    return BadRequest(new { Error = "主键值无效" });
                }

                // 输入验证
                if (request == null)
                {
                    return BadRequest(new { Error = "请求数据不能为空" });
                }

                // TODO: 添加 FluentValidation 验证器
                // var validator = new Update{entity.EntityName}RequestValidator();
                // var validationResult = await validator.ValidateAsync(request, cancellationToken);
                // if (!validationResult.IsValid)
                // {
                //     return BadRequest(validationResult.Errors);
                // }

                var grain = _clusterClient.GetGrain<IFakeNewsGrain>("Id");
                var result = await grain.UpdateAsync(request, cancellationToken);
                if (result.Success)
                    return Ok(result);
                return NotFound(result);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "更新FakeNews时发生系统错误: {Id}", Id);
                return StatusCode(500, new { Error = "系统内部错误，请稍后重试" });
            }
        }

        /// <summary>
        /// 删除FakeNews
        /// </summary>
        [HttpDelete("{Id}")]
        public async Task<ActionResult<DeleteFakeNewsResult>> DeleteFakeNews(long Id, CancellationToken cancellationToken = default)
        {
            try
            {
                // 主键验证
                if (Id == default(long))
                {
                    return BadRequest(new { Error = "主键值无效" });
                }

                var grain = _clusterClient.GetGrain<IFakeNewsGrain>("Id");
                var result = await grain.DeleteAsync(cancellationToken);
                if (result.Success)
                    return NoContent();
                return NotFound(result);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "删除FakeNews时发生系统错误: {Id}", Id);
                return StatusCode(500, new { Error = "系统内部错误，请稍后重试" });
            }
        }
    }
}
