using System.Text;

namespace FakeMicro.Utilities.CodeGenerator.Templates
{
    /// <summary>
    /// 控制器模板
    /// </summary>
    public static class ControllerTemplate
    {
        public static string Generate(EntityMetadata entity)
        {
            var sb = new StringBuilder();
            
            // 文件头注释
            sb.AppendLine($"// <auto-generated>");
            sb.AppendLine($"//     此代码由代码生成器生成，请勿手动修改");
            sb.AppendLine($"//     生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"// </auto-generated>");
            sb.AppendLine();
            
            // Using语句
            sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
            sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine($"using {entity.Namespace}.Interfaces;");
            sb.AppendLine($"using {entity.Namespace}.Models;");
            sb.AppendLine($"using {entity.Namespace}.Models.Results;");
            sb.AppendLine($"using Microsoft.Extensions.Logging;");
            sb.AppendLine("using Orleans;");
            sb.AppendLine("using Orleans.Runtime;");
            sb.AppendLine();
            
            // 命名空间
            sb.AppendLine($"namespace {entity.Namespace}.Api.Controllers");
            sb.AppendLine("{");
            
            // 类定义
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {entity.EntityDescription}控制器");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    [ApiController]");
            sb.AppendLine($"    [Route(\"api/[controller]\")]");
            sb.AppendLine($"    [Authorize]");
            sb.AppendLine($"    public class {entity.EntityName}Controller : ControllerBase");
            sb.AppendLine("    {");
            
            // 字段和构造函数
            sb.AppendLine($"        private readonly IClusterClient _clusterClient;");
            sb.AppendLine($"        private readonly ILogger<{entity.EntityName}Controller> _logger;");
            sb.AppendLine();
            sb.AppendLine($"        public {entity.EntityName}Controller(IClusterClient clusterClient, ILogger<{entity.EntityName}Controller> logger)");
            sb.AppendLine("        {");
            sb.AppendLine($"            this._clusterClient = clusterClient;");
            sb.AppendLine($"            _logger = logger;");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 获取单个实体
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 获取{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        [HttpGet(\"{{{entity.PrimaryKeyProperty}}}\")]");
            sb.AppendLine($"        public async Task<ActionResult<{entity.EntityName}Dto>> Get{entity.EntityName}({entity.PrimaryKeyType} {entity.PrimaryKeyProperty}, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine($"            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var grain = _clusterClient.GetGrain<I{entity.EntityName}Grain>(\"{entity.EntityName.ToLower()}\");");
            sb.AppendLine($"                var result = await grain.GetAsync(cancellationToken);");
            sb.AppendLine("                if (result == null)");
            sb.AppendLine("                    return NotFound();");
            sb.AppendLine("                return Ok(result);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _logger.LogError(ex, \"获取{entity.EntityDescription}时发生错误: {{{entity.PrimaryKeyProperty}}}\", {entity.PrimaryKeyProperty});");
            sb.AppendLine("                return StatusCode(500, \"内部服务器错误\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 获取列表
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 获取{entity.EntityDescription}列表");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        [HttpGet]");
            sb.AppendLine($"        public async Task<ActionResult<PagedResult<{entity.EntityName}Dto>>> Get{entity.EntityName}List([FromQuery] int page = 1, [FromQuery] int pageSize = 20, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine($"            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var grain = _clusterClient.GetGrain<I{entity.EntityName}Grain>(\"{entity.EntityName.ToLower()}\"); // 使用固定ID访问列表方法");
            sb.AppendLine($"                var items = await grain.GetListAsync(page, pageSize, cancellationToken);");
            sb.AppendLine($"                var totalCount = await grain.GetCountAsync(cancellationToken);");
            sb.AppendLine($"                var result = new PagedResult<{entity.EntityName}Dto>");
            sb.AppendLine("                {");
            sb.AppendLine("                    Items = items,");
            sb.AppendLine("                    TotalCount = totalCount,");
            sb.AppendLine("                    Page = page,");
            sb.AppendLine("                    PageSize = pageSize,");
            sb.AppendLine("                    TotalPages = (int)Math.Ceiling((double)totalCount / pageSize)");
            sb.AppendLine("                };");
            sb.AppendLine("                return Ok(result);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _logger.LogError(ex, \"获取{entity.EntityDescription}列表时发生错误\");");
            sb.AppendLine("                return StatusCode(500, \"内部服务器错误\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 创建方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 创建{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        [HttpPost]");
            sb.AppendLine($"        public async Task<ActionResult<Create{entity.EntityName}Result>> Create{entity.EntityName}([FromBody] Create{entity.EntityName}Request request, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine($"            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var grain = _clusterClient.GetGrain<I{entity.EntityName}Grain>(\"{entity.EntityName.ToLower()}\"); // 使用新ID创建");
            sb.AppendLine($"                var result = await grain.CreateAsync(request, cancellationToken);");
            sb.AppendLine("                if (result.Success)");
            sb.AppendLine($"                    return CreatedAtAction( nameof(Get{entity.EntityName}), new {entity.PrimaryKeyProperty} = result.Data?.Id, result);");
            sb.AppendLine($"                return BadRequest(result);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _logger.LogError(ex, \"创建{entity.EntityDescription}时发生错误\");");
            sb.AppendLine("                return StatusCode(500, \"内部服务器错误\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 更新方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 更新{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        [HttpPut(\"{{{entity.PrimaryKeyProperty}}}\")]");
            sb.AppendLine($"        public async Task<ActionResult<Update{entity.EntityName}Result>> Update{entity.EntityName}({entity.PrimaryKeyType} {entity.PrimaryKeyProperty}, [FromBody] Update{entity.EntityName}Request request, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine($"            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var grain = _clusterClient.GetGrain<I{entity.EntityName}Grain>(\"{entity.EntityName.ToLower()}\");");
            sb.AppendLine($"                var result = await grain.UpdateAsync(request, cancellationToken);");
            sb.AppendLine("                if (result.Success)");
            sb.AppendLine("                    return Ok(result);");
            sb.AppendLine("                return NotFound(result);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _logger.LogError(ex, \"更新{entity.EntityDescription}时发生错误: {{{entity.PrimaryKeyProperty}}}\", {entity.PrimaryKeyProperty});");
            sb.AppendLine("                return StatusCode(500, \"内部服务器错误\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 删除方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 删除{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        [HttpDelete(\"{{{entity.PrimaryKeyProperty}}}\")]");
            sb.AppendLine($"        public async Task<ActionResult<Delete{entity.EntityName}Result>> Delete{entity.EntityName}({entity.PrimaryKeyType} {entity.PrimaryKeyProperty}, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine($"            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var grain = _clusterClient.GetGrain<I{entity.EntityName}Grain>(\"{entity.EntityName.ToLower()}\");");
            sb.AppendLine($"                var result = await grain.DeleteAsync(cancellationToken);");
            sb.AppendLine("                if (result.Success)");
            sb.AppendLine("                    return NoContent();");
            sb.AppendLine("                return NotFound(result);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _logger.LogError(ex, \"删除{entity.EntityDescription}时发生错误: {{{entity.PrimaryKeyProperty}}}\", {entity.PrimaryKeyProperty});");
            sb.AppendLine("                return StatusCode(500, \"内部服务器错误\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            
            // 软删除支持
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine();
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// 软删除{entity.EntityDescription}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        [HttpPatch(\"{{{entity.PrimaryKeyProperty}}}/soft-delete\")]");
                sb.AppendLine($"        public async Task<ActionResult<Delete{entity.EntityName}Result>> SoftDelete{entity.EntityName}({entity.PrimaryKeyType} {entity.PrimaryKeyProperty}, CancellationToken cancellationToken = default)");
                sb.AppendLine("        {");
                sb.AppendLine($"            try");
                sb.AppendLine("            {");
                sb.AppendLine($"                var grain = _clusterClient.GetGrain<I{entity.EntityName}Grain>(\"{entity.EntityName.ToLower()}\");");
                sb.AppendLine($"                var result = await grain.SoftDeleteAsync(cancellationToken);");
                sb.AppendLine("                if (result.Success)");
                sb.AppendLine("                    return NoContent();");
                sb.AppendLine("                return NotFound(result);");
                sb.AppendLine("            }");
                sb.AppendLine("            catch (Exception ex)");
                sb.AppendLine("            {");
                sb.AppendLine($"                _logger.LogError(ex, \"软删除{entity.EntityDescription}时发生错误: {{{entity.PrimaryKeyProperty}}}\", {entity.PrimaryKeyProperty});");
                sb.AppendLine("                return StatusCode(500, \"内部服务器错误\");");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }
            
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            return sb.ToString();
        }
    }
}