using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using FakeMicro.Utilities.CodeGenerator.Entities;
using FakeMicro.Utilities.CodeGenerator;

namespace FakeMicro.Utilities.CodeGenerator.Templates
{
    /// <summary>
    /// DTO模板
    /// </summary>
    public static class DtoTemplate
    {
        public static string Generate(EntityMetadata metadata)
        {
            var sb = new StringBuilder();
            
            // 文件头注释
            sb.AppendLine($"// <auto-generated>");
            sb.AppendLine($"//     此代码由代码生成器生成，请勿手动修改");
            sb.AppendLine($"//     生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"// </auto-generated>");
            sb.AppendLine();

            // Using 语句 - 根据Orleans最佳实践优化
            sb.AppendLine("using System;");
            sb.AppendLine("using System.ComponentModel.DataAnnotations;");
            sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
            sb.AppendLine("using System.Text.RegularExpressions;");
            sb.AppendLine("using Orleans.Serialization;");
            sb.AppendLine("using Orleans;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine();

            // 命名空间
            sb.AppendLine("namespace FakeMicro.Interfaces.Models");
            sb.AppendLine("{");

            // 类注释
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {metadata.EntityDescription}数据传输对象");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class {metadata.EntityName}Dto");
            sb.AppendLine("    {");

            // 生成属性
            foreach (var prop in metadata.Properties)
            {
                sb.AppendLine("        /// <summary>");
                if (!string.IsNullOrEmpty(prop.Description))
                {
                    sb.AppendLine($"        /// {prop.Description}");
                }
                else
                {
                    sb.AppendLine($"        /// {prop.Name}");
                }
                sb.AppendLine("        /// </summary>");
                
                // Orleans序列化ID
                sb.AppendLine($"        [Id({metadata.Properties.IndexOf(prop)})]");
                
                // 验证属性
                if (prop.IsRequired && prop.Type != "string")
                {
                    sb.AppendLine("        [Required]");
                }
                
                if (prop.Type == "string" && prop.MaxLength.HasValue)
                {
                    sb.AppendLine($"        [MaxLength({prop.MaxLength.Value})]");
                }
                else if (prop.Type == "string" && prop.IsRequired)
                {
                    sb.AppendLine("        [Required]");
                }

                // 生成属性
                if (prop.Type == "string" && !prop.IsRequired)
                {
                    sb.AppendLine($"        public string? {prop.Name} {{ get; set; }} = string.Empty;");
                }
                else if (prop.Type.EndsWith("?"))
                {
                    sb.AppendLine($"        public {prop.Type} {prop.Name} {{ get; set; }}");
                }
                else if (prop.Type == "string")
                {
                    sb.AppendLine($"        public string {prop.Name} {{ get; set; }} = string.Empty;");
                }
                else if (prop.Type == "int" || prop.Type == "long" || prop.Type == "double" || prop.Type == "float" || prop.Type == "decimal")
                {
                    if (prop.IsRequired)
                    {
                        sb.AppendLine($"        public {prop.Type} {prop.Name} {{ get; set; }}");
                    }
                    else
                    {
                        sb.AppendLine($"        public {prop.Type}? {prop.Name} {{ get; set; }}");
                    }
                }
                else
                {
                    if (prop.IsRequired)
                    {
                        sb.AppendLine($"        public {prop.Type} {prop.Name} {{ get; set; }}");
                    }
                    else
                    {
                        sb.AppendLine($"        public {prop.Type}? {prop.Name} {{ get; set; }}");
                    }
                }
                sb.AppendLine();
            }

            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 验证DTO数据");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <returns>验证结果</returns>");
            sb.AppendLine("        public (bool IsValid, List<string> Errors) Validate()");
            sb.AppendLine("        {");
            sb.AppendLine("            var errors = new List<string>();");
            sb.AppendLine();

            foreach (var prop in metadata.Properties)
            {
                if (prop.IsRequired && prop.Type != "string")
                {
                    sb.AppendLine($"            if ({prop.Name} == null)");
                    sb.AppendLine($"                errors.Add(\"{prop.Name} 是必需的\");");
                    sb.AppendLine();
                }
                else if (prop.Type == "string" && prop.IsRequired)
                {
                    sb.AppendLine($"            if (string.IsNullOrWhiteSpace({prop.Name}))");
                    sb.AppendLine($"                errors.Add(\"{prop.Name} 是必需的\");");
                    sb.AppendLine();
                }
                else if (prop.Type == "string" && prop.MaxLength.HasValue)
                {
                    sb.AppendLine($"            if ({prop.Name}?.Length > {prop.MaxLength.Value})");
                    sb.AppendLine($"                errors.Add(\"{prop.Name} 长度不能超过 {prop.MaxLength.Value} 个字符\");");
                    sb.AppendLine();
                }
            }

            // 高级验证逻辑 - 邮箱、手机号、URL等
            foreach (var prop in metadata.Properties)
            {
                if (prop.Name.ToLower().Contains("email") && prop.Type == "string")
                {
                    sb.AppendLine($"            if (!string.IsNullOrWhiteSpace({prop.Name}))");
                    sb.AppendLine("            {");
                    sb.AppendLine("                var emailRegex = new Regex(@\"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$\", RegexOptions.IgnoreCase);");
                    sb.AppendLine($"                if (!emailRegex.IsMatch({prop.Name}.Trim()))");
                    sb.AppendLine($"                    errors.Add(\"{prop.Name} 邮箱格式不正确\");");
                    sb.AppendLine("            }");
                    sb.AppendLine();
                }
                else if (prop.Name.ToLower().Contains("phone") && prop.Type == "string")
                {
                    sb.AppendLine($"            if (!string.IsNullOrWhiteSpace({prop.Name}))");
                    sb.AppendLine("            {");
                    sb.AppendLine("                var phoneRegex = new Regex(@\"^1[3-9]\\d{9}$\");");
                    sb.AppendLine($"                if (!phoneRegex.IsMatch({prop.Name}.Trim()))");
                    sb.AppendLine($"                    errors.Add(\"{prop.Name} 手机号码格式不正确\");");
                    sb.AppendLine("            }");
                    sb.AppendLine();
                }
                else if (prop.Name.ToLower().Contains("url") && prop.Type == "string")
                {
                    sb.AppendLine($"            if (!string.IsNullOrWhiteSpace({prop.Name}))");
                    sb.AppendLine("            {");
                    sb.AppendLine("                if (!Uri.TryCreate({prop.Name}, UriKind.Absolute, out _))");
                    sb.AppendLine($"                    errors.Add(\"{prop.Name} URL格式不正确\");");
                    sb.AppendLine("            }");
                    sb.AppendLine();
                }
                else if (prop.Name.ToLower().Contains("code") && prop.Type == "string")
                {
                    sb.AppendLine($"            if (!string.IsNullOrWhiteSpace({prop.Name}))");
                    sb.AppendLine("            {");
                    sb.AppendLine("                var codeRegex = new Regex(@\"^[A-Z0-9_]+$\");");
                    sb.AppendLine($"                if (!codeRegex.IsMatch({prop.Name}.Trim().ToUpper()))");
                    sb.AppendLine($"                    errors.Add(\"{prop.Name} 只能包含大写字母、数字和下划线\");");
                    sb.AppendLine("            }");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("            return (errors.Count == 0, errors);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // 克隆方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 克隆DTO对象");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <returns>克隆的{metadata.EntityName}Dto对象</returns>");
            sb.AppendLine($"        public {metadata.EntityName}Dto Clone()");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new {metadata.EntityName}Dto");
            sb.AppendLine("            {");

            foreach (var prop in metadata.Properties)
            {
                sb.AppendLine($"                {prop.Name} = this.{prop.Name},");
            }

            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();

            // ToString方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 转换为字符串表示");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <returns>字符串表示</returns>");
            sb.AppendLine("        public override string ToString()");
            sb.AppendLine("        {");
            var propList = metadata.Properties.Select(p => $"{p.Name} = {{{p.Name}}}").ToList();
            sb.AppendLine($"            return $\"{metadata.EntityName}Dto {string.Join(",", propList)}\";");
            sb.AppendLine("        }");
            sb.AppendLine();

            // 相等性比较方法（基于主键）
            var pkProp = metadata.PrimaryKeyPropertyMetadata;
            if (pkProp != null)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// 比较两个对象是否相等");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        /// <param name=\"obj\">要比较的对象</param>");
                sb.AppendLine("        /// <returns>是否相等</returns>");
                sb.AppendLine("        public override bool Equals(object? obj)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return obj is {metadata.EntityName}Dto other && {pkProp.Name} == other.{pkProp.Name};");
                sb.AppendLine("        }");
                sb.AppendLine();

                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// 获取哈希码");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        /// <returns>哈希码</returns>");
                sb.AppendLine("        public override int GetHashCode()");
                sb.AppendLine("        {");
                sb.AppendLine($"            return {pkProp.Name}.GetHashCode();");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");

            // 请求和响应DTO（如果需要）
            sb.AppendLine();
            sb.AppendLine("    #region 请求和响应DTO");
            sb.AppendLine();

            // 创建请求DTO
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 创建{metadata.EntityDescription}请求");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("     [GenerateSerializer] ");
            sb.AppendLine($"    public class Create{metadata.EntityName}Request");
            sb.AppendLine("    {");

            // 创建请求不需要主键
            var createProps = metadata.Properties.Where(p => !p.IsPrimaryKey).ToList();
            foreach (var prop in createProps)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// {prop.Name}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        [Id({createProps.IndexOf(prop)})]");
                
                if (prop.IsRequired && prop.Type != "string")
                {
                    sb.AppendLine("        [Required]");
                }
                else if (prop.Type == "string" && prop.MaxLength.HasValue)
                {
                    sb.AppendLine($"        [MaxLength({prop.MaxLength.Value})]");
                }
                else if (prop.Type == "string" && prop.IsRequired)
                {
                    sb.AppendLine("        [Required]");
                }

                // 生成属性
                if (prop.Type == "string" && !prop.IsRequired)
                {
                    sb.AppendLine($"        public string? {prop.Name} {{ get; set; }}");
                }
                else if (prop.Type.EndsWith("?"))
                {
                    sb.AppendLine($"        public {prop.Type} {prop.Name} {{ get; set; }}");
                }
                else if (prop.Type == "string")
                {
                    sb.AppendLine($"        public string {prop.Name} {{ get; set; }} = string.Empty;");
                }
                else if (prop.IsRequired)
                {
                    sb.AppendLine($"        public {prop.Type} {prop.Name} {{ get; set; }}");
                }
                else
                {
                    sb.AppendLine($"        public {prop.Type}? {prop.Name} {{ get; set; }}");
                }
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine();

            // 更新请求DTO
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 更新{metadata.EntityDescription}请求");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class Update{metadata.EntityName}Request");
            sb.AppendLine("    {");

            foreach (var prop in metadata.Properties.Where(p => !p.IsPrimaryKey))
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// {prop.Name}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        [Id({metadata.Properties.IndexOf(prop) - 1})]"); // 减去主键

                // 更新请求的所有字段都是可选的
                if (prop.Type == "string")
                {
                    sb.AppendLine($"        public string? {prop.Name} {{ get; set; }}");
                }
                else if (prop.Type.EndsWith("?"))
                {
                    sb.AppendLine($"        public {prop.Type} {prop.Name} {{ get; set; }}");
                }
                else
                {
                    sb.AppendLine($"        public {prop.Type}? {prop.Name} {{ get; set; }}");
                }
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine();

            // 查询请求DTO
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 查询{metadata.EntityDescription}请求");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class Query{metadata.EntityName}Request");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(0)]");
            sb.AppendLine("        public int PageIndex { get; set; } = 1;");
            sb.AppendLine("        [Id(1)]");
            sb.AppendLine("        public int PageSize { get; set; } = 20;");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine("        public string? Keyword { get; set; }");
            sb.AppendLine();

            // 添加常用查询字段
            var queryProps = metadata.Properties.Where(p => 
                p.Type == "string" || p.Type == "bool" || p.Type == "DateTime?").ToList();
            
            int id = 3;
            foreach (var prop in queryProps.Take(10)) // 限制最多10个查询字段
            {
                sb.AppendLine($"        [Id({id})]");
                sb.AppendLine($"        public {prop.Type}? {prop.Name} {{ get; set; }}");
                sb.AppendLine();
                id++;
            }

            sb.AppendLine("    }");

            sb.AppendLine();
            sb.AppendLine("    #endregion");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}