using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using FakeMicro.Utilities.CodeGenerator.Entities;
using FakeMicro.Utilities.CodeGenerator;

namespace FakeMicro.Utilities.CodeGenerator.Templates
{
    /// <summary>
    /// 实体类定义模板
    /// </summary>
    public static class EntityTemplate
    {
        public static string Generate(EntityMetadata entity)
        {
            var sb = new StringBuilder();
            int idCounter = 0; // Orleans 序列化 ID 计数器
            
            // 文件头注释
            sb.AppendLine($"// <auto-generated>");
            sb.AppendLine($"//     此代码由代码生成器生成，请勿手动修改");
            sb.AppendLine($"//     生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"// </auto-generated>");
            sb.AppendLine();
            
            // Using语句
            sb.AppendLine("using System;");
            sb.AppendLine("using System.ComponentModel.DataAnnotations;");
            sb.AppendLine("using SqlSugar;");
            sb.AppendLine("using Orleans;");
            sb.AppendLine();
            
            // 命名空间 - 使用ProjectStructureMapping获取正确的命名空间
            var entityNamespace = ProjectStructureMapping.GetNamespace(GenerationType.Entity, entity.EntityName);
            sb.AppendLine($"namespace {entityNamespace}");
            sb.AppendLine("{");
            
            // 类定义
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {entity.EntityDescription}");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    [GenerateSerializer]");
            sb.AppendLine($"    [SugarTable(\"{entity.EntityName.ToLower()}\")]");
            sb.AppendLine($"    public class {entity.EntityName}");
            sb.AppendLine("    {");
            
            // 属性定义
            foreach (var property in entity.Properties)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// {property.Description}");
                sb.AppendLine("        /// </summary>");
                
                // 添加 Orleans Id 特性
                sb.AppendLine($"        [Id({idCounter++})]");
                
                // 添加数据注解
                if (property.IsRequired)
                {
                    sb.AppendLine("        [Required]");
                }
                
                if (property.MaxLength.HasValue && property.Type == "string")
                {
                    sb.AppendLine($"        [MaxLength({property.MaxLength.Value})]");
                }
                
                if (property.MinLength.HasValue && property.Type == "string")
                {
                    sb.AppendLine($"        [MinLength({property.MinLength.Value})]");
                }
                
                // 添加SqlSugar列属性
                var sugarColumnAttributes = new List<string>();
                
                if (property.IsPrimaryKey)
                {
                    sugarColumnAttributes.Add("IsPrimaryKey = true");
                    
                    if (property.IsIdentity)
                    {
                        sugarColumnAttributes.Add("IsIdentity = true");
                    }
                }
                
                if (property.IsReadOnly)
                {
                    sugarColumnAttributes.Add("IsOnlyIgnoreInsert = true, IsOnlyIgnoreUpdate = true");
                }
                
                if (!string.IsNullOrEmpty(property.ColumnName) && property.ColumnName != property.Name)
                {
                    sugarColumnAttributes.Add($"ColumnName = \"{property.ColumnName}\"");
                }
                
                if (property.Type == "string" && !string.IsNullOrEmpty(property.DefaultValue))
                {
                    sugarColumnAttributes.Add($"DefaultValue = \"{property.DefaultValue}\"");
                }
                else if (!string.IsNullOrEmpty(property.DefaultValue))
                {
                    sugarColumnAttributes.Add($"DefaultValue = {property.DefaultValue}");
                }
                
                if (sugarColumnAttributes.Any())
                {
                    sb.AppendLine($"        [SugarColumn({string.Join(", ", sugarColumnAttributes)})]");
                }
                
                // 属性定义
                var propertyType = GetCSharpType(property.Type);
                sb.AppendLine($"        public {propertyType} {property.Name} {{ get; set; }}");
                sb.AppendLine();
            }
            
            // 添加通用属性
            var hasCreatedAt = entity.Properties.Any(p => p.Name == "CreatedAt");
            var hasUpdatedAt = entity.Properties.Any(p => p.Name == "UpdatedAt");
            var hasIsDeleted = entity.Properties.Any(p => p.Name == "IsDeleted");
            
            if (!hasCreatedAt)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// 创建时间");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        [Id({idCounter++})]");
                sb.AppendLine("        [SugarColumn(IsOnlyIgnoreUpdate = true)]");
                sb.AppendLine("        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;");
                sb.AppendLine();
            }
            
            if (!hasUpdatedAt)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// 更新时间");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        [Id({idCounter++})]");
                sb.AppendLine("        [SugarColumn(IsOnlyIgnoreInsert = true)]");
                sb.AppendLine("        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;");
                sb.AppendLine();
            }
            
            if (entity.IsSoftDeletable && !hasIsDeleted)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// 是否已删除");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        [Id({idCounter++})]");
                sb.AppendLine("        [SugarColumn(IsOnlyIgnoreInsert = true)]");
                sb.AppendLine("        public bool IsDeleted { get; set; } = false;");
                sb.AppendLine();
            }
            
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            return sb.ToString();
        }
        
        private static string GetCSharpType(string type)
        {
            return type.ToLower() switch
            {
                "string" => "string",
                "int" or "int32" => "int",
                "long" or "int64" => "long",
                "short" or "int16" => "short",
                "decimal" => "decimal",
                "double" => "double",
                "float" or "single" => "float",
                "bool" or "boolean" => "bool",
                "datetime" => "DateTime",
                "datetimeoffset" => "DateTimeOffset",
                "guid" => "Guid",
                "byte[]" => "byte[]",
                _ => type
            };
        }
    }
}