using System.Text;

namespace FakeMicro.Utilities.CodeGenerator.Templates
{
    /// <summary>
    /// Grain实现模板
    /// </summary>
    public static class GrainTemplate
    {
        public static string Generate(EntityMetadata entity)
        {
            var sb = new StringBuilder();
            
            // 文件头注释
            sb.AppendLine($"// <auto-generated>");
            sb.AppendLine($"//     此代码由代码生成器生成，请勿手动修改");
            sb.AppendLine($"//     生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"// </auto-generated>");
            sb.AppendLine();
            
            // Using语句
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using Microsoft.Extensions.Logging;");
            sb.AppendLine("using Orleans;");
            sb.AppendLine("using Orleans.Runtime;");
            sb.AppendLine("using System;");
            sb.AppendLine($"using {entity.Namespace}.Interfaces;");
            sb.AppendLine($"using {entity.Namespace}.Models;");
            sb.AppendLine($"using {entity.Namespace}.Models.Requests;");
            sb.AppendLine($"using {entity.Namespace}.Models.Results;");
            sb.AppendLine("using FakeMicro.DatabaseAccess;");
            sb.AppendLine();
            
            // 命名空间
            sb.AppendLine($"namespace {entity.Namespace}.Grains");
            sb.AppendLine("{");
            
            // 类定义
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {entity.EntityDescription}Grain实现");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public class {entity.EntityName}Grain :Grain,I{entity.EntityName}Grain");
            sb.AppendLine("    {");
            
            // 字段和构造函数
            sb.AppendLine($"        private readonly ILogger<{entity.EntityName}Grain> _logger;");
            //sb.AppendLine($"        private readonly IMapper _mapper;");
            sb.AppendLine();
            sb.AppendLine($"        public {entity.EntityName}Grain(ILogger<{entity.EntityName}Grain> logger, IMapper mapper)");
            sb.AppendLine("        {");
            sb.AppendLine($"            _logger = logger;");
            sb.AppendLine($"            _mapper = mapper;");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 获取方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 获取{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public async Task<{entity.EntityName}Dto?> GetAsync(CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var repository = new SqlSugarRepository<{entity.EntityName}>();");
            sb.AppendLine($"                var entity = await repository.GetByIdAsync(this.GetPrimaryKey(), cancellationToken);");
            sb.AppendLine("                if (entity == null)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    _logger.LogWarning(\"{entity.EntityDescription}不存在: {{Id}}\", this.GetPrimaryKey());");
            sb.AppendLine("                    return null;");
            sb.AppendLine("                }");
            sb.AppendLine($"                return _mapper.Map<{entity.EntityName}Dto>(entity);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _logger.LogError(ex, \"获取{entity.EntityDescription}时发生错误: {{Id}}\", this.GetPrimaryKey());");
            sb.AppendLine("                throw;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 创建方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 创建{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public async Task<Create{entity.EntityName}Result> CreateAsync(Create{entity.EntityName}Request request, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var repository = new SqlSugarRepository<{entity.EntityName}>();");
            sb.AppendLine($"                var entity = _mapper.Map<{entity.EntityName}>(request);");
            sb.AppendLine();
            sb.AppendLine("                // 设置默认值");
            sb.AppendLine("                entity.Id = this.GetPrimaryKey();");
            sb.AppendLine("                entity.CreatedAt = DateTime.UtcNow;");
            sb.AppendLine("                entity.UpdatedAt = DateTime.UtcNow;");
            
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine("                entity.IsDeleted = false;");
            }
            
            sb.AppendLine();
            sb.AppendLine($"                var createdEntity = await repository.InsertAsync(entity, cancellationToken);");
            sb.AppendLine($"                var result = _mapper.Map<{entity.EntityName}Dto>(createdEntity);");
            sb.AppendLine();
            sb.AppendLine($"                _logger.LogInformation(\"{entity.EntityDescription}创建成功: {{Id}}\", createdEntity.Id);");
            sb.AppendLine($"                return Create{entity.EntityName}Result.Success(result);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _logger.LogError(ex, \"创建{entity.EntityDescription}时发生错误\");");
            sb.AppendLine($"                return Create{entity.EntityName}Result.Failure(\"创建失败: \" + ex.Message);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 更新方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 更新{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public async Task<Update{entity.EntityName}Result> UpdateAsync(Update{entity.EntityName}Request request, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var repository = new SqlSugarRepository<{entity.EntityName}>();");
            sb.AppendLine($"                var existingEntity = await repository.GetByIdAsync(this.GetPrimaryKey(), cancellationToken);");
            sb.AppendLine("                if (existingEntity == null)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    _logger.LogWarning(\"{entity.EntityDescription}不存在: {{Id}}\", this.GetPrimaryKey());");
            sb.AppendLine($"                    return Update{entity.EntityName}Result.NotFound(\"{entity.EntityDescription}不存在\");");
            sb.AppendLine("                }");
            sb.AppendLine();
            sb.AppendLine("                // 更新字段");
            sb.AppendLine("                _mapper.Map(request, existingEntity);");
            sb.AppendLine("                existingEntity.UpdatedAt = DateTime.UtcNow;");
            sb.AppendLine();
            sb.AppendLine($"                await repository.UpdateAsync(existingEntity, cancellationToken);");
            sb.AppendLine($"                var result = _mapper.Map<{entity.EntityName}Dto>(existingEntity);");
            sb.AppendLine();
            sb.AppendLine($"                _logger.LogInformation(\"{entity.EntityDescription}更新成功: {{Id}}\", existingEntity.Id);");
            sb.AppendLine($"                return Update{entity.EntityName}Result.Success(result);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _logger.LogError(ex, \"更新{entity.EntityDescription}时发生错误: {{Id}}\", this.GetPrimaryKey());");
            sb.AppendLine($"                return Update{entity.EntityName}Result.Failure(\"更新失败: \" + ex.Message);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 删除方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 删除{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public async Task<Delete{entity.EntityName}Result> DeleteAsync(CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var repository = new SqlSugarRepository<{entity.EntityName}>();");
            sb.AppendLine($"                var existingEntity = await repository.GetByIdAsync(this.GetPrimaryKey(), cancellationToken);");
            sb.AppendLine("                if (existingEntity == null)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    _logger.LogWarning(\"{entity.EntityDescription}不存在: {{Id}}\", this.GetPrimaryKey());");
            sb.AppendLine($"                    return Delete{entity.EntityName}Result.NotFound(\"{entity.EntityDescription}不存在\");");
            sb.AppendLine("                }");
            sb.AppendLine();
            
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine("                // 软删除");
                sb.AppendLine("                existingEntity.IsDeleted = true;");
                sb.AppendLine("                existingEntity.UpdatedAt = DateTime.UtcNow;");
                sb.AppendLine($"                await repository.UpdateAsync(existingEntity, cancellationToken);");
            }
            else
            {
                sb.AppendLine($"                await repository.DeleteAsync(this.GetPrimaryKey(), cancellationToken);");
            }
            
            sb.AppendLine();
            sb.AppendLine($"                _logger.LogInformation(\"{entity.EntityDescription}删除成功: {{Id}}\", this.GetPrimaryKey());");
            sb.AppendLine($"                return Delete{entity.EntityName}Result.Success();");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _logger.LogError(ex, \"删除{entity.EntityDescription}时发生错误: {{Id}}\", this.GetPrimaryKey());");
            sb.AppendLine($"                return Delete{entity.EntityName}Result.Failure(\"删除失败: \" + ex.Message);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 软删除方法
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// 软删除{entity.EntityDescription}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        public async Task<Delete{entity.EntityName}Result> SoftDeleteAsync(CancellationToken cancellationToken = default)");
                sb.AppendLine("        {");
                sb.AppendLine("            try");
                sb.AppendLine("            {");
                sb.AppendLine($"                var repository = new SqlSugarRepository<{entity.EntityName}>();");
                sb.AppendLine($"                var existingEntity = await repository.GetByIdAsync(this.GetPrimaryKey(), cancellationToken);");
                sb.AppendLine("                if (existingEntity == null)");
                sb.AppendLine("                {");
                sb.AppendLine($"                    _logger.LogWarning(\"{entity.EntityDescription}不存在: {{Id}}\", this.GetPrimaryKey());");
                sb.AppendLine($"                    return Delete{entity.EntityName}Result.NotFound(\"{entity.EntityDescription}不存在\");");
                sb.AppendLine("                }");
                sb.AppendLine();
                sb.AppendLine("                // 软删除");
                sb.AppendLine("                existingEntity.IsDeleted = true;");
                sb.AppendLine("                existingEntity.UpdatedAt = DateTime.UtcNow;");
                sb.AppendLine($"                await repository.UpdateAsync(existingEntity, cancellationToken);");
                sb.AppendLine();
                sb.AppendLine($"                _logger.LogInformation(\"{entity.EntityDescription}软删除成功: {{Id}}\", this.GetPrimaryKey());");
                sb.AppendLine($"                return Delete{entity.EntityName}Result.Success();");
                sb.AppendLine("            }");
                sb.AppendLine("            catch (Exception ex)");
                sb.AppendLine("            {");
                sb.AppendLine($"                _logger.LogError(ex, \"软删除{entity.EntityDescription}时发生错误: {{Id}}\", this.GetPrimaryKey());");
                sb.AppendLine($"                return Delete{entity.EntityName}Result.Failure(\"软删除失败: \" + ex.Message);");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            
            // 获取列表方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 获取{entity.EntityDescription}列表");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public async Task<List<{entity.EntityName}Dto>> GetListAsync(int page = 1, int pageSize = 20, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var repository = new SqlSugarRepository<{entity.EntityName}>();");
            sb.AppendLine("                var query = repository.GetQueryable();");
            
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine("                query = query.Where(x => !x.IsDeleted);");
            }
            
            sb.AppendLine();
            sb.AppendLine("                var entities = await query");
            sb.AppendLine("                    .OrderByDescending(x => x.CreatedAt)");
            sb.AppendLine("                    .Skip((page - 1) * pageSize)");
            sb.AppendLine("                    .Take(pageSize)");
            sb.AppendLine("                    .ToListAsync(cancellationToken);");
            sb.AppendLine();
            sb.AppendLine($"                return _mapper.Map<List<{entity.EntityName}Dto>>(entities);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _logger.LogError(ex, \"获取{entity.EntityDescription}列表时发生错误\");");
            sb.AppendLine("                throw;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 获取总数方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 获取{entity.EntityDescription}总数");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public async Task<int> GetCountAsync(CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var repository = new SqlSugarRepository<{entity.EntityName}>();");
            sb.AppendLine("                var query = repository.GetQueryable();");
            
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine("                query = query.Where(x => !x.IsDeleted);");
            }
            
            sb.AppendLine();
            sb.AppendLine("                return await query.CountAsync(cancellationToken);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _logger.LogError(ex, \"获取{entity.EntityDescription}总数时发生错误\");");
            sb.AppendLine("                throw;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 搜索方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 搜索{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public async Task<List<{entity.EntityName}Dto>> SearchAsync(string keyword, int page = 1, int pageSize = 20, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var repository = new SqlSugarRepository<{entity.EntityName}>();");
            sb.AppendLine("                var query = repository.GetQueryable();");
            
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine("                query = query.Where(x => !x.IsDeleted);");
            }
            
            sb.AppendLine();
            sb.AppendLine("                // 搜索逻辑 - 根据字符串属性搜索");
            var searchableProperties = entity.Properties.Where(p => p.Type == "string" && !p.IsPrimaryKey).ToList();
            if (searchableProperties.Any())
            {
                sb.AppendLine("                if (!string.IsNullOrEmpty(keyword))");
                sb.AppendLine("                {");
                sb.Append("                    query = query.Where(x => ");
                var searchConditions = searchableProperties.Select(p => $"x.{p.Name}.Contains(keyword)");
                sb.AppendLine(string.Join(" || ", searchConditions) + ");");
                sb.AppendLine("                }");
            }
            
            sb.AppendLine();
            sb.AppendLine("                var entities = await query");
            sb.AppendLine("                    .OrderByDescending(x => x.CreatedAt)");
            sb.AppendLine("                    .Skip((page - 1) * pageSize)");
            sb.AppendLine("                    .Take(pageSize)");
            sb.AppendLine("                    .ToListAsync(cancellationToken);");
            sb.AppendLine();
            sb.AppendLine($"                return _mapper.Map<List<{entity.EntityName}Dto>>(entities);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _logger.LogError(ex, \"搜索{entity.EntityDescription}时发生错误\");");
            sb.AppendLine("                throw;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 批量删除方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 批量删除{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public async Task<BatchDelete{entity.EntityName}Result> BatchDeleteAsync(List<{entity.PrimaryKeyType}> ids, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var repository = new SqlSugarRepository<{entity.EntityName}>();");
            sb.AppendLine("                var query = repository.GetQueryable().Where(x => ids.Contains(x.Id));");
            
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine("                query = query.Where(x => !x.IsDeleted);");
            }
            
            sb.AppendLine();
            sb.AppendLine("                var entities = await query.ToListAsync(cancellationToken);");
            sb.AppendLine("                if (!entities.Any())");
            sb.AppendLine("                {");
            sb.AppendLine($"                    return BatchDelete{entity.EntityName}Result.NotFound(\"未找到要删除的{entity.EntityDescription}\");");
            sb.AppendLine("                }");
            sb.AppendLine();
            
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine("                // 批量软删除");
                sb.AppendLine("                foreach (var entity in entities)");
                sb.AppendLine("                {");
                sb.AppendLine("                    entity.IsDeleted = true;");
                sb.AppendLine("                    entity.UpdatedAt = DateTime.UtcNow;");
                sb.AppendLine("                }");
                sb.AppendLine($"                await repository.UpdateRangeAsync(entities, cancellationToken);");
            }
            else
            {
                sb.AppendLine($"                await repository.DeleteRangeAsync(entities, cancellationToken);");
            }
            
            sb.AppendLine();
            sb.AppendLine($"                _logger.LogInformation(\"批量删除{entity.EntityDescription}成功，删除数量: {{Count}}\", entities.Count);");
            sb.AppendLine($"                return BatchDelete{entity.EntityName}Result.Success(entities.Count);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine($"                _logger.LogError(ex, \"批量删除{entity.EntityDescription}时发生错误\");");
            sb.AppendLine($"                return BatchDelete{entity.EntityName}Result.Failure(\"批量删除失败: \" + ex.Message);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 验证方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 验证{entity.EntityDescription}数据");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public async Task<ValidationResult> ValidateAsync({entity.EntityName}Dto data, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            var errors = new List<string>();");
            sb.AppendLine();
            
            // 添加验证逻辑
            foreach (var property in entity.Properties)
            {
                if (property.IsRequired && property.Type == "string")
                {
                    sb.AppendLine($"            if (string.IsNullOrWhiteSpace(data.{property.Name}))");
                    sb.AppendLine($"                errors.Add(\"{property.Description}不能为空\");");
                }
                
                if (property.MaxLength.HasValue && property.Type == "string")
                {
                    sb.AppendLine($"            if (data.{property.Name}?.Length > {property.MaxLength.Value})");
                    sb.AppendLine($"                errors.Add(\"{property.Description}长度不能超过{property.MaxLength.Value}个字符\");");
                }
                
                if (property.MinLength.HasValue && property.Type == "string")
                {
                    sb.AppendLine($"            if (data.{property.Name}?.Length < {property.MinLength.Value})");
                    sb.AppendLine($"                errors.Add(\"{property.Description}长度不能少于{property.MinLength.Value}个字符\");");
                }
            }
            
            sb.AppendLine();
            sb.AppendLine("            if (errors.Any())");
            sb.AppendLine("            {");
            sb.AppendLine("                return ValidationResult.Failure(errors);");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return ValidationResult.Success();");
            sb.AppendLine("        }");
            
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            return sb.ToString();
        }
    }
}