using System;
using System.Text;
using FakeMicro.Utilities.CodeGenerator;
using FakeMicro.Utilities.CodeGenerator.Entities;

namespace FakeMicro.Utilities.CodeGenerator.Templates
{
    /// <summary>
    /// IGrain接口模板
    /// </summary>
    public static class InterfaceTemplate
    {
        public static string Generate(EntityMetadata entity)
        {
            var sb = new StringBuilder();
            
            // 文件头注释
            sb.AppendLine($"// <auto-generated>");
            sb.AppendLine($"//     此代码由代码生成器生成，请勿手动修改");
            sb.AppendLine($"//     生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"// </auto-generated>");
            sb.AppendLine();
            
            // Using语句
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Orleans;  // Orleans Grain 接口支持");
            
            // 使用ProjectStructureMapping获取相关命名空间
            var entityNamespace = ProjectStructureMapping.GetNamespace(GenerationType.Entity, entity.EntityName);
            var requestNamespace = ProjectStructureMapping.GetNamespace(GenerationType.Request, entity.EntityName);
            var resultNamespace = ProjectStructureMapping.GetNamespace(GenerationType.Result, entity.EntityName);
            
            sb.AppendLine($"using {entityNamespace};");
            sb.AppendLine($"using {requestNamespace};");
            sb.AppendLine($"using {resultNamespace};");
            sb.AppendLine();
            
            // 命名空间 - 使用ProjectStructureMapping获取正确的命名空间
            var interfaceNamespace = ProjectStructureMapping.GetNamespace(GenerationType.Interface, entity.EntityName);
            sb.AppendLine($"namespace {interfaceNamespace}");
            sb.AppendLine("{");
            
            // 接口定义
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {entity.EntityDescription}Grain接口");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public interface I{entity.EntityName}Grain : IGrainWithStringKey");
            sb.AppendLine("    {");
            
            // 基础CRUD方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 获取{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        Task<{entity.EntityName}Dto?> GetAsync(CancellationToken cancellationToken = default);");
            sb.AppendLine();
            
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 创建{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        Task<Create{entity.EntityName}Result> CreateAsync(Create{entity.EntityName}Request request, CancellationToken cancellationToken = default);");
            sb.AppendLine();
            
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 更新{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        Task<Update{entity.EntityName}Result> UpdateAsync(Update{entity.EntityName}Request request, CancellationToken cancellationToken = default);");
            sb.AppendLine();
            
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 删除{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        Task<Delete{entity.EntityName}Result> DeleteAsync(CancellationToken cancellationToken = default);");
            sb.AppendLine();
            
            // 软删除支持
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// 软删除{entity.EntityDescription}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        Task<Delete{entity.EntityName}Result> SoftDeleteAsync(CancellationToken cancellationToken = default);");
                sb.AppendLine();
            }
            
            // 查询方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 获取{entity.EntityDescription}列表");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        Task<List<{entity.EntityName}Dto>> GetListAsync(int page = 1, int pageSize = 20, CancellationToken cancellationToken = default);");
            sb.AppendLine();
            
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 获取{entity.EntityDescription}总数");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        Task<int> GetCountAsync(CancellationToken cancellationToken = default);");
            sb.AppendLine();
            
            // 搜索方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 搜索{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        Task<List<{entity.EntityName}Dto>> SearchAsync(string keyword, int page = 1, int pageSize = 20, CancellationToken cancellationToken = default);");
            sb.AppendLine();
            
            // 批量操作方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 批量删除{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        Task<BatchDelete{entity.EntityName}Result> BatchDeleteAsync(List<{GetGrainKeyType(entity.PrimaryKeyType).ToLower()}> ids, CancellationToken cancellationToken = default);");
            sb.AppendLine();
            
            // 验证方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 验证{entity.EntityDescription}数据");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        Task<ValidationResult> ValidateAsync({entity.EntityName}Dto data, CancellationToken cancellationToken = default);");
            
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            return sb.ToString();
        }
        
        private static string GetGrainKeyType(string keyType)
        {
            return keyType.ToLower() switch
            {
                "string" => "String",
                "guid" => "Guid",
                "long" => "Long",
                "int" => "Integer",
                _ => "String"
            };
        }
    }
}