using System;
using System.Collections.Generic;
using System.Text;

namespace FakeMicro.Utilities.CodeGenerator.Templates
{
    /// <summary>
    /// Grain接口模板
    /// </summary>
    public static class InterfaceTemplate
    {
        public static string Generate(EntityMetadata metadata)
        {
            var sb = new StringBuilder();
            
            // 文件头注释
            sb.AppendLine($"// <auto-generated>");
            sb.AppendLine($"//     此代码由代码生成器生成，请勿手动修改");
            sb.AppendLine($"//     生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"// </auto-generated>");
            sb.AppendLine();

            // Using 语句
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Orleans;");
            sb.AppendLine("using Orleans.Concurrency;");
            sb.AppendLine($"using {metadata.Namespace};");
            sb.AppendLine("using FakeMicro.Interfaces.Models;");
            sb.AppendLine();

            // 命名空间
            sb.AppendLine("namespace FakeMicro.Interfaces");
            sb.AppendLine("{");

            // 类注释
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {metadata.EntityDescription} Grain接口");
            sb.AppendLine("    /// </summary>");
            //sb.AppendLine($"    public interface I{metadata.EntityName}Grain : IGrainWith{metadata.PrimaryKeyType}Key");
            sb.AppendLine($"    public interface I{metadata.EntityName}Grain : IGrainWithStringKey");
            sb.AppendLine("    {");

            // 基础CRUD方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 初始化Grain");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [AlwaysInterleave]");
            sb.AppendLine("        Task InitializeAsync(CancellationToken cancellationToken = default);");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 获取{metadata.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [ReadOnly]");
            sb.AppendLine($"        Task<{metadata.EntityName}Dto?> GetAsync(CancellationToken cancellationToken = default);");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 从数据库获取{metadata.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [ReadOnly]");
            sb.AppendLine($"        Task<{metadata.EntityName}Dto?> GetFromDatabaseAsync(CancellationToken cancellationToken = default);");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 创建{metadata.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        Task<Create{metadata.EntityName}Result> CreateAsync({metadata.EntityName}Dto dto, CancellationToken cancellationToken = default);");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 更新{metadata.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        Task<Update{metadata.EntityName}Result> UpdateAsync({metadata.EntityName}Dto dto, CancellationToken cancellationToken = default);");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 删除{metadata.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        Task<Delete{metadata.EntityName}Result> DeleteAsync(CancellationToken cancellationToken = default);");
            sb.AppendLine();

            // 检查存在性方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 检查{metadata.EntityDescription}是否存在");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [ReadOnly]");
            sb.AppendLine("        Task<bool> ExistsAsync(CancellationToken cancellationToken = default);");
            sb.AppendLine();

            // 软删除支持
            if (metadata.IsSoftDeletable)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// 软删除{metadata.EntityDescription}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        Task<Delete{metadata.EntityName}Result> SoftDeleteAsync(CancellationToken cancellationToken = default);");
                sb.AppendLine();

                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// 恢复{metadata.EntityDescription}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        Task<Update{metadata.EntityName}Result> RestoreAsync(CancellationToken cancellationToken = default);");
                sb.AppendLine();
            }

            // 查询方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 获取{metadata.EntityDescription}列表");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [ReadOnly]");
            sb.AppendLine($"        Task<List<{metadata.EntityName}Dto>> GetListAsync(int pageIndex = 1, int pageSize = 20, CancellationToken cancellationToken = default);");
            sb.AppendLine();

            // 搜索方法（如果有字符串属性）
            var searchableProperties = metadata.Properties.FindAll(p => 
                p.Type == "string" && !p.IsPrimaryKey);
            
            if (searchableProperties.Count > 0)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// 搜索{metadata.EntityDescription}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        [ReadOnly]");
                sb.AppendLine($"        Task<List<{metadata.EntityName}Dto>> SearchAsync(string keyword, CancellationToken cancellationToken = default);");
                sb.AppendLine();
            }

            // 特定业务方法示例
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 获取{metadata.EntityDescription}统计信息");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [ReadOnly]");
            sb.AppendLine($"        Task<{metadata.EntityName}Statistics> GetStatisticsAsync(CancellationToken cancellationToken = default);");
            sb.AppendLine();

            // 批量操作方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 批量更新{metadata.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        Task<BatchUpdate{metadata.EntityName}Result> BatchUpdateAsync(List<{metadata.EntityName}Dto> dtos, CancellationToken cancellationToken = default);");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// 批量删除{metadata.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        Task<BatchDelete{metadata.EntityName}Result> BatchDeleteAsync(List<{metadata.PrimaryKeyType}> ids, CancellationToken cancellationToken = default);");
            sb.AppendLine();

            sb.AppendLine("    }");
            sb.AppendLine("}");

            // 生成结果类
            sb.AppendLine();
            sb.AppendLine("namespace FakeMicro.Interfaces");
            sb.AppendLine("{");

            // 创建结果类
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 创建{metadata.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class Create{metadata.EntityName}Result");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(0)]");
            sb.AppendLine("        public bool Success { get; set; }");
            sb.AppendLine("        [Id(1)]");
            sb.AppendLine("        public string? ErrorMessage { get; set; }");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine($"        public {metadata.EntityName}Dto? Created{metadata.EntityName} {{ get; set; }}");
            sb.AppendLine("        [Id(3)]");
            sb.AppendLine($"        public {metadata.PrimaryKeyType}? {metadata.PrimaryKeyProperty} {{ get; set; }}");
            sb.AppendLine();
            sb.AppendLine($"        public static Create{metadata.EntityName}Result CreateSuccess({metadata.EntityName}Dto entity, {metadata.PrimaryKeyType} id)");
            sb.AppendLine($"            => new() {{ Success = true, Created{metadata.EntityName} = entity, {metadata.PrimaryKeyProperty} = id }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Create{metadata.EntityName}Result CreateFailed(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage }};");
            sb.AppendLine("    }");
            sb.AppendLine();

            // 更新结果类
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 更新{metadata.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class Update{metadata.EntityName}Result");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(0)]");
            sb.AppendLine("        public bool Success { get; set; }");
            sb.AppendLine("        [Id(1)]");
            sb.AppendLine("        public string? ErrorMessage { get; set; }");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine($"        public {metadata.EntityName}Dto? Updated{metadata.EntityName} {{ get; set; }}");
            sb.AppendLine();
            sb.AppendLine($"        public static Update{metadata.EntityName}Result CreateSuccess({metadata.EntityName}Dto entity)");
            sb.AppendLine($"            => new() {{ Success = true, Updated{metadata.EntityName} = entity }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Update{metadata.EntityName}Result CreateFailed(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage }};");
            sb.AppendLine("    }");
            sb.AppendLine();

            // 删除结果类
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 删除{metadata.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class Delete{metadata.EntityName}Result");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(0)]");
            sb.AppendLine("        public bool Success { get; set; }");
            sb.AppendLine("        [Id(1)]");
            sb.AppendLine("        public string? ErrorMessage { get; set; }");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine("        public bool IsSoftDeleted { get; set; }");
            sb.AppendLine();
            sb.AppendLine($"        public static Delete{metadata.EntityName}Result CreateSuccess(bool isSoftDeleted = false)");
            sb.AppendLine($"            => new() {{ Success = true, IsSoftDeleted = isSoftDeleted }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Delete{metadata.EntityName}Result CreateFailed(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage }};");
            sb.AppendLine("    }");
            sb.AppendLine();

            // 批量更新结果类
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 批量更新{metadata.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class BatchUpdate{metadata.EntityName}Result");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(0)]");
            sb.AppendLine("        public bool Success { get; set; }");
            sb.AppendLine("        [Id(1)]");
            sb.AppendLine("        public string? ErrorMessage { get; set; }");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine("        public int SuccessCount { get; set; }");
            sb.AppendLine("        [Id(3)]");
            sb.AppendLine("        public int FailedCount { get; set; }");
            sb.AppendLine("        [Id(4)]");
            sb.AppendLine("        public List<string> Errors { get; set; } = new();");
            sb.AppendLine();
            sb.AppendLine($"        public static BatchUpdate{metadata.EntityName}Result CreateSuccess(int successCount)");
            sb.AppendLine($"            => new() {{ Success = true, SuccessCount = successCount }};");
            sb.AppendLine();
            sb.AppendLine($"        public static BatchUpdate{metadata.EntityName}Result CreateFailed(List<string> errors)");
            sb.AppendLine($"            => new() {{ Success = false, FailedCount = errors.Count, Errors = errors }};");
            sb.AppendLine("    }");
            sb.AppendLine();

            // 批量删除结果类
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 批量删除{metadata.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class BatchDelete{metadata.EntityName}Result");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(0)]");
            sb.AppendLine("        public bool Success { get; set; }");
            sb.AppendLine("        [Id(1)]");
            sb.AppendLine("        public string? ErrorMessage { get; set; }");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine("        public int SuccessCount { get; set; }");
            sb.AppendLine("        [Id(3)]");
            sb.AppendLine("        public int FailedCount { get; set; }");
            sb.AppendLine("        [Id(4)]");
            sb.AppendLine("        public List<string> Errors { get; set; } = new();");
            sb.AppendLine();
            sb.AppendLine($"        public static BatchDelete{metadata.EntityName}Result CreateSuccess(int successCount)");
            sb.AppendLine($"            => new() {{ Success = true, SuccessCount = successCount }};");
            sb.AppendLine();
            sb.AppendLine($"        public static BatchDelete{metadata.EntityName}Result CreateFailed(List<string> errors)");
            sb.AppendLine($"            => new() {{ Success = false, FailedCount = errors.Count, Errors = errors }};");
            sb.AppendLine("    }");
            sb.AppendLine();

            // 统计信息类
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {metadata.EntityDescription}统计信息");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class {metadata.EntityName}Statistics");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(0)]");
            sb.AppendLine("        public int TotalCount { get; set; }");
            sb.AppendLine("        [Id(1)]");
            sb.AppendLine("        public int ActiveCount { get; set; }");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine("        public int CreatedToday { get; set; }");
            sb.AppendLine("        [Id(3)]");
            sb.AppendLine("        public int CreatedThisWeek { get; set; }");
            sb.AppendLine("        [Id(4)]");
            sb.AppendLine("        public int CreatedThisMonth { get; set; }");
            sb.AppendLine("        [Id(5)]");
            sb.AppendLine("        public DateTime? LastCreated { get; set; }");
            sb.AppendLine("        [Id(6)]");
            sb.AppendLine("        public DateTime? LastUpdated { get; set; }");
            sb.AppendLine();
            if (metadata.IsSoftDeletable)
            {
                sb.AppendLine("        [Id(7)]");
                sb.AppendLine("        public int DeletedCount { get; set; }");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}