using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

using FakeMicro.Utilities.CodeGenerator.Entities;
using FakeMicro.Utilities.CodeGenerator;

namespace FakeMicro.Utilities.CodeGenerator.Templates
{
    /// <summary>
    /// 仓储实现模板
    /// 生成符合Orleans最佳实践的仓储实现类
    /// 继承SqlSugarRepository并实现相应的仓储接口
    /// 
    /// 优化特性：
    /// 1. 同步方法包装，兼容旧接口
    /// 2. 改进的分页查询方法
    /// 3. 字段存在性检查方法
    /// 4. 基于业务字段的查询方法
    /// 5. Orleans特定的Grain操作方法
    /// 6. 完善的异常处理和日志记录
    /// </summary>
    public static class RepositoryImplementationTemplate
    {
        /// <summary>
        /// 生成仓储实现代码（使用EntityMetadata）
        /// </summary>
        /// <param name="entity">实体元数据</param>
        /// <returns>生成的代码字符串</returns>
        public static string Generate(EntityMetadata entity)
        {
            var sb = new StringBuilder();
            
            // 文件头注释
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     此代码由代码生成器生成，请勿手动修改");
            sb.AppendLine("//     生成时间: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
            sb.AppendLine("//     功能: " + entity.EntityDescription + "仓储实现类");
            sb.AppendLine("//     架构: 遵循Orleans最佳实践，继承SqlSugarRepository");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            
            // Using语句
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Linq.Expressions;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Microsoft.Extensions.Logging;");
            sb.AppendLine("using SqlSugar;");
            sb.AppendLine("using FakeMicro.DatabaseAccess;");
            sb.AppendLine("using FakeMicro.DatabaseAccess.Interfaces;");
            
            // 使用ProjectStructureMapping获取实体命名空间
            var entityNamespace = ProjectStructureMapping.GetNamespace(GenerationType.Entity, entity.EntityName);
            sb.AppendLine($"using {entityNamespace};");
            sb.AppendLine();
            
            // 命名空间 - 使用ProjectStructureMapping获取正确的命名空间
            var repositoryNamespace = ProjectStructureMapping.GetNamespace(GenerationType.RepositoryImplementation, entity.EntityName);
            sb.AppendLine($"namespace {repositoryNamespace}");
            sb.AppendLine("{");
            
            // 仓储实现类定义
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// " + entity.EntityDescription + "仓储实现类");
            sb.AppendLine("    /// 继承SqlSugarRepository，遵循Orleans架构最佳实践");
            sb.AppendLine("    /// </summary>");
            
            // 根据主键类型选择泛型参数
            var primaryKeyType = entity.PrimaryKeyType.ToLower() switch
            {
                "guid" => "Guid",
                "long" => "long", 
                "int" => "int",
                "string" => "string",
                _ => "Guid"
            };

            // 正确的继承声明：继承SqlSugarRepository并实现接口
            sb.AppendLine("    public class " + entity.EntityName + "Repository : SqlSugarRepository<" + entity.EntityName + ", " + primaryKeyType + ">, I" + entity.EntityName + "Repository");
            sb.AppendLine("    {");
            
            // 私有字段
            sb.AppendLine("        private readonly ILogger<" + entity.EntityName + "Repository> _logger;");
            sb.AppendLine();
            
            // 构造函数 - 正确的依赖注入
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// " + entity.EntityDescription + "仓储构造函数");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"db\">SqlSugar数据库客户端</param>");
            sb.AppendLine("        /// <param name=\"logger\">日志记录器</param>");
            sb.AppendLine("        public " + entity.EntityName + "Repository(ISqlSugarClient db, ILogger<" + entity.EntityName + "Repository> logger)");
            sb.AppendLine("            : base(db, logger)");
            sb.AppendLine("        {");
            sb.AppendLine("            _logger = logger ?? throw new ArgumentNullException(nameof(logger));");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 重写基类的GetByIdAsync方法以提供更好的性能
            sb.AppendLine("        #region 基类方法重写");
            sb.AppendLine();
            
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 重写获取" + entity.EntityDescription + "方法，添加性能优化");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"id\">主键值</param>");
            sb.AppendLine("        /// <param name=\"cancellationToken\">取消令牌</param>");
            sb.AppendLine("        /// <returns>" + entity.EntityDescription + "实体</returns>");
            sb.AppendLine("        public new async virtual Task<" + entity.EntityName + "?> GetByIdAsync(" + primaryKeyType + " id, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                // 使用SqlSugar的查询优化，添加WITH(NOLOCK)提示");
            sb.AppendLine("                return await GetSqlSugarClient().Queryable<" + entity.EntityName + ">()");
            sb.AppendLine("                    .With(SqlWith.NoLock)");
            sb.AppendLine("                    .Where(entity => entity." + entity.PrimaryKeyProperty + " == id)");
            sb.AppendLine("                    .FirstAsync(cancellationToken);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (SqlSugarException ex)");
            sb.AppendLine("            {");
            sb.AppendLine("                _logger.LogError(ex, \"获取" + entity.EntityDescription + "失败: {Id}\", id);");
            sb.AppendLine("                throw new DataAccessException(\"获取" + entity.EntityDescription + "失败: \" + id, ex);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // CreateAndReturnAsync方法 - 创建实体并返回
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 创建" + entity.EntityDescription + "并返回创建后的实体");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"entity\">" + entity.EntityDescription + "实体</param>");
            sb.AppendLine("        /// <param name=\"cancellationToken\">取消令牌</param>");
            sb.AppendLine("        /// <returns>创建后的" + entity.EntityDescription + "实体</returns>");
            sb.AppendLine("        public async virtual Task<" + entity.EntityName + "?> CreateAndReturnAsync(" + entity.EntityName + " entity, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
            sb.AppendLine("            if (entity == null) throw new ArgumentNullException(nameof(entity));");
            sb.AppendLine("            ");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                var result = await GetSqlSugarClient().Insertable(entity).ExecuteReturnEntityAsync(cancellationToken);");
            sb.AppendLine("                _logger.LogInformation(\"成功创建" + entity.EntityName + ": {Id}\", typeof(" + entity.EntityName + ").Name, result." + entity.PrimaryKeyProperty + ");");
            sb.AppendLine("                return result;");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (SqlSugarException ex)");
            sb.AppendLine("            {");
            sb.AppendLine("                _logger.LogError(ex, \"创建" + entity.EntityDescription + "失败\");");
            sb.AppendLine("                throw new DataAccessException(\"创建" + entity.EntityDescription + "失败\", ex);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // UpdateAndReturnAsync方法 - 更新实体并返回更新后的实体
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 更新" + entity.EntityDescription + "并返回更新后的实体");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"entity\">" + entity.EntityDescription + "实体</param>");
            sb.AppendLine("        /// <param name=\"cancellationToken\">取消令牌</param>");
            sb.AppendLine("        /// <returns>更新后的" + entity.EntityDescription + "实体</returns>");
            sb.AppendLine("        public async virtual Task<" + entity.EntityName + "?> UpdateAndReturnAsync(" + entity.EntityName + " entity, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
            sb.AppendLine("            if (entity == null) throw new ArgumentNullException(nameof(entity));");
            sb.AppendLine("            ");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                var result = await GetSqlSugarClient().Updateable(entity).ExecuteReturnEntityAsync(cancellationToken);");
            sb.AppendLine("                _logger.LogInformation(\"成功更新" + entity.EntityName + ": {Id}\", typeof(" + entity.EntityName + ").Name, entity." + entity.PrimaryKeyProperty + ");");
            sb.AppendLine("                return result;");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (SqlSugarException ex)");
            sb.AppendLine("            {");
            sb.AppendLine("                _logger.LogError(ex, \"更新" + entity.EntityDescription + "失败\");");
            sb.AppendLine("                throw new DataAccessException(\"更新" + entity.EntityDescription + "失败\", ex);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // CreateRangeAndReturnAsync方法 - 批量创建实体并返回结果列表
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 批量创建" + entity.EntityDescription + "并返回创建后的实体列表");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"entities\">" + entity.EntityDescription + "实体集合</param>");
            sb.AppendLine("        /// <param name=\"cancellationToken\">取消令牌</param>");
            sb.AppendLine("        /// <returns>创建后的" + entity.EntityDescription + "实体列表</returns>");
            sb.AppendLine("        public async virtual Task<IEnumerable<" + entity.EntityName + ">?> CreateRangeAndReturnAsync(IEnumerable<" + entity.EntityName + "> entities, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
            sb.AppendLine("            if (entities == null) throw new ArgumentNullException(nameof(entities));");
            sb.AppendLine("            var entityList = entities.ToList();");
            sb.AppendLine("            if (!entityList.Any()) return Enumerable.Empty<" + entity.EntityName + ">();");
            sb.AppendLine("            ");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                var result = await GetSqlSugarClient().Insertable(entityList).ExecuteReturnListAsync(cancellationToken);");
            sb.AppendLine("                _logger.LogInformation(\"成功批量创建" + entity.EntityName + "，数量: {Count}\", result.Count);");
            sb.AppendLine("                return result;");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (SqlSugarException ex)");
            sb.AppendLine("            {");
            sb.AppendLine("                _logger.LogError(ex, \"批量创建" + entity.EntityDescription + "失败，数量: {Count}\", entityList.Count);");
            sb.AppendLine("                throw new DataAccessException(\"批量创建" + entity.EntityDescription + "失败\", ex);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 软删除方法（如果实体支持软删除）
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// 软删除" + entity.EntityDescription);
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        /// <param name=\"id\">主键值</param>");
                sb.AppendLine("        /// <param name=\"cancellationToken\">取消令牌</param>");
                sb.AppendLine("        /// <returns>是否删除成功</returns>");
                sb.AppendLine("        public async virtual Task<bool> SoftDeleteAsync(" + primaryKeyType + " id, CancellationToken cancellationToken = default)");
                sb.AppendLine("        {");
                sb.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
                sb.AppendLine("            try");
                sb.AppendLine("            {");
                sb.AppendLine("                var result = await GetSqlSugarClient().Updateable<" + entity.EntityName + ">()");
                sb.AppendLine("                    .SetColumns(entity => new " + entity.EntityName + " { IsDeleted = true, DeleteTime = DateTime.UtcNow })");
                sb.AppendLine("                    .Where(entity => entity." + entity.PrimaryKeyProperty + " == id)");
                sb.AppendLine("                    .ExecuteCommandAsync(cancellationToken);");
                sb.AppendLine("                ");
                sb.AppendLine("                if (result > 0)");
                sb.AppendLine("                {");
                sb.AppendLine("                    _logger.LogInformation(\"成功软删除" + entity.EntityDescription + ": {Id}\", id);");
                sb.AppendLine("                    return true;");
                sb.AppendLine("                }");
                sb.AppendLine("                ");
                sb.AppendLine("                return false;");
                sb.AppendLine("            }");
                sb.AppendLine("            catch (SqlSugarException ex)");
                sb.AppendLine("            {");
                sb.AppendLine("                _logger.LogError(ex, \"软删除" + entity.EntityDescription + "失败: {Id}\", id);");
                sb.AppendLine("                throw new DataAccessException(\"软删除" + entity.EntityDescription + "失败: \" + id, ex);");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // Orleans特定的仓储方法（基于Grain ID的操作）
            sb.AppendLine("        #region Orleans Grain特定操作");
            sb.AppendLine();
            
            // GetAsync - 通过Grain ID获取（无参数，使用Grain的ID作为主键）
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 通过Grain ID获取" + entity.EntityDescription + "（Orleans特定）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"cancellationToken\">取消令牌</param>");
            sb.AppendLine("        /// <returns>" + entity.EntityDescription + "实体</returns>");
            sb.AppendLine("        public async virtual Task<" + entity.EntityName + "?> GetByGrainIdAsync(CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            // 注意：此方法需要在Grain上下文中调用，通过Grain的ID获取实体");
            sb.AppendLine("            // 具体实现取决于Grain的ID策略");
            sb.AppendLine("            throw new NotImplementedException(\"需要在Grain上下文中实现GetByGrainIdAsync方法\");");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // CreateAsync - Orleans特定的创建方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 创建" + entity.EntityDescription + "（Orleans特定）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"entity\">" + entity.EntityDescription + "实体</param>");
            sb.AppendLine("        /// <param name=\"cancellationToken\">取消令牌</param>");
            sb.AppendLine("        /// <returns>创建后的" + entity.EntityDescription + "实体</returns>");
            sb.AppendLine("        public async virtual Task<" + entity.EntityName + "> CreateAsync(" + entity.EntityName + " entity, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            return await CreateAndReturnAsync(entity, cancellationToken);");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 同步方法包装（兼容旧接口）
            sb.AppendLine("        #region 同步方法包装");
            sb.AppendLine();
            
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 同步更新方法（包装异步方法）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public void Update(" + entity.EntityName + " entity)");
            sb.AppendLine("        {");
            sb.AppendLine("            UpdateAsync(entity).GetAwaiter().GetResult();");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 同步批量更新方法（包装异步方法）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public void UpdateRange(IEnumerable<" + entity.EntityName + "> entities)");
            sb.AppendLine("        {");
            sb.AppendLine("            UpdateRangeAsync(entities).GetAwaiter().GetResult();");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 同步删除方法（包装异步方法）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public void Delete(" + entity.EntityName + " entity)");
            sb.AppendLine("        {");
            sb.AppendLine("            DeleteAsync(entity).GetAwaiter().GetResult();");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 同步批量删除方法（包装异步方法）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public void DeleteRange(IEnumerable<" + entity.EntityName + "> entities)");
            sb.AppendLine("        {");
            sb.AppendLine("            DeleteRangeAsync(entities).GetAwaiter().GetResult();");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 同步部分更新方法（包装异步方法）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public void UpdatePartial(" + entity.EntityName + " entity, params Expression<Func<" + entity.EntityName + ", object>>[] properties)");
            sb.AppendLine("        {");
            sb.AppendLine("            UpdatePartialAsync(entity, properties).GetAwaiter().GetResult();");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 添加基于属性的同步方法 - 参考DictionaryTypeRepository模式
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 基于属性的同步方法适配器");
            sb.AppendLine("        /// </summary>");
            foreach (var prop in entity.Properties.Where(p => !p.IsPrimaryKey && !p.IsNavigationProperty))
            {
                if (prop.Type.ToLower().Contains("string"))
                {
                    sb.AppendLine("        /// <summary>");
                    sb.AppendLine("        /// 同步获取" + entity.EntityDescription + "（根据" + prop.Name + "）");
                    sb.AppendLine("        /// </summary>");
                    sb.AppendLine("        public " + entity.EntityName + "? GetBy" + prop.Name + "(string " + prop.Name.ToLower() + ")");
                    sb.AppendLine("        {");
                    sb.AppendLine("            return GetBy" + prop.Name + "Async(" + prop.Name.ToLower() + ").GetAwaiter().GetResult();");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    
                    sb.AppendLine("        /// <summary>");
                    sb.AppendLine("        /// 同步检查" + prop.Name + "是否存在");
                    sb.AppendLine("        /// </summary>");
                    sb.AppendLine("        public bool " + prop.Name + "Exists(string " + prop.Name.ToLower() + ", " + primaryKeyType + " excludeId = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            return " + prop.Name + "ExistsAsync(" + prop.Name.ToLower() + ", excludeId).GetAwaiter().GetResult();");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }
            }
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 改进的分页查询方法
            sb.AppendLine("        #region 分页查询方法");
            sb.AppendLine();
            
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 分页查询" + entity.EntityDescription + "（Orleans接口兼容）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"pageNumber\">页码（从1开始）</param>");
            sb.AppendLine("        /// <param name=\"pageSize\">页大小</param>");
            sb.AppendLine("        /// <param name=\"orderBy\">排序表达式（可选）</param>");
            sb.AppendLine("        /// <param name=\"cancellationToken\">取消令牌</param>");
            sb.AppendLine("        /// <returns>分页结果</returns>");
            sb.AppendLine("        public async virtual Task<PagedResult<" + entity.EntityName + ">> GetPagedAsync(int pageNumber, int pageSize, ");
            sb.AppendLine("            Expression<Func<" + entity.EntityName + ", object>>? orderBy = null, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
            sb.AppendLine("            if (pageNumber < 1) pageNumber = 1;");
            sb.AppendLine("            if (pageSize < 1) pageSize = 20;");
            sb.AppendLine("            ");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                // 使用基类的分页方法");
            sb.AppendLine("                var orderByExpression = orderBy ?? (x => x." + entity.PrimaryKeyProperty + ");");
            sb.AppendLine("                var result = await base.GetPagedAsync(pageNumber, pageSize, orderByExpression, false, cancellationToken);");
            sb.AppendLine("                _logger.LogInformation(\"成功获取" + entity.EntityDescription + "分页数据，页码: {PageNumber}, 页大小: {PageSize}\", pageNumber, pageSize);");
            sb.AppendLine("                return result;");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (SqlSugarException ex)");
            sb.AppendLine("            {");
            sb.AppendLine("                _logger.LogError(ex, \"获取" + entity.EntityDescription + "分页数据失败，页码: {PageNumber}, 页大小: {PageSize}\", pageNumber, pageSize);");
            sb.AppendLine("                throw new DataAccessException(\"获取\" + entity.EntityDescription + \"分页数据失败\", ex);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 条件分页查询" + entity.EntityDescription + "（Orleans接口兼容）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"predicate\">查询条件</param>");
            sb.AppendLine("        /// <param name=\"pageNumber\">页码（从1开始）</param>");
            sb.AppendLine("        /// <param name=\"pageSize\">页大小</param>");
            sb.AppendLine("        /// <param name=\"orderBy\">排序表达式（可选）</param>");
            sb.AppendLine("        /// <param name=\"cancellationToken\">取消令牌</param>");
            sb.AppendLine("        /// <returns>分页结果</returns>");
            sb.AppendLine("        public async virtual Task<PagedResult<" + entity.EntityName + ">> GetPagedByConditionAsync(");
            sb.AppendLine("            Expression<Func<" + entity.EntityName + ", bool>> predicate, int pageNumber, int pageSize,");
            sb.AppendLine("            Expression<Func<" + entity.EntityName + ", object>>? orderBy = null, CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
            sb.AppendLine("            if (pageNumber < 1) pageNumber = 1;");
            sb.AppendLine("            if (pageSize < 1) pageSize = 20;");
            sb.AppendLine("            if (predicate == null) throw new ArgumentNullException(nameof(predicate));");
            sb.AppendLine("            ");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                // 使用基类的条件分页方法");
            sb.AppendLine("                var orderByExpression = orderBy ?? (x => x." + entity.PrimaryKeyProperty + ");");
            sb.AppendLine("                var result = await base.GetPagedByConditionAsync(predicate, pageNumber, pageSize, orderByExpression, false, cancellationToken);");
            sb.AppendLine("                _logger.LogInformation(\"成功获取" + entity.EntityDescription + "条件分页数据，页码: {PageNumber}, 页大小: {PageSize}\", pageNumber, pageSize);");
            sb.AppendLine("                return result;");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (SqlSugarException ex)");
            sb.AppendLine("            {");
            sb.AppendLine("                _logger.LogError(ex, \"获取\" + entity.EntityDescription + \"条件分页数据失败，页码: {PageNumber}, 页大小: {PageSize}\", pageNumber, pageSize);");
            sb.AppendLine("                throw new DataAccessException(\"获取\" + entity.EntityDescription + \"条件分页数据失败\", ex);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 业务查询方法
            sb.AppendLine("        #region 业务查询方法");
            sb.AppendLine();
            
            // 基于属性的查询方法 - 参考DictionaryTypeRepository模式
            foreach (var prop in entity.Properties.Where(p => !p.IsPrimaryKey && !p.IsNavigationProperty))
            {
                if (prop.Type.ToLower().Contains("string"))
                {
                    // GetByPropertyAsync方法 - 简洁实现
                    sb.AppendLine("        /// <summary>");
                    sb.AppendLine("        /// 根据" + prop.Name + "查询" + entity.EntityDescription);
                    sb.AppendLine("        /// </summary>");
                    sb.AppendLine("        /// <param name=\"" + prop.Name.ToLower() + "\">" + prop.Name + "</param>");
                    sb.AppendLine("        /// <param name=\"cancellationToken\">取消令牌</param>");
                    sb.AppendLine("        /// <returns>" + entity.EntityDescription + "实体</returns>");
                    sb.AppendLine("        public async Task<" + entity.EntityName + "?> GetBy" + prop.Name + "Async(string " + prop.Name.ToLower() + ", CancellationToken cancellationToken = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
                    sb.AppendLine("            try");
                    sb.AppendLine("            {");
                    sb.AppendLine("                return await GetSqlSugarClient().Queryable<" + entity.EntityName + ">()");
                    sb.AppendLine("                    .Where(entity => entity." + prop.Name + " == " + prop.Name.ToLower() + ")");
                    sb.AppendLine("                    .FirstAsync();");
                    sb.AppendLine("            }");
                    sb.AppendLine("            catch (SqlSugarException ex)");
                    sb.AppendLine("            {");
                    sb.AppendLine("                throw new Exception($\"根据" + prop.Name + "获取" + entity.EntityDescription + "失败: {ex.Message}\", ex);");
                    sb.AppendLine("            }");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    
                    // PropertyExistsAsync方法 - 改进的Exists检查
                    sb.AppendLine("        /// <summary>");
                    sb.AppendLine("        /// 检查" + prop.Name + "是否存在");
                    sb.AppendLine("        /// </summary>");
                    sb.AppendLine("        /// <param name=\"" + prop.Name.ToLower() + "\">" + prop.Name + "</param>");
                    sb.AppendLine("        /// <param name=\"excludeId\">排除的ID（用于更新时验证）</param>");
                    sb.AppendLine("        /// <param name=\"cancellationToken\">取消令牌</param>");
                    sb.AppendLine("        /// <returns>是否存在</returns>");
                    sb.AppendLine("        public async Task<bool> " + prop.Name + "ExistsAsync(string " + prop.Name.ToLower() + ", " + primaryKeyType + " excludeId = default, CancellationToken cancellationToken = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
                    sb.AppendLine("            try");
                    sb.AppendLine("            {");
                    sb.AppendLine("                var query = GetSqlSugarClient().Queryable<" + entity.EntityName + ">()");
                    sb.AppendLine("                    .Where(entity => entity." + prop.Name + " == " + prop.Name.ToLower() + ");");
                    sb.AppendLine("                ");
                    sb.AppendLine("                if (!excludeId.Equals(default(" + primaryKeyType + ")))");
                    sb.AppendLine("                {");
                    sb.AppendLine("                    query = query.Where(entity => entity." + entity.PrimaryKeyProperty + " != excludeId);");
                    sb.AppendLine("                }");
                    sb.AppendLine("                ");
                    sb.AppendLine("                var count = await query.CountAsync();");
                    sb.AppendLine("                return count > 0;");
                    sb.AppendLine("            }");
                    sb.AppendLine("            catch (SqlSugarException ex)");
                    sb.AppendLine("            {");
                    sb.AppendLine("                throw new Exception($\"检查" + entity.EntityDescription + prop.Name + "是否存在失败: {ex.Message}\", ex);");
                    sb.AppendLine("            }");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }
            }
            
            // 注：PagedResult类型的分页方法已在上面实现
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 类结束
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            return sb.ToString();
        }
    }
}