using System;
using System.Text;
using System.Collections.Generic;
using System.Linq;
using FakeMicro.Utilities.CodeGenerator;
using FakeMicro.Utilities.CodeGenerator.Entities;

namespace FakeMicro.Utilities.CodeGenerator.Templates
{
    /// <summary>
    /// 仓储接口模板
    /// 生成符合DDD规范的仓储接口定义
    /// </summary>
    public static class RepositoryInterfaceTemplate
    {
        /// <summary>
        /// 生成仓储接口代码（使用EntityMetadata）
        /// </summary>
        /// <param name="entity">实体元数据</param>
        /// <returns>生成的代码字符串</returns>
        public static string Generate(EntityMetadata entity)
        {
            var sb = new StringBuilder();
            
            // 文件头注释
            sb.AppendLine($"// <auto-generated>");
            sb.AppendLine($"//     此代码由代码生成器生成，请勿手动修改");
            sb.AppendLine($"//     生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"//     功能: {entity.EntityDescription}仓储接口定义");
            sb.AppendLine($"// </auto-generated>");
            sb.AppendLine();
            
            // Using语句
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq.Expressions;");
            sb.AppendLine("using FakeMicro.DatabaseAccess.Interfaces;");
            sb.AppendLine("using FakeMicro.Utilities;");
            
            // 使用ProjectStructureMapping获取实体命名空间
            var entityNamespace = ProjectStructureMapping.GetNamespace(GenerationType.Entity, entity.EntityName);
            sb.AppendLine($"using {entityNamespace};");
            sb.AppendLine();
            
            // 命名空间 - 使用ProjectStructureMapping获取正确的命名空间
            var repositoryInterfaceNamespace = ProjectStructureMapping.GetNamespace(GenerationType.Repository, entity.EntityName);
            sb.AppendLine($"namespace {repositoryInterfaceNamespace}");
            sb.AppendLine("{");
            
            // 仓储接口定义
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {entity.EntityDescription}仓储接口");
            sb.AppendLine($"    /// 遵循DDD原则，集成SqlSugar ORM和Orleans架构");
            sb.AppendLine("    /// </summary>");
            
            // 根据主键类型选择泛型参数
            var primaryKeyType = entity.PrimaryKeyType.ToLower() switch
            {
                "guid" => "Guid",
                "long" => "long", 
                "int" => "int",
                "string" => "string",
                _ => "Guid"
            };
            
            sb.AppendLine($"    public interface I{entity.EntityName}Repository");
            if (primaryKeyType == "Guid")
                sb.AppendLine($"        : IRepository<{entity.EntityName}, Guid>");
            else if (primaryKeyType == "long")
                sb.AppendLine($"        : IRepository<{entity.EntityName}, long>");
            else if (primaryKeyType == "int")
                sb.AppendLine($"        : IRepository<{entity.EntityName}, int>");
            else
                sb.AppendLine($"        : IRepository<{entity.EntityName}, string>");
            sb.AppendLine("    {");
            
            // Orleans特定的仓储方法（基于Grain ID的操作）
            sb.AppendLine("        #region Orleans Grain特定操作");
            sb.AppendLine();
            
            // GetAsync - 通过Grain ID获取（无参数，使用Grain的ID作为主键）
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 通过Orleans Grain ID获取{entity.EntityDescription}实体");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"cancellationToken\">取消令牌</param>");
            sb.AppendLine($"        /// <returns>实体对象，如果不存在则返回null</returns>");
            sb.AppendLine($"        new Task<{entity.EntityName}?> GetByIdAsync({primaryKeyType} id, CancellationToken cancellationToken = default);");
            sb.AppendLine();
            
            // CreateAsync - 创建实体并返回创建后的实体
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 创建{entity.EntityDescription}实体并返回创建后的实体");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"entity\">{entity.EntityDescription}实体</param>");
            sb.AppendLine($"        /// <param name=\"cancellationToken\">取消令牌</param>");
            sb.AppendLine($"        /// <returns>创建后的实体对象</returns>");
            sb.AppendLine($"        Task<{entity.EntityName}?> CreateAndReturnAsync({entity.EntityName} entity, CancellationToken cancellationToken = default);");
            sb.AppendLine();
            
            // UpdateAndReturnAsync - 更新实体并返回更新后的实体
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 更新{entity.EntityDescription}实体并返回更新后的实体");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"entity\">{entity.EntityDescription}实体</param>");
            sb.AppendLine($"        /// <param name=\"cancellationToken\">取消令牌</param>");
            sb.AppendLine($"        /// <returns>更新后的实体对象</returns>");
            sb.AppendLine($"        Task<{entity.EntityName}?> UpdateAndReturnAsync({entity.EntityName} entity, CancellationToken cancellationToken = default);");
            sb.AppendLine();
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 业务特定查询操作
            sb.AppendLine("        #region 业务特定查询操作");
            sb.AppendLine();
            
            // GetWithIncludesAsync - 包含导航属性的查询（重写基方法以提供更具体的导航属性）
            var navigationProperties = entity.Properties.Where(p => p.IsNavigationProperty).ToList();
            if (navigationProperties.Any())
            {
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// 获取{entity.EntityDescription}实体，包含所有导航属性");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        /// <param name=\"cancellationToken\">取消令牌</param>");
                sb.AppendLine($"        /// <returns>包含导航属性的实体对象</returns>");
                sb.AppendLine($"        new Task<{entity.EntityName}?> GetByIdWithIncludesAsync({primaryKeyType} id, CancellationToken cancellationToken = default);");
                sb.AppendLine();
            }
            
            // 根据实体的特定属性生成查询方法
            var searchableProperties = entity.Properties.Where(p => 
                !p.IsPrimaryKey && 
                (p.Type.ToLower().Contains("string") || p.Type.ToLower().Contains("int") || p.Type.ToLower().Contains("guid")))
                .Take(3) // 限制生成3个常用查询方法
                .ToList();
                
            foreach (var prop in searchableProperties)
            {
                var methodName = $"GetBy{prop.Name}Async";
                var returnType = prop.Type.ToLower().Contains("list") || prop.Type.ToLower().Contains("collection") 
                    ? $"IEnumerable<{entity.EntityName}>" 
                    : $"{entity.EntityName}?";
                    
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// 根据{prop.Name}获取{entity.EntityDescription}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        /// <param name=\"{prop.Name.ToLower()}\">{prop.Name}值</param>");
                sb.AppendLine($"        /// <param name=\"cancellationToken\">取消令牌</param>");
                sb.AppendLine($"        /// <returns>{(returnType.Contains("IEnumerable") ? "符合条件的实体集合" : "实体对象，如果不存在则返回null")}</returns>");
                sb.AppendLine($"        Task<{returnType}> {methodName}({prop.Type} {prop.Name.ToLower()}, CancellationToken cancellationToken = default);");
                sb.AppendLine();
            }
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 批量业务操作
            sb.AppendLine("        #region 批量业务操作");
            sb.AppendLine();
            
            // CreateRangeAndReturnAsync - 批量创建并返回创建后的实体
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 批量创建{entity.EntityDescription}实体并返回创建后的实体");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"entities\">{entity.EntityDescription}实体集合</param>");
            sb.AppendLine($"        /// <param name=\"cancellationToken\">取消令牌</param>");
            sb.AppendLine($"        /// <returns>创建后的实体集合</returns>");
            sb.AppendLine($"        Task<IEnumerable<{entity.EntityName}>> CreateRangeAndReturnAsync(IEnumerable<{entity.EntityName}> entities, CancellationToken cancellationToken = default);");
            sb.AppendLine();
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 软删除支持
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine("        #region 软删除操作");
                sb.AppendLine();
                
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// 软删除{entity.EntityDescription}实体");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        /// <param name=\"id\">主键ID</param>");
                sb.AppendLine($"        /// <param name=\"cancellationToken\">取消令牌</param>");
                sb.AppendLine($"        /// <returns>删除是否成功</returns>");
                sb.AppendLine($"        Task<bool> SoftDeleteByIdAsync({primaryKeyType} id, CancellationToken cancellationToken = default);");
                sb.AppendLine();
                
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// 批量软删除{entity.EntityDescription}实体");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        /// <param name=\"ids\">主键ID集合</param>");
                sb.AppendLine($"        /// <param name=\"cancellationToken\">取消令牌</param>");
                sb.AppendLine($"        /// <returns>删除是否成功</returns>");
                sb.AppendLine($"        Task<bool> SoftDeleteRangeByIdsAsync(IEnumerable<{primaryKeyType}> ids, CancellationToken cancellationToken = default);");
                sb.AppendLine();
                
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// 恢复软删除的{entity.EntityDescription}实体");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        /// <param name=\"id\">主键ID</param>");
                sb.AppendLine($"        /// <param name=\"cancellationToken\">取消令牌</param>");
                sb.AppendLine($"        /// <returns>恢复是否成功</returns>");
                sb.AppendLine($"        Task<bool> RestoreByIdAsync({primaryKeyType} id, CancellationToken cancellationToken = default);");
                sb.AppendLine();
                
                // 获取未删除的实体
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// 获取未删除的{entity.EntityDescription}实体");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        /// <param name=\"id\">主键ID</param>");
                sb.AppendLine($"        /// <param name=\"cancellationToken\">取消令牌</param>");
                sb.AppendLine($"        /// <returns>未删除的实体对象</returns>");
                sb.AppendLine($"        Task<{entity.EntityName}?> GetActiveByIdAsync({primaryKeyType} id, CancellationToken cancellationToken = default);");
                sb.AppendLine();
                
                sb.AppendLine("        #endregion");
                sb.AppendLine();
            }
            
            // Orleans特定的分页查询扩展
            sb.AppendLine("        #region Orleans分页查询扩展");
            sb.AppendLine();
            
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 获取{entity.EntityDescription}分页列表（包含关联数据）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"pageNumber\">页码（从1开始）</param>");
            sb.AppendLine($"        /// <param name=\"pageSize\">每页大小</param>");
            sb.AppendLine($"        /// <param name=\"orderBy\">排序表达式</param>");
            sb.AppendLine($"        /// <param name=\"cancellationToken\">取消令牌</param>");
            sb.AppendLine($"        /// <returns>分页结果</returns>");
            sb.AppendLine($"        new Task<PagedResult<{entity.EntityName}>> GetPagedAsync(int pageNumber, int pageSize, ");
            sb.AppendLine($"            Expression<Func<{entity.EntityName}, object>>? orderBy = null, CancellationToken cancellationToken = default);");
            sb.AppendLine();
            
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 根据条件获取{entity.EntityDescription}分页列表");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"predicate\">查询条件</param>");
            sb.AppendLine($"        /// <param name=\"pageNumber\">页码（从1开始）</param>");
            sb.AppendLine($"        /// <param name=\"pageSize\">每页大小</param>");
            sb.AppendLine($"        /// <param name=\"orderBy\">排序表达式</param>");
            sb.AppendLine($"        /// <param name=\"cancellationToken\">取消令牌</param>");
            sb.AppendLine($"        /// <returns>分页结果</returns>");
            sb.AppendLine($"        new Task<PagedResult<{entity.EntityName}>> GetPagedByConditionAsync(");
            sb.AppendLine($"            Expression<Func<{entity.EntityName}, bool>> predicate, int pageNumber, int pageSize,");
            sb.AppendLine($"            Expression<Func<{entity.EntityName}, object>>? orderBy = null, CancellationToken cancellationToken = default);");
            sb.AppendLine();
            
            sb.AppendLine("        #endregion");
            
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            return sb.ToString();
        }

        /// <summary>
        /// 生成仓储接口代码（使用EntityMetadata）
        /// </summary>
        /// <param name="entity">实体元数据</param>
        /// <returns>生成的代码字符串</returns>
        public static string GenerateCode(EntityMetadata entity)
        {
            return Generate(entity);
        }
    }
}