using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FakeMicro.Utilities.CodeGenerator.Templates
{
    public static class RepositoryImplementationTemplate
    {
        public static string Generate(EntityMetadata entity)
        {
            var sb = new StringBuilder();
            
            // 文件头注释
            sb.AppendLine($"// <auto-generated>");
            sb.AppendLine($"//     此代码由代码生成器生成，请勿手动修改");
            sb.AppendLine($"//     生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"//     功能: {entity.EntityDescription}仓储实现类");
            sb.AppendLine($"// </auto-generated>");
            sb.AppendLine();
            
            // Using语句
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();
            
            // 命名空间
            sb.AppendLine($"namespace {entity.Namespace}.Repositories");
            sb.AppendLine("{");
            
            // 仓储实现类定义
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {entity.EntityDescription}仓储实现类");
            sb.AppendLine("    /// </summary>");
            
            // 根据主键类型选择泛型参数
            var primaryKeyType = entity.PrimaryKeyType.ToLower() switch
            {
                "guid" => "Guid",
                "long" => "long", 
                "int" => "int",
                "string" => "string",
                _ => "Guid"
            };
            
            sb.AppendLine($"    public class {entity.EntityName}Repository : I{entity.EntityName}Repository");
            sb.AppendLine("    {");
            
            sb.AppendLine("        // TODO: 在这里注入必要的数据访问依赖");
            sb.AppendLine($"        public {entity.EntityName}Repository()");
            sb.AppendLine("        {");
            sb.AppendLine("            // 构造函数注入依赖项");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 基础CRUD操作
            sb.AppendLine("        #region 基础CRUD操作");
            sb.AppendLine();
            
            // GetAsync - 通过主键获取
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 通过主键获取{entity.EntityDescription}");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        /// <param name=\"id\">主键值</param>");
            sb.AppendLine($"        /// <returns>实体对象</returns>");
            sb.AppendLine($"        public virtual async Task<{entity.EntityName}?> GetAsync({primaryKeyType} id)");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: 实现获取实体逻辑");
            sb.AppendLine($"            return await Task.FromResult<{entity.EntityName}?>(null);");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // CreateAsync - 创建实体
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 创建{entity.EntityDescription}实体");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        /// <param name=\"entity\">{entity.EntityDescription}实体</param>");
            sb.AppendLine($"        /// <returns>创建后的实体对象</returns>");
            sb.AppendLine($"        public virtual async Task<{entity.EntityName}?> CreateAsync({entity.EntityName} entity)");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: 实现创建实体逻辑");
            sb.AppendLine("            if (entity == null)");
            sb.AppendLine("            {");
            sb.AppendLine("                throw new ArgumentNullException(nameof(entity));");
            sb.AppendLine("            }");
            sb.AppendLine("            // 设置创建时间等字段");
            sb.AppendLine($"            return await Task.FromResult<{entity.EntityName}?>(entity);");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // UpdateAsync - 更新实体
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 更新{entity.EntityDescription}实体");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        /// <param name=\"entity\">{entity.EntityDescription}实体</param>");
            sb.AppendLine($"        /// <returns>更新后的实体对象</returns>");
            sb.AppendLine($"        public virtual async Task<{entity.EntityName}?> UpdateAsync({entity.EntityName} entity)");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: 实现更新实体逻辑");
            sb.AppendLine("            if (entity == null)");
            sb.AppendLine("            {");
            sb.AppendLine("                throw new ArgumentNullException(nameof(entity));");
            sb.AppendLine("            }");
            sb.AppendLine("            // 设置更新时间等字段");
            sb.AppendLine($"            return await Task.FromResult<{entity.EntityName}?>(entity);");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // DeleteAsync - 删除实体
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 删除{entity.EntityDescription}实体");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        /// <param name=\"id\">主键值</param>");
            sb.AppendLine($"        /// <returns>删除是否成功</returns>");
            sb.AppendLine($"        public virtual async Task<bool> DeleteAsync({primaryKeyType} id)");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: 实现删除实体逻辑（支持软删除）");
            sb.AppendLine("            return await Task.FromResult(true);");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 业务查询操作
            sb.AppendLine("        #region 业务查询操作");
            sb.AppendLine();
            
            // GetAllAsync - 获取所有实体
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 获取{entity.EntityDescription}所有实体列表");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        /// <returns>实体列表</returns>");
            sb.AppendLine($"        public virtual async Task<List<{entity.EntityName}>> GetAllAsync()");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: 实现获取所有实体逻辑");
            sb.AppendLine($"            return await Task.FromResult(new List<{entity.EntityName}>());");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // ExistsAsync - 存在性检查
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 检查{entity.EntityDescription}是否存在");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        /// <param name=\"predicate\">查询条件</param>");
            sb.AppendLine($"        /// <returns>是否存在</returns>");
            sb.AppendLine($"        public virtual async Task<bool> ExistsAsync(System.Linq.Expressions.Expression<Func<{entity.EntityName}, bool>> predicate)");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: 实现存在性检查逻辑");
            sb.AppendLine("            return await Task.FromResult(false);");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // CountAsync - 数量统计
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 统计{entity.EntityDescription}数量");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        /// <param name=\"predicate\">查询条件，可选</param>");
            sb.AppendLine($"        /// <returns>数量</returns>");
            sb.AppendLine($"        public virtual async Task<int> CountAsync(System.Linq.Expressions.Expression<Func<{entity.EntityName}, bool>>? predicate = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: 实现数量统计逻辑");
            sb.AppendLine("            return await Task.FromResult(0);");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 批量操作
            sb.AppendLine("        #region 批量操作");
            sb.AppendLine();
            
            // CreateRangeAsync - 批量创建
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 批量创建{entity.EntityDescription}实体");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        /// <param name=\"entities\">{entity.EntityDescription}实体集合</param>");
            sb.AppendLine($"        /// <returns>创建后的实体集合</returns>");
            sb.AppendLine($"        public virtual async Task<IEnumerable<{entity.EntityName}>> CreateRangeAsync(IEnumerable<{entity.EntityName}> entities)");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: 实现批量创建逻辑");
            sb.AppendLine("            if (entities == null || !entities.Any())");
            sb.AppendLine("            {");
            sb.AppendLine($"                return new List<{entity.EntityName}>();");
            sb.AppendLine("            }");
            sb.AppendLine("            return entities;");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // UpdateRangeAsync - 批量更新
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 批量更新{entity.EntityDescription}实体");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        /// <param name=\"entities\">{entity.EntityDescription}实体集合</param>");
            sb.AppendLine($"        /// <returns>更新后的实体集合</returns>");
            sb.AppendLine($"        public virtual async Task<IEnumerable<{entity.EntityName}>> UpdateRangeAsync(IEnumerable<{entity.EntityName}> entities)");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: 实现批量更新逻辑");
            sb.AppendLine("            if (entities == null || !entities.Any())");
            sb.AppendLine("            {");
            sb.AppendLine($"                return new List<{entity.EntityName}>();");
            sb.AppendLine("            }");
            sb.AppendLine("            return entities;");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // DeleteRangeAsync - 批量删除
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 批量删除{entity.EntityDescription}实体");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        /// <param name=\"entities\">{entity.EntityDescription}实体集合</param>");
            sb.AppendLine($"        /// <returns>删除是否成功</returns>");
            sb.AppendLine($"        public virtual async Task<bool> DeleteRangeAsync(IEnumerable<{entity.EntityName}> entities)");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: 实现批量删除逻辑");
            sb.AppendLine("            return await Task.FromResult(true);");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 软删除支持
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine("        #region 软删除操作");
                sb.AppendLine();
                
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// 软删除{entity.EntityDescription}实体");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        /// <param name=\"id\">主键值</param>");
                sb.AppendLine($"        /// <returns>删除是否成功</returns>");
                sb.AppendLine($"        public virtual async Task<bool> SoftDeleteAsync({primaryKeyType} id)");
                sb.AppendLine("        {");
                sb.AppendLine("            // TODO: 实现软删除逻辑（设置IsDeleted = true）");
                sb.AppendLine("            return await Task.FromResult(true);");
                sb.AppendLine("        }");
                sb.AppendLine();
                
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// 批量软删除{entity.EntityDescription}实体");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        /// <param name=\"entities\">{entity.EntityDescription}实体集合</param>");
                sb.AppendLine($"        /// <returns>删除是否成功</returns>");
                sb.AppendLine($"        public virtual async Task<bool> SoftDeleteRangeAsync(IEnumerable<{entity.EntityName}> entities)");
                sb.AppendLine("        {");
                sb.AppendLine("            // TODO: 实现批量软删除逻辑");
                sb.AppendLine("            return await Task.FromResult(true);");
                sb.AppendLine("        }");
                sb.AppendLine();
                
                sb.AppendLine("        #endregion");
                sb.AppendLine();
            }
            
            // 结束类定义
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            return sb.ToString();
        }
    }
}