using System;
using System.Text;
using System.Collections.Generic;
using System.Linq;
using FakeMicro.Utilities.CodeGenerator.Entities;

namespace FakeMicro.Utilities.CodeGenerator.Templates
{
    /// <summary>
    /// 仓储接口模板
    /// 生成符合DDD规范的仓储接口定义
    /// </summary>
    public static class RepositoryInterfaceTemplate
    {
        /// <summary>
        /// 生成仓储接口代码（使用EntityMetadata）
        /// </summary>
        /// <param name="entity">实体元数据</param>
        /// <returns>生成的代码字符串</returns>
        public static string Generate(EntityMetadata entity)
        {
            var sb = new StringBuilder();
            
            // 文件头注释
            sb.AppendLine($"// <auto-generated>");
            sb.AppendLine($"//     此代码由代码生成器生成，请勿手动修改");
            sb.AppendLine($"//     生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"//     功能: {entity.EntityDescription}仓储接口定义");
            sb.AppendLine($"// </auto-generated>");
            sb.AppendLine();
            
            // Using语句
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq.Expressions;");
            sb.AppendLine();
            
            // 命名空间
            sb.AppendLine($"namespace {entity.Namespace}.Repositories");
            sb.AppendLine("{");
            
            // 仓储接口定义
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {entity.EntityDescription}仓储接口");
            sb.AppendLine($"    /// 遵循DDD原则，集成SqlSugar ORM和Orleans架构");
            sb.AppendLine("    /// </summary>");
            
            // 根据主键类型选择泛型参数
            var primaryKeyType = entity.PrimaryKeyType.ToLower() switch
            {
                "guid" => "Guid",
                "long" => "long", 
                "int" => "int",
                "string" => "string",
                _ => "Guid"
            };
            
            sb.AppendLine($"    public interface I{entity.EntityName}Repository");
            if (primaryKeyType == "Guid")
                sb.AppendLine($"        : IRepository<{entity.EntityName}, Guid>");
            else if (primaryKeyType == "long")
                sb.AppendLine($"        : IRepository<{entity.EntityName}, long>");
            else if (primaryKeyType == "int")
                sb.AppendLine($"        : IRepository<{entity.EntityName}, int>");
            else
                sb.AppendLine($"        : IRepository<{entity.EntityName}, string>");
            sb.AppendLine("    {");
            
            // 基础CRUD操作（覆盖或扩展基接口）
            sb.AppendLine("        #region 基础CRUD操作");
            sb.AppendLine();
            
            // GetAsync - 通过Grain ID获取
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 通过Orleans Grain ID获取{entity.EntityDescription}");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <returns>实体对象，如果不存在则返回null</returns>");
            sb.AppendLine($"        Task<{entity.EntityName}?> GetAsync();");
            sb.AppendLine();
            
            // CreateAsync - 创建实体
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 创建{entity.EntityDescription}实体");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"entity\">{entity.EntityDescription}实体</param>");
            sb.AppendLine($"        /// <returns>创建后的实体对象</returns>");
            sb.AppendLine($"        Task<{entity.EntityName}?> CreateAsync({entity.EntityName} entity);");
            sb.AppendLine();
            
            // UpdateAsync - 更新实体
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 更新{entity.EntityDescription}实体");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"entity\">{entity.EntityDescription}实体</param>");
            sb.AppendLine($"        /// <returns>更新后的实体对象</returns>");
            sb.AppendLine($"        Task<{entity.EntityName}?> UpdateAsync({entity.EntityName} entity);");
            sb.AppendLine();
            
            // DeleteAsync - 删除实体
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 删除{entity.EntityDescription}实体");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <returns>删除是否成功</returns>");
            sb.AppendLine($"        Task<bool> DeleteAsync();");
            sb.AppendLine();
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 业务查询操作
            sb.AppendLine("        #region 业务查询操作");
            sb.AppendLine();
            
            // GetWithIncludesAsync - 包含导航属性的查询
            var navigationProperties = entity.Properties.Where(p => p.IsNavigationProperty).ToList();
            if (navigationProperties.Any())
            {
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// 获取{entity.EntityDescription}实体，包含导航属性");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        /// <returns>包含导航属性的实体对象</returns>");
                sb.AppendLine($"        Task<{entity.EntityName}?> GetWithIncludesAsync();");
                sb.AppendLine();
            }
            
            // ExistsAsync - 存在性检查
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 检查{entity.EntityDescription}是否存在");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"predicate\">查询条件</param>");
            sb.AppendLine($"        /// <returns>是否存在</returns>");
            sb.AppendLine($"        Task<bool> ExistsAsync(Expression<Func<{entity.EntityName}, bool>> predicate);");
            sb.AppendLine();
            
            // CountAsync - 数量统计
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 统计{entity.EntityDescription}数量");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"predicate\">查询条件，可选</param>");
            sb.AppendLine($"        /// <returns>数量</returns>");
            sb.AppendLine($"        Task<int> CountAsync(Expression<Func<{entity.EntityName}, bool>>? predicate = null);");
            sb.AppendLine();
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 批量操作
            sb.AppendLine("        #region 批量操作");
            sb.AppendLine();
            
            // CreateRangeAsync - 批量创建
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 批量创建{entity.EntityDescription}实体");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"entities\">{entity.EntityDescription}实体集合</param>");
            sb.AppendLine($"        /// <returns>创建后的实体集合</returns>");
            sb.AppendLine($"        Task<IEnumerable<{entity.EntityName}>> CreateRangeAsync(IEnumerable<{entity.EntityName}> entities);");
            sb.AppendLine();
            
            // UpdateRangeAsync - 批量更新
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 批量更新{entity.EntityDescription}实体");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"entities\">{entity.EntityDescription}实体集合</param>");
            sb.AppendLine($"        /// <returns>更新后的实体集合</returns>");
            sb.AppendLine($"        Task<IEnumerable<{entity.EntityName}>> UpdateRangeAsync(IEnumerable<{entity.EntityName}> entities);");
            sb.AppendLine();
            
            // DeleteRangeAsync - 批量删除
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 批量删除{entity.EntityDescription}实体");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"entities\">{entity.EntityDescription}实体集合</param>");
            sb.AppendLine($"        /// <returns>删除是否成功</returns>");
            sb.AppendLine($"        Task<bool> DeleteRangeAsync(IEnumerable<{entity.EntityName}> entities);");
            sb.AppendLine();
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 软删除支持
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine("        #region 软删除操作");
                sb.AppendLine();
                
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// 软删除{entity.EntityDescription}实体");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        /// <returns>删除是否成功</returns>");
                sb.AppendLine($"        Task<bool> SoftDeleteAsync();");
                sb.AppendLine();
                
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// 批量软删除{entity.EntityDescription}实体");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        /// <param name=\"entities\">{entity.EntityDescription}实体集合</param>");
                sb.AppendLine($"        /// <returns>删除是否成功</returns>");
                sb.AppendLine($"        Task<bool> SoftDeleteRangeAsync(IEnumerable<{entity.EntityName}> entities);");
                sb.AppendLine();
                
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// 恢复软删除的{entity.EntityDescription}实体");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        /// <returns>恢复是否成功</returns>");
                sb.AppendLine($"        Task<bool> RestoreAsync();");
                sb.AppendLine();
                
                sb.AppendLine("        #endregion");
                sb.AppendLine();
            }
            
            // 事务操作
            sb.AppendLine("        #region 事务操作");
            sb.AppendLine();
            
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 在事务中执行{entity.EntityDescription}的批量操作");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"operations\">操作集合</param>");
            sb.AppendLine($"        /// <returns>事务执行结果</returns>");
            sb.AppendLine($"        Task<bool> ExecuteInTransactionAsync(Func<Task> operations);");
            sb.AppendLine();
            
            sb.AppendLine("        #endregion");
            sb.AppendLine();
            
            // 分页查询扩展
            sb.AppendLine("        #region 分页查询扩展");
            sb.AppendLine();
            
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 获取{entity.EntityDescription}分页列表（包含关联数据）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"pageIndex\">页索引（从0开始）</param>");
            sb.AppendLine($"        /// <param name=\"pageSize\">每页大小</param>");
            sb.AppendLine($"        /// <param name=\"includeProperties\">要包含的导航属性</param>");
            sb.AppendLine($"        /// <returns>分页结果</returns>");
            sb.AppendLine($"        Task<IPagedResult<{entity.EntityName}>> GetPagedWithIncludesAsync(");
            sb.AppendLine($"            int pageIndex, int pageSize, params string[] includeProperties);");
            sb.AppendLine();
            
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 根据条件获取{entity.EntityDescription}分页列表");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"pageIndex\">页索引（从0开始）</param>");
            sb.AppendLine($"        /// <param name=\"pageSize\">每页大小</param>");
            sb.AppendLine($"        /// <param name=\"predicate\">查询条件</param>");
            sb.AppendLine($"        /// <param name=\"includeProperties\">要包含的导航属性</param>");
            sb.AppendLine($"        /// <returns>分页结果</returns>");
            sb.AppendLine($"        Task<IPagedResult<{entity.EntityName}>> GetPagedByConditionAsync(");
            sb.AppendLine($"            int pageIndex, int pageSize, Expression<Func<{entity.EntityName}, bool>> predicate, ");
            sb.AppendLine($"            params string[] includeProperties);");
            sb.AppendLine();
            
            sb.AppendLine("        #endregion");
            
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            return sb.ToString();
        }

        /// <summary>
        /// 生成仓储接口代码（使用EntityInfo兼容旧版本）
        /// </summary>
        /// <param name="entity">实体信息</param>
        /// <returns>生成的代码字符串</returns>
        public static string GenerateCode(EntityInfo entity)
        {
            // 将EntityInfo转换为EntityMetadata
            var entityMetadata = new EntityMetadata
            {
                EntityName = entity.EntityName,
                EntityDescription = string.IsNullOrEmpty(entity.Description) ? entity.EntityName : entity.Description,
                Namespace = entity.Namespace,
                PrimaryKeyProperty = entity.PrimaryKeyName,
                PrimaryKeyType = entity.PrimaryKeyType,
                Properties = entity.Properties?.Select(p => new PropertyMetadata
                {
                    Name = p.Name,
                    Type = p.Type,
                    IsNullable = p.IsNullable,
                    IsPrimaryKey = p.IsPrimaryKey,
                    //IsForeignKey = p.IsForeignKey,
                    //IsNavigationProperty = !string.IsNullOrEmpty(p.ForeignEntityName), // 有外键实体名称的才作为导航属性
                    //RelatedEntityName = p.ForeignEntityName,
                    IsRequired = p.IsRequired,
                    DefaultValue = p.DefaultValue,
                    MaxLength = p.MaxLength
                }).ToList(),
                IsSoftDeletable = entity.SupportSoftDelete,
                //SupportMultiTenant = entity.SupportMultiTenant
            };

            return Generate(entityMetadata);
        }
    }
}