using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using FakeMicro.Utilities.CodeGenerator.Entities;
using FakeMicro.Utilities.CodeGenerator;

namespace FakeMicro.Utilities.CodeGenerator.Templates
{
    /// <summary>
    /// 请求类模板 - 生成独立的请求类文件
    /// 遵循Orleans最佳实践，将请求类与接口分离
    /// </summary>
    public static class RequestTemplate
    {
        /// <summary>
        /// 生成请求类代码
        /// </summary>
        /// <param name="entity">实体元数据</param>
        /// <returns>生成的代码</returns>
        public static string Generate(EntityMetadata entity)
        {
            var sb = new StringBuilder();
            
            // 文件头部注释
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     此代码由代码生成器生成。");
            sb.AppendLine("//     运行时版本: " + Environment.Version.ToString());
            sb.AppendLine("//     生成时间: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
            sb.AppendLine("//     </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();

            // using语句 - 增强验证和Orleans支持
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.ComponentModel.DataAnnotations;");
            sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Text.RegularExpressions;");
            sb.AppendLine("using Orleans.Concurrency;");
            sb.AppendLine();

            // 命名空间
            sb.AppendLine("namespace FakeMicro.Interfaces.Models.Requests");
            sb.AppendLine("{");

            // 创建请求类
            GenerateCreateRequestClass(sb, entity);
            sb.AppendLine();

            // 更新请求类
            GenerateUpdateRequestClass(sb, entity);
            sb.AppendLine();

            // 批量操作请求类
            GenerateBatchRequestClass(sb, entity);
            sb.AppendLine();

            // 查询请求类
            GenerateQueryRequestClass(sb, entity);
            sb.AppendLine();

            // 搜索请求类
            GenerateSearchRequestClass(sb, entity);

            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 生成创建请求类 - 增强验证支持
        /// </summary>
        private static void GenerateCreateRequestClass(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 创建{entity.EntityDescription}请求");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine("    [GenerateSerializer]");
            sb.AppendLine("    [Immutable]");
            sb.AppendLine($"    public class Create{entity.EntityName}Request");
            sb.AppendLine("    {");

            // 生成属性（排除主键和只读属性）
            var properties = entity.Properties
                .Where(p => !p.IsPrimaryKey)
                .ToList();

            int idCounter = 0;
            foreach (var property in properties)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// {property.Description ?? property.Name}");
                sb.AppendLine("        /// </summary>");
                
                // 添加验证特性
                if (property.IsRequired)
                {
                    sb.AppendLine("        [Required(ErrorMessage = \"{0}是必需的\")]");
                }
                
                if (property.MaxLength.HasValue && property.MaxLength.Value > 0)
                {
                    sb.AppendLine($"        [MaxLength({property.MaxLength.Value}, ErrorMessage = \"{{0}}长度不能超过{property.MaxLength.Value}个字符\")]");
                }

                if (property.MinLength.HasValue && property.MinLength.Value > 0)
                {
                    sb.AppendLine($"        [MinLength({property.MinLength.Value}, ErrorMessage = \"{{0}}长度不能少于{property.MinLength.Value}个字符\")]");
                }

                // 特殊字段验证
                if (property.Name.ToLower().Contains("email") && property.Type == "string")
                {
                    sb.AppendLine("        [EmailAddress(ErrorMessage = \"{0}格式不正确\")]");
                }
                else if (property.Name.ToLower().Contains("phone") && property.Type == "string")
                {
                    sb.AppendLine("        [Phone(ErrorMessage = \"{0}格式不正确\")]");
                }
                else if (property.Name.ToLower().Contains("url") && property.Type == "string")
                {
                    sb.AppendLine("        [Url(ErrorMessage = \"{0}格式不正确\")]");
                }

                // 添加Orleans序列化特性
                sb.AppendLine($"        [Id({idCounter})]");
                
                // 处理可空类型
                string propertyType = property.IsRequired && property.Type != "string" 
                    ? property.Type 
                    : property.Type + "?";
                    
                sb.AppendLine($"        public {propertyType} {property.Name} {{ get; set; }}");
                sb.AppendLine();
                idCounter++;
            }

            // 添加验证方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 手动验证请求数据");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <returns>验证结果</returns>");
            sb.AppendLine("        public (bool IsValid, List<string> Errors) Validate()");
            sb.AppendLine("        {");
            sb.AppendLine("            var errors = new List<string>();");
            sb.AppendLine();
            
            // 生成验证逻辑
            foreach (var property in properties)
            {
                if (property.IsRequired)
                {
                    if (property.Type == "string")
                    {
                        sb.AppendLine($"            if (string.IsNullOrWhiteSpace({property.Name}))");
                        sb.AppendLine($"                errors.Add(\"{property.Name}是必需的\");");
                    }
                    else
                    {
                        sb.AppendLine($"            if ({property.Name} == null)");
                        sb.AppendLine($"                errors.Add(\"{property.Name}是必需的\");");
                    }
                    sb.AppendLine();
                }
                
                if (property.Type == "string" && property.MaxLength.HasValue)
                {
                    sb.AppendLine($"            if ({property.Name}?.Length > {property.MaxLength.Value})");
                    sb.AppendLine($"                errors.Add(\"{property.Name}长度不能超过{property.MaxLength.Value}个字符\");");
                    sb.AppendLine();
                }
            }
            
            sb.AppendLine("            return (errors.Count == 0, errors);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成更新请求类
        /// </summary>
        private static void GenerateUpdateRequestClass(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 更新{entity.EntityDescription}请求");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine("    [GenerateSerializer]");
            sb.AppendLine("    [Immutable]");
            sb.AppendLine($"    public class Update{entity.EntityName}Request");
            sb.AppendLine("    {");

            // 主键属性
            var primaryKey = entity.Properties.FirstOrDefault(p => p.IsPrimaryKey);
            if (primaryKey != null)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// {primaryKey.Description ?? primaryKey.Name}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        [Id(0)]");
                sb.AppendLine($"        public {primaryKey.Type} {primaryKey.Name} {{ get; set; }}");
                sb.AppendLine();
            }

            // 生成可更新属性
            var updatableProperties = entity.Properties
                .Where(p => !p.IsPrimaryKey && !p.IsReadOnly)
                .ToList();

            int idCounter = 1;
            foreach (var property in updatableProperties)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// {property.Description ?? property.Name}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        [Id({idCounter})]");
                sb.AppendLine($"        public {property.Type}? {property.Name} {{ get; set; }}");
                sb.AppendLine();
                idCounter++;
            }

            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成批量操作请求类
        /// </summary>
        private static void GenerateBatchRequestClass(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 批量操作{entity.EntityDescription}请求");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine("    [GenerateSerializer]");
            sb.AppendLine("    [Immutable]");
            sb.AppendLine($"    public class Batch{entity.EntityName}Request");
            sb.AppendLine("    {");

            // 主键列表
            var primaryKey = entity.Properties.FirstOrDefault(p => p.IsPrimaryKey);
            if (primaryKey != null)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// {primaryKey.Description ?? primaryKey.Name}列表");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        [Id(0)]");
                sb.AppendLine($"        public List<{primaryKey.Type}> {primaryKey.Name}s {{ get; set; }} = new();");
                sb.AppendLine();
            }

            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 操作类型");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [Id(1)]");
            sb.AppendLine("        public BatchOperationType OperationType { get; set; }");
            sb.AppendLine();

            sb.AppendLine("    }");

            // 批量操作类型枚举
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 批量操作类型");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public enum BatchOperationType");
            sb.AppendLine("    {");
            sb.AppendLine("        Delete,");
            sb.AppendLine("        SoftDelete,");
            sb.AppendLine("        Restore,");
            sb.AppendLine("        Archive");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成查询请求类
        /// </summary>
        private static void GenerateQueryRequestClass(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 查询{entity.EntityDescription}请求");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine("    [GenerateSerializer]");
            sb.AppendLine("    [Immutable]");
            sb.AppendLine($"    public class Query{entity.EntityName}Request");
            sb.AppendLine("    {");

            // 主键属性
            var primaryKey = entity.Properties.FirstOrDefault(p => p.IsPrimaryKey);
            if (primaryKey != null)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// {primaryKey.Description ?? primaryKey.Name}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        [Id(0)]");
                sb.AppendLine($"        public {primaryKey.Type} {primaryKey.Name} {{ get; set; }}");
                sb.AppendLine();
            }

            // 包含软删除记录
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 是否包含软删除的记录");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [Id(1)]");
            sb.AppendLine("        public bool IncludeDeleted { get; set; } = false;");
            sb.AppendLine();

            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成搜索请求类
        /// </summary>
        private static void GenerateSearchRequestClass(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 搜索{entity.EntityDescription}请求");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine("    [GenerateSerializer]");
            sb.AppendLine("    [Immutable]");
            sb.AppendLine($"    public class Search{entity.EntityName}Request");
            sb.AppendLine("    {");

            // 搜索关键词
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 搜索关键词");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [Id(0)]");
            sb.AppendLine("        public string Keyword { get; set; } = string.Empty;");
            sb.AppendLine();

            // 分页参数
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 页码（从1开始）");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [Id(1)]");
            sb.AppendLine("        public int Page { get; set; } = 1;");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 每页大小");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine("        public int PageSize { get; set; } = 20;");
            sb.AppendLine();

            // 排序参数
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 排序字段");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [Id(3)]");
            sb.AppendLine("        public string SortBy { get; set; } = \"CreatedAt\";");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 排序方向");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [Id(4)]");
            sb.AppendLine("        public SortDirection SortDirection { get; set; } = SortDirection.Descending;");
            sb.AppendLine();

            // 过滤参数
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 过滤条件");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [Id(5)]");
            sb.AppendLine("        public Dictionary<string, object> Filters { get; set; } = new();");
            sb.AppendLine();

            sb.AppendLine("    }");

            // 排序方向枚举
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 排序方向");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public enum SortDirection");
            sb.AppendLine("    {");
            sb.AppendLine("        Ascending,");
            sb.AppendLine("        Descending");
            sb.AppendLine("    }");
        }
    }
}