using System;
using System.Collections.Generic;
using System.Text;

namespace FakeMicro.Utilities.CodeGenerator.Templates
{
    /// <summary>
    /// 结果类模板 - 专门用于生成CRUD操作的结果类
    /// </summary>
    public static class ResultTemplate
    {
        /// <summary>
        /// 生成实体相关的所有结果类
        /// </summary>
        /// <param name="entity">实体元数据</param>
        /// <returns>结果类代码</returns>
        public static string Generate(EntityMetadata entity)
        {
            var sb = new StringBuilder();
            
            // 文件头注释
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     此代码由代码生成器生成，请勿手动修改");
            sb.AppendLine($"//     生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();

            // Using 语句
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Orleans;");
            sb.AppendLine($"using {entity.Namespace};");
            sb.AppendLine();

            // 命名空间
            sb.AppendLine("namespace FakeMicro.Interfaces.Models.Results");
            sb.AppendLine("{");

            // 创建结果类
            GenerateCreateResult(sb, entity);
            sb.AppendLine();

            // 更新结果类
            GenerateUpdateResult(sb, entity);
            sb.AppendLine();

            // 删除结果类
            GenerateDeleteResult(sb, entity);
            sb.AppendLine();

            // 批量更新结果类
            GenerateBatchUpdateResult(sb, entity);
            sb.AppendLine();

            // 批量删除结果类
            GenerateBatchDeleteResult(sb, entity);
            sb.AppendLine();

            // 统计信息类
            GenerateStatistics(sb, entity);

            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 生成创建结果类
        /// </summary>
        private static void GenerateCreateResult(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 创建{entity.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class Create{entity.EntityName}Result : BaseResult");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine($"        public {entity.EntityName}Dto? Created{entity.EntityName} {{ get; set; }}");
            sb.AppendLine("        [Id(3)]");
            sb.AppendLine($"        public {entity.PrimaryKeyType}? {entity.PrimaryKeyProperty} {{ get; set; }}");
            sb.AppendLine();
            sb.AppendLine($"        public static Create{entity.EntityName}Result CreateSuccess({entity.EntityName}Dto entity, {entity.PrimaryKeyType} id)");
            sb.AppendLine($"            => new() {{ Success = true, Created{entity.EntityName} = entity, {entity.PrimaryKeyProperty} = id }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Create{entity.EntityName}Result CreateFailed(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage }};");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成更新结果类
        /// </summary>
        private static void GenerateUpdateResult(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 更新{entity.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class Update{entity.EntityName}Result : BaseResult");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine($"        public {entity.EntityName}Dto? Updated{entity.EntityName} {{ get; set; }}");
            sb.AppendLine();
            sb.AppendLine($"        public static Update{entity.EntityName}Result CreateSuccess({entity.EntityName}Dto entity)");
            sb.AppendLine($"            => new() {{ Success = true, Updated{entity.EntityName} = entity }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Update{entity.EntityName}Result CreateFailed(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage }};");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成删除结果类
        /// </summary>
        private static void GenerateDeleteResult(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 删除{entity.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class Delete{entity.EntityName}Result : BaseResult");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine("        public bool IsSoftDeleted { get; set; }");
            sb.AppendLine();
            sb.AppendLine($"        public static Delete{entity.EntityName}Result CreateSuccess(bool isSoftDeleted = false)");
            sb.AppendLine($"            => new() {{ Success = true, IsSoftDeleted = isSoftDeleted }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Delete{entity.EntityName}Result CreateFailed(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage }};");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成批量更新结果类
        /// </summary>
        private static void GenerateBatchUpdateResult(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 批量更新{entity.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class BatchUpdate{entity.EntityName}Result : BaseResult");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine("        public int SuccessCount { get; set; }");
            sb.AppendLine("        [Id(3)]");
            sb.AppendLine("        public int FailedCount { get; set; }");
            sb.AppendLine("        [Id(4)]");
            sb.AppendLine("        public List<string> Errors { get; set; } = new();");
            sb.AppendLine();
            sb.AppendLine($"        public static BatchUpdate{entity.EntityName}Result CreateSuccess(int successCount)");
            sb.AppendLine($"            => new() {{ Success = true, SuccessCount = successCount }};");
            sb.AppendLine();
            sb.AppendLine($"        public static BatchUpdate{entity.EntityName}Result CreateFailed(List<string> errors)");
            sb.AppendLine($"            => new() {{ Success = false, FailedCount = errors.Count, Errors = errors }};");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成批量删除结果类
        /// </summary>
        private static void GenerateBatchDeleteResult(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 批量删除{entity.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class BatchDelete{entity.EntityName}Result : BaseResult");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine("        public int SuccessCount { get; set; }");
            sb.AppendLine("        [Id(3)]");
            sb.AppendLine("        public int FailedCount { get; set; }");
            sb.AppendLine("        [Id(4)]");
            sb.AppendLine("        public List<string> Errors { get; set; } = new();");
            sb.AppendLine();
            sb.AppendLine($"        public static BatchDelete{entity.EntityName}Result CreateSuccess(int successCount)");
            sb.AppendLine($"            => new() {{ Success = true, SuccessCount = successCount }};");
            sb.AppendLine();
            sb.AppendLine($"        public static BatchDelete{entity.EntityName}Result CreateFailed(List<string> errors)");
            sb.AppendLine($"            => new() {{ Success = false, FailedCount = errors.Count, Errors = errors }};");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成统计信息类
        /// </summary>
        private static void GenerateStatistics(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {entity.EntityDescription}统计信息");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("[GenerateSerializer]");
            sb.AppendLine($"    public class {entity.EntityName}Statistics");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(0)]");
            sb.AppendLine("        public int TotalCount { get; set; }");
            sb.AppendLine("        [Id(1)]");
            sb.AppendLine("        public int ActiveCount { get; set; }");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine("        public int CreatedToday { get; set; }");
            sb.AppendLine("        [Id(3)]");
            sb.AppendLine("        public int CreatedThisWeek { get; set; }");
            sb.AppendLine("        [Id(4)]");
            sb.AppendLine("        public int CreatedThisMonth { get; set; }");
            sb.AppendLine("        [Id(5)]");
            sb.AppendLine("        public DateTime? LastCreated { get; set; }");
            sb.AppendLine("        [Id(6)]");
            sb.AppendLine("        public DateTime? LastUpdated { get; set; }");
            
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine();
                sb.AppendLine("        [Id(7)]");
                sb.AppendLine("        public int DeletedCount { get; set; }");
            }
            
            sb.AppendLine("    }");
        }
    }
}