using System;
using System.Collections.Generic;
using System.Text;
using FakeMicro.Utilities.CodeGenerator.Entities;
using FakeMicro.Utilities.CodeGenerator;

namespace FakeMicro.Utilities.CodeGenerator.Templates
{
    /// <summary>
    /// 结果类模板 - 专门用于生成CRUD操作的结果类
    /// </summary>
    public static class ResultTemplate
    {
        /// <summary>
        /// 生成实体相关的所有结果类
        /// </summary>
        /// <param name="entity">实体元数据</param>
        /// <returns>结果类代码</returns>
        public static string Generate(EntityMetadata entity)
        {
            var sb = new StringBuilder();
            
            // 文件头注释
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     此代码由代码生成器生成，请勿手动修改");
            sb.AppendLine($"//     生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();

            // Using 语句 - 增强错误处理支持
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using Orleans;");
            sb.AppendLine("using System.ComponentModel.DataAnnotations;");
            sb.AppendLine($"using {entity.Namespace};");
            sb.AppendLine();

            // 命名空间
            sb.AppendLine("namespace FakeMicro.Interfaces.Models.Results");
            sb.AppendLine("{");

            // 创建结果类
            GenerateCreateResult(sb, entity);
            sb.AppendLine();

            // 更新结果类
            GenerateUpdateResult(sb, entity);
            sb.AppendLine();

            // 删除结果类
            GenerateDeleteResult(sb, entity);
            sb.AppendLine();

            // 批量更新结果类
            GenerateBatchUpdateResult(sb, entity);
            sb.AppendLine();

            // 批量删除结果类
            GenerateBatchDeleteResult(sb, entity);
            sb.AppendLine();

            // 统计信息类
            GenerateStatistics(sb, entity);

            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 生成创建结果类 - 增强错误处理
        /// </summary>
        private static void GenerateCreateResult(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 创建{entity.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [GenerateSerializer]");
            sb.AppendLine($"    public class Create{entity.EntityName}Result : BaseResult");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(5)]");
            sb.AppendLine($"        public {entity.EntityName}Dto? Created{entity.EntityName} {{ get; set; }}");
            sb.AppendLine("        [Id(6)]");
            sb.AppendLine($"        public {entity.PrimaryKeyType}? {entity.PrimaryKeyProperty} {{ get; set; }}");
            sb.AppendLine();
            
            // 成功方法
            sb.AppendLine($"        public static Create{entity.EntityName}Result CreateSuccess({entity.EntityName}Dto entity, {entity.PrimaryKeyType} id)");
            sb.AppendLine($"            => new() {{ Success = true, Created{entity.EntityName} = entity, {entity.PrimaryKeyProperty} = id }};");
            sb.AppendLine();
            
            // 失败方法 - 分类错误处理
            sb.AppendLine($"        public static Create{entity.EntityName}Result Failed(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Create{entity.EntityName}Result NotFound(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage, ErrorCode = \"NOT_FOUND\" }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Create{entity.EntityName}Result Conflict(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage, ErrorCode = \"CONFLICT\" }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Create{entity.EntityName}Result InvalidReference(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage, ErrorCode = \"INVALID_REFERENCE\" }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Create{entity.EntityName}Result ValidationFailed(List<string> errors)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = string.Join(\"; \", errors), ErrorCode = \"VALIDATION_FAILED\" }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Create{entity.EntityName}Result InvalidGrainId()");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = \"无效的Grain ID\", ErrorCode = \"INVALID_GRAIN_ID\" }};");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成更新结果类 - 增强错误处理
        /// </summary>
        private static void GenerateUpdateResult(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 更新{entity.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [GenerateSerializer]");
            sb.AppendLine($"    public class Update{entity.EntityName}Result : BaseResult");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(5)]");
            sb.AppendLine($"        public {entity.EntityName}Dto? Updated{entity.EntityName} {{ get; set; }}");
            sb.AppendLine("        [Id(6)]");
            sb.AppendLine($"        public {entity.PrimaryKeyType}? {entity.PrimaryKeyProperty} {{ get; set; }}");
            sb.AppendLine();
            
            // 成功方法
            sb.AppendLine($"        public static Update{entity.EntityName}Result CreateSuccess({entity.EntityName}Dto entity, {entity.PrimaryKeyType} id)");
            sb.AppendLine($"            => new() {{ Success = true, Updated{entity.EntityName} = entity, {entity.PrimaryKeyProperty} = id }};");
            sb.AppendLine();
            
            // 失败方法 - 分类错误处理
            sb.AppendLine($"        public static Update{entity.EntityName}Result Failed(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Update{entity.EntityName}Result NotFound(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage, ErrorCode = \"NOT_FOUND\" }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Update{entity.EntityName}Result Conflict(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage, ErrorCode = \"CONFLICT\" }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Update{entity.EntityName}Result InvalidReference(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage, ErrorCode = \"INVALID_REFERENCE\" }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Update{entity.EntityName}Result ValidationFailed(List<string> errors)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = string.Join(\"; \", errors), ErrorCode = \"VALIDATION_FAILED\" }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Update{entity.EntityName}Result OptimisticConcurrency(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage, ErrorCode = \"OPTIMISTIC_CONCURRENCY\" }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Update{entity.EntityName}Result InvalidGrainId()");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = \"无效的Grain ID\", ErrorCode = \"INVALID_GRAIN_ID\" }};");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成删除结果类 - 增强错误处理
        /// </summary>
        private static void GenerateDeleteResult(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 删除{entity.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [GenerateSerializer]");
            sb.AppendLine($"    public class Delete{entity.EntityName}Result : BaseResult");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(5)]");
            sb.AppendLine("        public bool IsSoftDeleted { get; set; }");
            sb.AppendLine("        [Id(6)]");
            sb.AppendLine($"        public {entity.PrimaryKeyType}? {entity.PrimaryKeyProperty} {{ get; set; }}");
            sb.AppendLine();
            
            // 成功方法
            sb.AppendLine($"        public static Delete{entity.EntityName}Result CreateSuccess(bool isSoftDeleted = false, {entity.PrimaryKeyType}? id = null)");
            sb.AppendLine($"            => new() {{ Success = true, IsSoftDeleted = isSoftDeleted, {entity.PrimaryKeyProperty} = id }};");
            sb.AppendLine();
            
            // 失败方法 - 分类错误处理
            sb.AppendLine($"        public static Delete{entity.EntityName}Result Failed(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Delete{entity.EntityName}Result NotFound(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage, ErrorCode = \"NOT_FOUND\" }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Delete{entity.EntityName}Result CannotDeleteReferenced(string errorMessage)");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = errorMessage, ErrorCode = \"CANNOT_DELETE_REFERENCED\" }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Delete{entity.EntityName}Result InvalidGrainId()");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = \"无效的Grain ID\", ErrorCode = \"INVALID_GRAIN_ID\" }};");
            sb.AppendLine();
            sb.AppendLine($"        public static Delete{entity.EntityName}Result AlreadyDeleted()");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = \"项目已经被删除\", ErrorCode = \"ALREADY_DELETED\" }};");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成批量更新结果类 - 增强错误处理
        /// </summary>
        private static void GenerateBatchUpdateResult(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 批量更新{entity.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [GenerateSerializer]");
            sb.AppendLine($"    public class BatchUpdate{entity.EntityName}Result : BaseResult");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(5)]");
            sb.AppendLine("        public int SuccessCount { get; set; }");
            sb.AppendLine("        [Id(6)]");
            sb.AppendLine("        public int FailedCount { get; set; }");
            sb.AppendLine("        [Id(7)]");
            sb.AppendLine("        public int TotalCount { get; set; }");
            sb.AppendLine("        [Id(8)]");
            sb.AppendLine("        public List<string> Errors { get; set; } = new();");
            sb.AppendLine("        [Id(9)]");
            sb.AppendLine("        public List<string> ValidationErrors { get; set; } = new();");
            sb.AppendLine("        [Id(10)]");
            sb.AppendLine("        public List<string> ConflictErrors { get; set; } = new();");
            sb.AppendLine();
            
            // 计算成功率
            sb.AppendLine("        public double SuccessRate => TotalCount > 0 ? (double)SuccessCount / TotalCount * 100 : 0;");
            sb.AppendLine();
            
            // 成功方法
            sb.AppendLine($"        public static BatchUpdate{entity.EntityName}Result CreateSuccess(int successCount, int totalCount)");
            sb.AppendLine($"            => new() {{ Success = true, SuccessCount = successCount, TotalCount = totalCount, FailedCount = totalCount - successCount }};");
            sb.AppendLine();
            
            // 失败方法 - 分类错误处理
            sb.AppendLine($"        public static BatchUpdate{entity.EntityName}Result Failed(List<string> errors, List<string> validationErrors = null, List<string> conflictErrors = null)");
            sb.AppendLine($"            => new() {{ Success = false, FailedCount = errors?.Count ?? 0, TotalCount = (errors?.Count ?? 0) + (validationErrors?.Count ?? 0) + (conflictErrors?.Count ?? 0), Errors = errors ?? new(), ValidationErrors = validationErrors ?? new(), ConflictErrors = conflictErrors ?? new() }};");
            sb.AppendLine();
            sb.AppendLine($"        public static BatchUpdate{entity.EntityName}Result PartialSuccess(int successCount, int totalCount, List<string> errors)");
            sb.AppendLine($"            => new() {{ Success = true, SuccessCount = successCount, TotalCount = totalCount, FailedCount = errors?.Count ?? 0, Errors = errors ?? new() }};");
            sb.AppendLine();
            sb.AppendLine($"        public static BatchUpdate{entity.EntityName}Result InvalidGrainId()");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = \"无效的Grain ID\", ErrorCode = \"INVALID_GRAIN_ID\" }};");
            sb.AppendLine();
            sb.AppendLine($"        public static BatchUpdate{entity.EntityName}Result EmptyRequest()");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = \"批量更新请求为空\", ErrorCode = \"EMPTY_REQUEST\" }};");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成批量删除结果类 - 增强错误处理
        /// </summary>
        private static void GenerateBatchDeleteResult(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 批量删除{entity.EntityDescription}结果");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [GenerateSerializer]");
            sb.AppendLine($"    public class BatchDelete{entity.EntityName}Result : BaseResult");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(5)]");
            sb.AppendLine("        public int SuccessCount { get; set; }");
            sb.AppendLine("        [Id(6)]");
            sb.AppendLine("        public int FailedCount { get; set; }");
            sb.AppendLine("        [Id(7)]");
            sb.AppendLine("        public int TotalCount { get; set; }");
            sb.AppendLine("        [Id(8)]");
            sb.AppendLine("        public int SoftDeletedCount { get; set; }");
            sb.AppendLine("        [Id(9)]");
            sb.AppendLine("        public int HardDeletedCount { get; set; }");
            sb.AppendLine("        [Id(10)]");
            sb.AppendLine("        public List<string> Errors { get; set; } = new();");
            sb.AppendLine("        [Id(11)]");
            sb.AppendLine("        public List<string> CannotDeleteReferencedErrors { get; set; } = new();");
            sb.AppendLine("        [Id(12)]");
            sb.AppendLine("        public List<string> NotFoundErrors { get; set; } = new();");
            sb.AppendLine();
            
            // 计算成功率
            sb.AppendLine("        public double SuccessRate => TotalCount > 0 ? (double)SuccessCount / TotalCount * 100 : 0;");
            sb.AppendLine();
            
            // 成功方法
            sb.AppendLine($"        public static BatchDelete{entity.EntityName}Result CreateSuccess(int successCount, int totalCount, int softDeletedCount = 0, int hardDeletedCount = 0)");
            sb.AppendLine($"            => new() {{ Success = true, SuccessCount = successCount, TotalCount = totalCount, SoftDeletedCount = softDeletedCount, HardDeletedCount = hardDeletedCount, FailedCount = totalCount - successCount }};");
            sb.AppendLine();
            
            // 失败方法 - 分类错误处理
            sb.AppendLine($"        public static BatchDelete{entity.EntityName}Result Failed(List<string> errors, List<string> cannotDeleteErrors = null, List<string> notFoundErrors = null)");
            sb.AppendLine($"            => new() {{ Success = false, FailedCount = errors?.Count ?? 0, TotalCount = (errors?.Count ?? 0) + (cannotDeleteErrors?.Count ?? 0) + (notFoundErrors?.Count ?? 0), Errors = errors ?? new(), CannotDeleteReferencedErrors = cannotDeleteErrors ?? new(), NotFoundErrors = notFoundErrors ?? new() }};");
            sb.AppendLine();
            sb.AppendLine($"        public static BatchDelete{entity.EntityName}Result PartialSuccess(int successCount, int totalCount, int softDeletedCount, int hardDeletedCount, List<string> errors, List<string> cannotDeleteErrors = null, List<string> notFoundErrors = null)");
            sb.AppendLine($"            => new() {{ Success = true, SuccessCount = successCount, TotalCount = totalCount, SoftDeletedCount = softDeletedCount, HardDeletedCount = hardDeletedCount, FailedCount = (errors?.Count ?? 0) + (cannotDeleteErrors?.Count ?? 0) + (notFoundErrors?.Count ?? 0), Errors = errors ?? new(), CannotDeleteReferencedErrors = cannotDeleteErrors ?? new(), NotFoundErrors = notFoundErrors ?? new() }};");
            sb.AppendLine();
            sb.AppendLine($"        public static BatchDelete{entity.EntityName}Result InvalidGrainId()");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = \"无效的Grain ID\", ErrorCode = \"INVALID_GRAIN_ID\" }};");
            sb.AppendLine();
            sb.AppendLine($"        public static BatchDelete{entity.EntityName}Result EmptyRequest()");
            sb.AppendLine($"            => new() {{ Success = false, ErrorMessage = \"批量删除请求为空\", ErrorCode = \"EMPTY_REQUEST\" }};");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// 生成统计信息类
        /// </summary>
        private static void GenerateStatistics(StringBuilder sb, EntityMetadata entity)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {entity.EntityDescription}统计信息");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("     [GenerateSerializer]");
            sb.AppendLine($"    public class {entity.EntityName}Statistics");
            sb.AppendLine("    {");
            sb.AppendLine("        [Id(0)]");
            sb.AppendLine("        public int TotalCount { get; set; }");
            sb.AppendLine("        [Id(1)]");
            sb.AppendLine("        public int ActiveCount { get; set; }");
            sb.AppendLine("        [Id(2)]");
            sb.AppendLine("        public int CreatedToday { get; set; }");
            sb.AppendLine("        [Id(3)]");
            sb.AppendLine("        public int CreatedThisWeek { get; set; }");
            sb.AppendLine("        [Id(4)]");
            sb.AppendLine("        public int CreatedThisMonth { get; set; }");
            sb.AppendLine("        [Id(5)]");
            sb.AppendLine("        public DateTime? LastCreated { get; set; }");
            sb.AppendLine("        [Id(6)]");
            sb.AppendLine("        public DateTime? LastUpdated { get; set; }");
            
            if (entity.IsSoftDeletable)
            {
                sb.AppendLine();
                sb.AppendLine("        [Id(7)]");
                sb.AppendLine("        public int DeletedCount { get; set; }");
            }
            
            sb.AppendLine("    }");
        }
    }
}