// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-11-20 22:08:21
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using AutoMapper;
using Orleans;
using Orleans.Runtime;
using SqlSugar;
using FakeMicro.Entities;
using FakeMicro.Entities.Grains;
using FakeMicro.Interfaces;
using FakeMicro.Interfaces.Models;
using FakeMicro.Interfaces.Models.Results;
using FakeMicro.DatabaseAccess;
using FakeMicro.DatabaseAccess.Interfaces;
using FakeMicro.Utilities.CodeGenerator;
using CodeGeneratorValidationResult = FakeMicro.Utilities.CodeGenerator;
using InterfacesValidationResult = FakeMicro.Interfaces.Models.ValidationResult;

namespace FakeMicro.Entities.Grains
{
    /// <summary>
    /// FakeStudentGrain实现
    /// </summary>
    public class FakeStudentGrain :Grain,IFakeStudentGrain
    {
        private readonly ILogger<FakeStudentGrain> _logger;
        private readonly IMapper _mapper;
        private readonly IFakeStudentRepository _repository;

        public FakeStudentGrain(
            ILogger<FakeStudentGrain> logger,
            IMapper mapper,
            IFakeStudentRepository repository) // 通过接口注入
        {
            _logger = logger;
            _mapper = mapper;
            _repository = repository; // 使用注入的仓储
        }

        /// <summary>
        /// 获取FakeStudent
        /// </summary>
        public async Task<FakeStudentDto?> GetAsync(CancellationToken cancellationToken = default)
        {
            try
            {
                var grainIdStr = this.GetPrimaryKeyString();
                if (!long.TryParse(grainIdStr, out long grainId))
                {
                    _logger.LogWarning("无效的Grain ID: {GrainId}", grainIdStr);
                    return null;
                }

                var entity = await _repository.GetByIdAsync(grainId, cancellationToken);
                if (entity == null)
                {
                    _logger.LogInformation("FakeStudent不存在: {Id}", grainId);
                    return null;
                }
                return _mapper.Map<FakeStudentDto>(entity);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "获取FakeStudent时发生错误: {Id}", this.GetPrimaryKeyString());
                throw; // 对于查询操作，抛出异常更合适
            }
        }
        
        /// <summary>
        /// 通过Grain ID获取FakeStudent实体
        /// </summary>
        public async Task<FakeStudent?> GetByGrainIdAsync(CancellationToken cancellationToken = default)
        {
            try
            {
                var grainIdStr = this.GetPrimaryKeyString();
                if (!long.TryParse(grainIdStr, out long grainId))
                {
                    _logger.LogWarning("无效的Grain ID: {GrainId}", grainIdStr);
                    return null;
                }

                var entity = await _repository.GetByIdAsync(grainId, cancellationToken);
                if (entity == null)
                {
                    _logger.LogInformation("FakeStudent实体不存在: {Id}", grainId);
                    return null;
                }
                return entity;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "通过Grain ID获取FakeStudent实体时发生错误: {Id}", this.GetPrimaryKeyString());
                throw;
            }
        }

        /// <summary>
        /// 创建FakeStudent
        /// </summary>
        public async Task<CreateFakeStudentResult> CreateAsync(CreateFakeStudentRequest request, CancellationToken cancellationToken = default)
        {
            try
            {
                var grainIdStr = this.GetPrimaryKeyString();
                if (!long.TryParse(grainIdStr, out long grainId))
                {
                    _logger.LogWarning("无效的Grain ID: {GrainId}", grainIdStr);
                    return CreateFakeStudentResult.InvalidGrainId();
                }

                var entity = _mapper.Map<FakeStudent>(request);

                // 设置默认值
                entity.Id = grainId;
                entity.CreatedAt = DateTime.UtcNow;
                entity.UpdatedAt = DateTime.UtcNow;

                // 修复CS0815错误，AddAsync可能返回void
                await _repository.AddAsync(entity, cancellationToken);
                var result = _mapper.Map<FakeStudentDto>(entity);

                _logger.LogInformation("FakeStudent创建成功: {Id}", entity.Id);
                return CreateFakeStudentResult.CreateSuccess(result, entity.Id);
            }
            catch (SqlSugarException ex)
            {
                var msg = ex.InnerException?.Message ?? ex.Message;
                if (msg.Contains("FK_"))
                {
                    _logger.LogWarning(ex, "创建FakeStudent时发生外键约束错误");
                    return CreateFakeStudentResult.InvalidReference("引用的数据不存在");
                }
                _logger.LogWarning(ex, "创建FakeStudent时发生唯一键冲突或数据库错误");
                return CreateFakeStudentResult.Conflict("该FakeStudent已存在");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "创建FakeStudent时发生系统错误");
                return CreateFakeStudentResult.Failed("创建失败，请稍后重试");
            }
        }

        /// <summary>
        /// 更新FakeStudent
        /// </summary>
        public async Task<UpdateFakeStudentResult> UpdateAsync(UpdateFakeStudentRequest request, CancellationToken cancellationToken = default)
        {
            try
            {
                var grainIdStr = this.GetPrimaryKeyString();
                if (!long.TryParse(grainIdStr, out long grainId))
                {
                    _logger.LogWarning("无效的Grain ID: {GrainId}", grainIdStr);
                    return UpdateFakeStudentResult.InvalidGrainId();
                }

                var existingEntity = await _repository.GetByIdAsync(grainId, cancellationToken);
                if (existingEntity == null)
                {
                    _logger.LogWarning("FakeStudent不存在: {Id}", grainId);
                    return UpdateFakeStudentResult.NotFound("FakeStudent不存在");
                }

                // 更新字段
                _mapper.Map(request, existingEntity);
                existingEntity.UpdatedAt = DateTime.UtcNow;

                await _repository.UpdateAsync(existingEntity, cancellationToken);
                var result = _mapper.Map<FakeStudentDto>(existingEntity);

                _logger.LogInformation("FakeStudent更新成功: {Id}", existingEntity.Id);
                return UpdateFakeStudentResult.CreateSuccess(result, existingEntity.Id);
            }
            catch (SqlSugarException ex)
            {
                _logger.LogWarning(ex, "更新FakeStudent时发生并发冲突或数据库错误");
                return UpdateFakeStudentResult.OptimisticConcurrency("数据已被其他操作修改，请刷新后重试");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "更新FakeStudent时发生系统错误: {Id}", this.GetPrimaryKeyString());
                return UpdateFakeStudentResult.Failed("更新失败，请稍后重试");
            }
        }

        /// <summary>
        /// 删除FakeStudent
        /// </summary>
        public async Task<DeleteFakeStudentResult> DeleteAsync(CancellationToken cancellationToken = default)
        {
            try
            {
                var grainIdStr = this.GetPrimaryKeyString();
                if (!long.TryParse(grainIdStr, out long grainId))
                {
                    _logger.LogWarning("无效的Grain ID: {GrainId}", grainIdStr);
                    return DeleteFakeStudentResult.InvalidGrainId();
                }

                var existingEntity = await _repository.GetByIdAsync(grainId, cancellationToken);
                if (existingEntity == null)
                {
                    _logger.LogWarning("FakeStudent不存在: {Id}", grainId);
                    return DeleteFakeStudentResult.NotFound("FakeStudent不存在");
                }

                await _repository.DeleteAsync(existingEntity, cancellationToken);

                _logger.LogInformation("FakeStudent删除成功: {Id}", grainId);
                return DeleteFakeStudentResult.CreateSuccess();
            }
            catch (SqlSugarException ex)
            {
                var msg = ex.InnerException?.Message ?? ex.Message;
                if (msg.Contains("FK_"))
                {
                    _logger.LogWarning(ex, "删除FakeStudent时发生外键约束错误");
                    return DeleteFakeStudentResult.CannotDeleteReferenced("该FakeStudent被其他数据引用，无法删除");
                }
                throw;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "删除FakeStudent时发生系统错误: {Id}", this.GetPrimaryKeyString());
                return DeleteFakeStudentResult.Failed("删除失败，请稍后重试");
            }
        }

        /// <summary>
        /// 获取FakeStudent列表
        /// </summary>
        public async Task<List<FakeStudentDto>> GetListAsync(int page = 1, int pageSize = 20, CancellationToken cancellationToken = default)
        {
            try
            {
                var pagedResult = await _repository.GetPagedAsync(page, pageSize, x => x.CreatedAt, true, cancellationToken);
                return _mapper.Map<List<FakeStudentDto>>(pagedResult.Items);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "获取FakeStudent列表时发生系统错误");
                throw new InvalidOperationException("获取FakeStudent列表失败，请稍后重试");
            }
        }

        /// <summary>
        /// 获取FakeStudent总数
        /// </summary>
        public async Task<int> GetCountAsync(CancellationToken cancellationToken = default)
        {
            try
            {
                return await _repository.CountAsync(null, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "获取FakeStudent总数时发生系统错误");
                throw new InvalidOperationException("获取FakeStudent总数失败，请稍后重试");
            }
        }

        /// <summary>
        /// 搜索FakeStudent
        /// </summary>
        public async Task<List<FakeStudentDto>> SearchAsync(string keyword, int page = 1, int pageSize = 20, CancellationToken cancellationToken = default)
        {
            try
            {
                // 搜索逻辑 - 根据字符串属性搜索
                Expression<Func<FakeStudent, bool>>? predicate = null;
                if (!string.IsNullOrEmpty(keyword))
                {
                    predicate = x => x.ClassName.Contains(keyword) || x.ClassCode.Contains(keyword) || x.Major.Contains(keyword) || x.Description.Contains(keyword);
                }

                var pagedResult = await _repository.GetPagedByConditionAsync(predicate, page, pageSize, x => x.CreatedAt, true, cancellationToken);
                return _mapper.Map<List<FakeStudentDto>>(pagedResult.Items);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "搜索FakeStudent时发生系统错误");
                throw new InvalidOperationException("搜索FakeStudent失败，请稍后重试");
            }
        }

        /// <summary>
        /// 批量删除FakeStudent
        /// </summary>
        public async Task<BatchDeleteFakeStudentResult> BatchDeleteAsync(List<long> ids, CancellationToken cancellationToken = default)
        {
            try
            {
                if (ids == null || !ids.Any())
                {
                    return BatchDeleteFakeStudentResult.EmptyRequest();
                }

                var entities = await _repository.GetByConditionAsync(x => ids.Contains(x.Id), cancellationToken);
                if (!entities.Any())
                {
                    return BatchDeleteFakeStudentResult.Failed(new List<string> { "未找到要删除的FakeStudent" });
                }

                // 使用获取到的实体列表进行删除
                await _repository.DeleteRangeAsync(entities, cancellationToken);

                _logger.LogInformation("批量删除FakeStudent成功，删除数量: {Count}", entities.Count());
                return BatchDeleteFakeStudentResult.CreateSuccess(entities.Count(), entities.Count());
            }
            catch (SqlSugarException ex)
            {
                var msg = ex.InnerException?.Message ?? ex.Message;
                if (msg.Contains("FK_"))
                {
                    _logger.LogWarning(ex, "批量删除FakeStudent时发生外键约束错误");
                    return BatchDeleteFakeStudentResult.Failed(new List<string> { "部分FakeStudent被其他数据引用，无法删除" });
                }
                throw;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "批量删除FakeStudent时发生系统错误");
                return BatchDeleteFakeStudentResult.Failed(new List<string> { "批量删除失败，请稍后重试" });
            }
        }

        /// <summary>
        /// 验证FakeStudent数据
        /// </summary>
        public async Task<InterfacesValidationResult> ValidateAsync(FakeStudentDto data, CancellationToken cancellationToken = default)
        {
            var errors = new List<string>();

            if (string.IsNullOrWhiteSpace(data.ClassName))
                errors.Add("班级名称不能为空");
            if (data.ClassName?.Length > 100)
                errors.Add("班级名称长度不能超过100个字符");
            if (string.IsNullOrWhiteSpace(data.ClassCode))
                errors.Add("班级编号不能为空");
            if (data.ClassCode?.Length > 20)
                errors.Add("班级编号长度不能超过20个字符");
            if (string.IsNullOrWhiteSpace(data.Major))
                errors.Add("专业不能为空");
            if (data.Major?.Length > 100)
                errors.Add("专业长度不能超过100个字符");
            if (data.Description?.Length > 500)
                errors.Add("班级描述长度不能超过500个字符");

            if (errors.Any())
            {
                return InterfacesValidationResult.CreateFailed(errors);
            }

            return InterfacesValidationResult.CreateSuccess();
        }
    }
}
