// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-11-21 13:10:31
// </auto-generated>

using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Extensions.Logging;
using Orleans;
using Orleans.Runtime;
using System;
using SqlSugar;
using FakeMicro.DatabaseAccess;
using FakeMicro.Interfaces;
using FakeMicro.Interfaces.Models;
using FakeMicro.Interfaces.Models.Results;
using FakeMicro.Utilities.CodeGenerator;
using FakeMicro.DatabaseAccess.Interfaces;
using AutoMapper;
namespace FakeMicro.Entities.Grains
{
    /// <summary>
    /// FakeNewsGrain实现
    /// </summary>
    public class FakeNewsGrain :Grain,IFakeNewsGrain
    {
        private readonly ILogger<FakeNewsGrain> _logger;
        private readonly IMapper _mapper;
        private readonly IFakeNewsRepository _repository;

        public FakeNewsGrain(
            ILogger<FakeNewsGrain> logger,
            IMapper mapper,
            IFakeNewsRepository repository) // 通过接口注入
        {
            _logger = logger;
            //_mapper = mapper;
            _repository = repository; // 使用注入的仓储
        }

        /// <summary>
        /// 获取FakeNews
        /// </summary>
        public async Task<FakeNewsDto?> GetAsync(CancellationToken cancellationToken = default)
        {
            try
            {
                long grainId;
                var idString = this.GetPrimaryKeyString();
                if (string.IsNullOrEmpty(idString) || !long.TryParse(idString, out grainId))
                {
                    _logger.LogWarning("无效的Grain ID: {GrainId}", idString);
                    return null;
                }

                var entity = await _repository.GetByIdAsync(grainId, cancellationToken);
                if (entity == null)
                {
                    _logger.LogInformation("FakeNews不存在: {Id}", grainId);
                    return null;
                }
                return _mapper.Map<FakeNewsDto>(entity);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "获取FakeNews时发生错误: {Id}", this.GetPrimaryKeyString());
                throw; // 对于查询操作，抛出异常更合适
            }
        }

        /// <summary>
        /// 创建FakeNews
        /// </summary>
        public async Task<CreateFakeNewsResult> CreateAsync(CreateFakeNewsRequest request, CancellationToken cancellationToken = default)
        {
            try
            {
                long grainId;
                var idString = this.GetPrimaryKeyString();
                if (string.IsNullOrEmpty(idString) || !long.TryParse(idString, out grainId))
                {
                    _logger.LogWarning("无效的Grain ID: {GrainId}", idString);
                    return CreateFakeNewsResult.InvalidGrainId();
                }

                var entity = _mapper.Map<FakeNews>(request);

                // 设置默认值
                entity.Id = grainId;
                entity.CreatedAt = DateTime.UtcNow;
                entity.UpdatedAt = DateTime.UtcNow;

                await _repository.AddAsync(entity, cancellationToken);
                var result = _mapper.Map<FakeNewsDto>(entity);

                _logger.LogInformation("FakeNews创建成功: {Id}", entity.Id);
                return CreateFakeNewsResult.CreateSuccess(result,entity.Id);
            }
            catch (SqlSugarException ex) // 唯一键冲突
            {
               var msg = ex.InnerException?.Message ?? ex.Message; 
              if(msg.Contains("FK_"))
{ 
                _logger.LogError(ex, "创建FakeNews创建FakeStudent时发生外键约束错误");
               return CreateFakeNewsResult.InvalidReference("引用的数据不存在");
}
             _logger.LogWarning(ex, "FakeNews时发生唯一键冲突或数据库错误");
              return CreateFakeNewsResult.Conflict("FakeNews已存在");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "创建FakeNews时发生系统错误");
                return CreateFakeNewsResult.Failed("创建失败，请稍后重试");
            }
        }

        /// <summary>
        /// 更新FakeNews
        /// </summary>
        public async Task<UpdateFakeNewsResult> UpdateAsync(UpdateFakeNewsRequest request, CancellationToken cancellationToken = default)
        {
            try
            {
                long grainId;
                var idString = this.GetPrimaryKeyString();
                if (string.IsNullOrEmpty(idString) || !long.TryParse(idString, out grainId))
                {
                    _logger.LogWarning("无效的Grain ID: {GrainId}", idString);
                    return UpdateFakeNewsResult.InvalidGrainId();
                }

                var existingEntity = await _repository.GetByIdAsync(grainId, cancellationToken);
                if (existingEntity == null)
                {
                    _logger.LogWarning("FakeNews不存在: {Id}", grainId);
                    return UpdateFakeNewsResult.NotFound("FakeNews不存在");
                }

                // 更新字段
                _mapper.Map(request, existingEntity);
                existingEntity.UpdatedAt = DateTime.UtcNow;

                await _repository.UpdateAsync(existingEntity, cancellationToken);
                var result = _mapper.Map<FakeNewsDto>(existingEntity);

                _logger.LogInformation("FakeNews更新成功: {Id}", existingEntity.Id);
                return UpdateFakeNewsResult.CreateSuccess(result, existingEntity.Id);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "更新FakeNews时发生系统错误: {Id}", this.GetPrimaryKeyString());
                return UpdateFakeNewsResult.Failed("更新失败，请稍后重试");
            }
        }

        /// <summary>
        /// 删除FakeNews
        /// </summary>
        public async Task<DeleteFakeNewsResult> DeleteAsync(CancellationToken cancellationToken = default)
        {
            try
            {
                long grainId;
                var idString = this.GetPrimaryKeyString();
                if (string.IsNullOrEmpty(idString) || !long.TryParse(idString, out grainId))
                {
                    _logger.LogWarning("无效的Grain ID: {GrainId}", idString);
                    return DeleteFakeNewsResult.InvalidGrainId();
                }

                var existingEntity = await _repository.GetByIdAsync(grainId, cancellationToken);
                if (existingEntity == null)
                {
                    _logger.LogWarning("FakeNews不存在: {Id}", grainId);
                    return DeleteFakeNewsResult.NotFound("FakeNews不存在");
                }

                await _repository.DeleteAsync(existingEntity, cancellationToken); // 使用实体对象删除，避免类型错误

                _logger.LogInformation("FakeNews删除成功: {Id}", grainId);
                return DeleteFakeNewsResult.CreateSuccess();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "删除FakeNews时发生系统错误: {Id}", this.GetPrimaryKeyString());
                return DeleteFakeNewsResult.Failed("删除失败，请稍后重试");
            }
        }

        /// <summary>
        /// 获取FakeNews列表
        /// </summary>
        public async Task<List<FakeNewsDto>> GetListAsync(int page = 1, int pageSize = 20, CancellationToken cancellationToken = default)
        {
            try
            {
                var query = _repository.GetQueryable();

                var entities = await query
                    .OrderByDescending(x => x.CreatedAt)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize)
                    .ToListAsync(cancellationToken);

                return _mapper.Map<List<FakeNewsDto>>(entities);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "获取FakeNews列表时发生系统错误");
                throw new InvalidOperationException("获取FakeNews列表失败，请稍后重试");
            }
        }

        /// <summary>
        /// 获取FakeNews总数
        /// </summary>
        public async Task<int> GetCountAsync(CancellationToken cancellationToken = default)
        {
            try
            {
                var query = _repository.GetQueryable();

                return await query.CountAsync(cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "获取FakeNews总数时发生系统错误");
                throw new InvalidOperationException($"获取FakeNews总数失败，请稍后重试");
            }
        }

        /// <summary>
        /// 搜索FakeNews
        /// </summary>
        public async Task<List<FakeNewsDto>> SearchAsync(string keyword, int page = 1, int pageSize = 20, CancellationToken cancellationToken = default)
        {
            try
            {
                var query = _repository.GetQueryable();

                // 搜索逻辑 - 根据字符串属性搜索
                if (!string.IsNullOrEmpty(keyword))
                {
                    query = query.Where(x => x.title.Contains(keyword) || x.author.Contains(keyword) || x.content.Contains(keyword) || x.Description.Contains(keyword));
                }

                var entities = await query
                    .OrderByDescending(x => x.CreatedAt)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize)
                    .ToListAsync(cancellationToken);

                return _mapper.Map<List<FakeNewsDto>>(entities);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "搜索FakeNews时发生系统错误");
                throw new InvalidOperationException($"搜索FakeNews失败，请稍后重试");
            }
        }

        /// <summary>
        /// 批量删除FakeNews
        /// </summary>
        public async Task<BatchDeleteFakeNewsResult> BatchDeleteAsync(List<long> ids, CancellationToken cancellationToken = default)
        {
            try
            {
                if (ids == null || !ids.Any())
                {
                    return BatchDeleteFakeNewsResult.Failed("批量删除ID列表不能为空");
                }

                var query = _repository.GetQueryable().Where(x => ids.Contains(x.Id));

                var entities = await query.ToListAsync(cancellationToken);
                if (!entities.Any())
                {
                    return BatchDeleteFakeNewsResult.NotFound("未找到要删除的FakeNews");
                }

                await _repository.DeleteRangeAsync(entities, cancellationToken); // 使用获取到的实体列表进行删除，避免类型错误

                _logger.LogInformation("批量删除FakeNews成功，删除数量: {Count}", entities.Count);
                return BatchDeleteFakeNewsResult.Success(entities.Count);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "批量删除FakeNews时发生系统错误");
                return BatchDeleteFakeNewsResult.Failure("批量删除失败，请稍后重试");
            }
        }

        /// <summary>
        /// 验证FakeNews数据
        /// </summary>
        public async Task<ValidationResult> ValidateAsync(FakeNewsDto data, CancellationToken cancellationToken = default)
        {
            var errors = new List<string>();

            if (string.IsNullOrWhiteSpace(data.title))
                errors.Add("标题不能为空");
            if (data.title?.Length > 200)
                errors.Add("标题长度不能超过200个字符");
            if (string.IsNullOrWhiteSpace(data.author))
                errors.Add("作者不能为空");
            if (data.author?.Length > 100)
                errors.Add("作者长度不能超过100个字符");
            if (string.IsNullOrWhiteSpace(data.content))
                errors.Add("专业不能为空");
            if (data.content?.Length > 10000)
                errors.Add("专业长度不能超过10000个字符");
            if (data.Description?.Length > 500)
                errors.Add("描述长度不能超过500个字符");

            if (errors.Any())
            {
                return ValidationResult.CreateFailed(errors);
            }

            return ValidationResult.CreateSuccess();
        }
    }
}
