// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-11-20 22:08:21
// </auto-generated>

using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using Orleans;  // Orleans Grain 接口支持
using FakeMicro.Entities;
using FakeMicro.Interfaces.Models;
using FakeMicro.Interfaces.Models.Results;
using FakeMicro.Utilities.CodeGenerator;
using CodeGeneratorValidationResult = FakeMicro.Utilities.CodeGenerator.ValidationResult;
using InterfacesValidationResult = FakeMicro.Interfaces.Models.ValidationResult;

namespace FakeMicro.Interfaces
{
    /// <summary>
    /// FakeStudentGrain接口
    /// </summary>
    public interface IFakeStudentGrain : IGrainWithStringKey
    {
        /// <summary>
        /// 获取FakeStudent
        /// </summary>
        Task<FakeStudentDto?> GetAsync(CancellationToken cancellationToken = default);

        /// <summary>
        /// 创建FakeStudent
        /// </summary>
        Task<CreateFakeStudentResult> CreateAsync(CreateFakeStudentRequest request, CancellationToken cancellationToken = default);

        /// <summary>
        /// 更新FakeStudent
        /// </summary>
        Task<UpdateFakeStudentResult> UpdateAsync(UpdateFakeStudentRequest request, CancellationToken cancellationToken = default);

        /// <summary>
        /// 删除FakeStudent
        /// </summary>
        Task<DeleteFakeStudentResult> DeleteAsync(CancellationToken cancellationToken = default);

        /// <summary>
        /// 获取FakeStudent列表
        /// </summary>
        Task<List<FakeStudentDto>> GetListAsync(int page = 1, int pageSize = 20, CancellationToken cancellationToken = default);

        /// <summary>
        /// 获取FakeStudent总数
        /// </summary>
        Task<int> GetCountAsync(CancellationToken cancellationToken = default);

        /// <summary>
        /// 搜索FakeStudent
        /// </summary>
        Task<List<FakeStudentDto>> SearchAsync(string keyword, int page = 1, int pageSize = 20, CancellationToken cancellationToken = default);

        /// <summary>
        /// 批量删除FakeStudent
        /// </summary>
        Task<BatchDeleteFakeStudentResult> BatchDeleteAsync(List<long> ids, CancellationToken cancellationToken = default);

        /// <summary>
        /// 验证FakeStudent数据
        /// </summary>
        Task<InterfacesValidationResult> ValidateAsync(FakeStudentDto data, CancellationToken cancellationToken = default);
    }
}
