//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由代码生成器生成。
//     运行时版本: 9.0.11
//     生成时间: 2025-11-20 22:08:21
//     </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text.RegularExpressions;
using Orleans.Concurrency;
using Orleans;

namespace FakeMicro.Interfaces.Models.Requests
{
    /// <summary>
    /// 创建FakeStudent请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class CreateFakeStudentRequest
    {
        /// <summary>
        /// 班级名称
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [MaxLength(100, ErrorMessage = "{0}长度不能超过100个字符")]
        [Id(0)]
        public string? ClassName { get; set; }

        /// <summary>
        /// 班级编号
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [MaxLength(20, ErrorMessage = "{0}长度不能超过20个字符")]
        [Id(1)]
        public string? ClassCode { get; set; }

        /// <summary>
        /// 年级
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [Id(2)]
        public int Grade { get; set; }

        /// <summary>
        /// 专业
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [MaxLength(100, ErrorMessage = "{0}长度不能超过100个字符")]
        [Id(3)]
        public string? Major { get; set; }

        /// <summary>
        /// 班主任ID
        /// </summary>
        [Id(4)]
        public long? TeacherId { get; set; }

        /// <summary>
        /// 最大学生数
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [Id(5)]
        public int MaxStudents { get; set; }

        /// <summary>
        /// 当前学生数
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [Id(6)]
        public int CurrentStudents { get; set; }

        /// <summary>
        /// 班级状态(1:正常,2:停课,3:毕业)
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [Id(7)]
        public int Status { get; set; }

        /// <summary>
        /// 班级描述
        /// </summary>
        [MaxLength(500, ErrorMessage = "{0}长度不能超过500个字符")]
        [Id(8)]
        public string? Description { get; set; }

        /// <summary>
        /// 手动验证请求数据
        /// </summary>
        /// <returns>验证结果</returns>
        public (bool IsValid, List<string> Errors) Validate()
        {
            var errors = new List<string>();

            if (string.IsNullOrWhiteSpace(ClassName))
                errors.Add("ClassName是必需的");

            if (ClassName?.Length > 100)
                errors.Add("ClassName长度不能超过100个字符");

            if (string.IsNullOrWhiteSpace(ClassCode))
                errors.Add("ClassCode是必需的");

            if (ClassCode?.Length > 20)
                errors.Add("ClassCode长度不能超过20个字符");

            if (Grade == null)
                errors.Add("Grade是必需的");

            if (string.IsNullOrWhiteSpace(Major))
                errors.Add("Major是必需的");

            if (Major?.Length > 100)
                errors.Add("Major长度不能超过100个字符");

            if (MaxStudents == null)
                errors.Add("MaxStudents是必需的");

            if (CurrentStudents == null)
                errors.Add("CurrentStudents是必需的");

            if (Status == null)
                errors.Add("Status是必需的");

            if (Description?.Length > 500)
                errors.Add("Description长度不能超过500个字符");

            return (errors.Count == 0, errors);
        }
    }

    /// <summary>
    /// 更新FakeStudent请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class UpdateFakeStudentRequest
    {
        /// <summary>
        /// 班级唯一标识
        /// </summary>
        [Id(0)]
        public long Id { get; set; }

        /// <summary>
        /// 班级名称
        /// </summary>
        [Id(1)]
        public string? ClassName { get; set; }

        /// <summary>
        /// 班级编号
        /// </summary>
        [Id(2)]
        public string? ClassCode { get; set; }

        /// <summary>
        /// 年级
        /// </summary>
        [Id(3)]
        public int? Grade { get; set; }

        /// <summary>
        /// 专业
        /// </summary>
        [Id(4)]
        public string? Major { get; set; }

        /// <summary>
        /// 班主任ID
        /// </summary>
        [Id(5)]
        public long? TeacherId { get; set; }

        /// <summary>
        /// 最大学生数
        /// </summary>
        [Id(6)]
        public int? MaxStudents { get; set; }

        /// <summary>
        /// 当前学生数
        /// </summary>
        [Id(7)]
        public int? CurrentStudents { get; set; }

        /// <summary>
        /// 班级状态(1:正常,2:停课,3:毕业)
        /// </summary>
        [Id(8)]
        public int? Status { get; set; }

        /// <summary>
        /// 班级描述
        /// </summary>
        [Id(9)]
        public string? Description { get; set; }

    }

    /// <summary>
    /// 批量操作FakeStudent请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class BatchFakeStudentRequest
    {
        /// <summary>
        /// 班级唯一标识列表
        /// </summary>
        [Id(0)]
        public List<long> Ids { get; set; } = new();

        /// <summary>
        /// 操作类型
        /// </summary>
        [Id(1)]
        public BatchOperationType OperationType { get; set; }

    }

    /// <summary>
    /// 批量操作类型
    /// </summary>
    public enum BatchOperationType
    {
        Delete,
        SoftDelete,
        Restore,
        Archive
    }

    /// <summary>
    /// 查询FakeStudent请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class QueryFakeStudentRequest
    {
        /// <summary>
        /// 班级唯一标识
        /// </summary>
        [Id(0)]
        public long Id { get; set; }

        /// <summary>
        /// 是否包含软删除的记录
        /// </summary>
        [Id(1)]
        public bool IncludeDeleted { get; set; } = false;

    }

    /// <summary>
    /// 搜索FakeStudent请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class SearchFakeStudentRequest
    {
        /// <summary>
        /// 搜索关键词
        /// </summary>
        [Id(0)]
        public string Keyword { get; set; } = string.Empty;

        /// <summary>
        /// 页码（从1开始）
        /// </summary>
        [Id(1)]
        public int Page { get; set; } = 1;

        /// <summary>
        /// 每页大小
        /// </summary>
        [Id(2)]
        public int PageSize { get; set; } = 20;

        /// <summary>
        /// 排序字段
        /// </summary>
        [Id(3)]
        public string SortBy { get; set; } = "CreatedAt";

        /// <summary>
        /// 排序方向
        /// </summary>
        [Id(4)]
        public SortDirection SortDirection { get; set; } = SortDirection.Descending;

        /// <summary>
        /// 过滤条件
        /// </summary>
        [Id(5)]
        public Dictionary<string, object> Filters { get; set; } = new();

    }

    /// <summary>
    /// 排序方向
    /// </summary>
}
