//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由代码生成器生成。
//     运行时版本: 9.0.11
//     生成时间: 2025-11-22 21:03:51
//     </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text.RegularExpressions;
using Orleans.Concurrency;
using Orleans;
using FakeMicro.Entities.Enums;

namespace FakeMicro.Interfaces.Models.Requests
{
    /// <summary>
    /// 创建FakeNews请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class CreateFakeNewsRequest
    {
        /// <summary>
        /// 标题
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [MaxLength(200, ErrorMessage = "{0}长度不能超过200个字符")]
        [Id(0)]
        public string? title { get; set; }

        /// <summary>
        /// 作者
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [MaxLength(100, ErrorMessage = "{0}长度不能超过100个字符")]
        [Id(1)]
        public string? author { get; set; }

        /// <summary>
        /// 年级
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [Id(2)]
        public int order { get; set; }

        /// <summary>
        /// 专业
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [MaxLength(10000, ErrorMessage = "{0}长度不能超过10000个字符")]
        [Id(3)]
        public string? content { get; set; }

        /// <summary>
        /// 状态(1:正常,2:停课,3:毕业)
        /// </summary>
        [Required(ErrorMessage = "{0}是必需的")]
        [Id(4)]
        public int Status { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        [MaxLength(500, ErrorMessage = "{0}长度不能超过500个字符")]
        [Id(5)]
        public string? Description { get; set; }

        /// <summary>
        /// 手动验证请求数据
        /// </summary>
        /// <returns>验证结果</returns>
        public (bool IsValid, List<string> Errors) Validate()
        {
            var errors = new List<string>();

            if (string.IsNullOrWhiteSpace(title))
                errors.Add("title是必需的");

            if (title?.Length > 200)
                errors.Add("title长度不能超过200个字符");

            if (string.IsNullOrWhiteSpace(author))
                errors.Add("author是必需的");

            if (author?.Length > 100)
                errors.Add("author长度不能超过100个字符");

            //if (order == null)
            //    errors.Add("order是必需的");

            if (string.IsNullOrWhiteSpace(content))
                errors.Add("content是必需的");

            if (content?.Length > 10000)
                errors.Add("content长度不能超过10000个字符");

            //if (Status == null)
            //    errors.Add("Status是必需的");

            if (Description?.Length > 500)
                errors.Add("Description长度不能超过500个字符");

            return (errors.Count == 0, errors);
        }
    }

    /// <summary>
    /// 更新FakeNews请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class UpdateFakeNewsRequest
    {
        /// <summary>
        /// 新闻Id
        /// </summary>
        [Id(0)]
        public long Id { get; set; }

        /// <summary>
        /// 标题
        /// </summary>
        [Id(1)]
        public string? title { get; set; }

        /// <summary>
        /// 作者
        /// </summary>
        [Id(2)]
        public string? author { get; set; }

        /// <summary>
        /// 年级
        /// </summary>
        [Id(3)]
        public int? order { get; set; }

        /// <summary>
        /// 专业
        /// </summary>
        [Id(4)]
        public string? content { get; set; }

        /// <summary>
        /// 状态(1:正常,2:停课,3:毕业)
        /// </summary>
        [Id(5)]
        public int? Status { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        [Id(6)]
        public string? Description { get; set; }

    }

    /// <summary>
    /// 批量操作FakeNews请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class BatchFakeNewsRequest
    {
        /// <summary>
        /// 新闻Id列表
        /// </summary>
        [Id(0)]
        public List<long> Ids { get; set; } = new();

        /// <summary>
        /// 操作类型
        /// </summary>
        [Id(1)]
        public BatchOperationType OperationType { get; set; }

    }

    /// <summary>
    /// 查询FakeNews请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class QueryFakeNewsRequest
    {
        /// <summary>
        /// 新闻Id
        /// </summary>
        [Id(0)]
        public long Id { get; set; }

        /// <summary>
        /// 是否包含软删除的记录
        /// </summary>
        [Id(1)]
        public bool IncludeDeleted { get; set; } = false;

    }

    /// <summary>
    /// 搜索FakeNews请求
    /// </summary>
    [Serializable]
    [GenerateSerializer]
    [Immutable]
    public class SearchFakeNewsRequest
    {
        /// <summary>
        /// 搜索关键词
        /// </summary>
        [Id(0)]
        public string Keyword { get; set; } = string.Empty;

        /// <summary>
        /// 页码（从1开始）
        /// </summary>
        [Id(1)]
        public int Page { get; set; } = 1;

        /// <summary>
        /// 每页大小
        /// </summary>
        [Id(2)]
        public int PageSize { get; set; } = 20;

        /// <summary>
        /// 排序字段
        /// </summary>
        [Id(3)]
        public string SortBy { get; set; } = "CreatedAt";

        /// <summary>
        /// 排序方向
        /// </summary>
        [Id(4)]
        public SortDirection SortDirection { get; set; } = SortDirection.Descending;

        /// <summary>
        /// 过滤条件
        /// </summary>
        [Id(5)]
        public Dictionary<string, object> Filters { get; set; } = new();

    }
}
