// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-11-22 21:03:51
// </auto-generated>

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.RegularExpressions;
using Orleans.Serialization;
using Orleans;
using System.Collections.Generic;
using System.Linq;

namespace FakeMicro.Interfaces.Models
{
    /// <summary>
    /// FakeNews数据传输对象
    /// </summary>
[GenerateSerializer]
    public class FakeNewsDto
    {
        /// <summary>
        /// 新闻Id
        /// </summary>
        [Id(0)]
        [Required]
        public long Id { get; set; }

        /// <summary>
        /// 标题
        /// </summary>
        [Id(1)]
        [MaxLength(200)]
        public string title { get; set; } = string.Empty;

        /// <summary>
        /// 作者
        /// </summary>
        [Id(2)]
        [MaxLength(100)]
        public string author { get; set; } = string.Empty;

        /// <summary>
        /// 年级
        /// </summary>
        [Id(3)]
        [Required]
        public int order { get; set; }

        /// <summary>
        /// 专业
        /// </summary>
        [Id(4)]
        [MaxLength(10000)]
        public string content { get; set; } = string.Empty;

        /// <summary>
        /// 状态(1:正常,2:停课,3:毕业)
        /// </summary>
        [Id(5)]
        [Required]
        public int Status { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        [Id(6)]
        [MaxLength(500)]
        public string? Description { get; set; } = string.Empty;

        /// <summary>
        /// 验证DTO数据
        /// </summary>
        /// <returns>验证结果</returns>
        public (bool IsValid, List<string> Errors) Validate()
        {
            var errors = new List<string>();

            if (Id == null)
                errors.Add("Id 是必需的");

            if (string.IsNullOrWhiteSpace(title))
                errors.Add("title 是必需的");

            if (string.IsNullOrWhiteSpace(author))
                errors.Add("author 是必需的");

            if (order == null)
                errors.Add("order 是必需的");

            if (string.IsNullOrWhiteSpace(content))
                errors.Add("content 是必需的");

            if (Status == null)
                errors.Add("Status 是必需的");

            if (Description?.Length > 500)
                errors.Add("Description 长度不能超过 500 个字符");

            return (errors.Count == 0, errors);
        }

        /// <summary>
        /// 克隆DTO对象
        /// </summary>
        /// <returns>克隆的FakeNewsDto对象</returns>
        public FakeNewsDto Clone()
        {
            return new FakeNewsDto
            {
                Id = this.Id,
                title = this.title,
                author = this.author,
                order = this.order,
                content = this.content,
                Status = this.Status,
                Description = this.Description,
            };
        }

        /// <summary>
        /// 转换为字符串表示
        /// </summary>
        /// <returns>字符串表示</returns>
        public override string ToString()
        {
            return $"FakeNewsDto Id = {Id},title = {title},author = {author},order = {order},content = {content},Status = {Status},Description = {Description}";
        }

    }

    #region 请求和响应DTO

    /// <summary>
    /// 创建FakeNews请求
    /// </summary>
     [GenerateSerializer] 
    public class CreateFakeNewsRequest
    {
        /// <summary>
        /// title
        /// </summary>
        [Id(0)]
        [MaxLength(200)]
        public string title { get; set; } = string.Empty;

        /// <summary>
        /// author
        /// </summary>
        [Id(1)]
        [MaxLength(100)]
        public string author { get; set; } = string.Empty;

        /// <summary>
        /// order
        /// </summary>
        [Id(2)]
        [Required]
        public int order { get; set; }

        /// <summary>
        /// content
        /// </summary>
        [Id(3)]
        [MaxLength(10000)]
        public string content { get; set; } = string.Empty;

        /// <summary>
        /// Status
        /// </summary>
        [Id(4)]
        [Required]
        public int Status { get; set; }

        /// <summary>
        /// Description
        /// </summary>
        [Id(5)]
        [MaxLength(500)]
        public string? Description { get; set; }

    }

    /// <summary>
    /// 更新FakeNews请求
    /// </summary>
[GenerateSerializer]
    public class UpdateFakeNewsRequest
    {
        /// <summary>
        /// title
        /// </summary>
        [Id(0)]
        public string? title { get; set; }

        /// <summary>
        /// author
        /// </summary>
        [Id(1)]
        public string? author { get; set; }

        /// <summary>
        /// order
        /// </summary>
        [Id(2)]
        public int? order { get; set; }

        /// <summary>
        /// content
        /// </summary>
        [Id(3)]
        public string? content { get; set; }

        /// <summary>
        /// Status
        /// </summary>
        [Id(4)]
        public int? Status { get; set; }

        /// <summary>
        /// Description
        /// </summary>
        [Id(5)]
        public string? Description { get; set; }

    }

    /// <summary>
    /// 查询FakeNews请求
    /// </summary>
[GenerateSerializer]
    public class QueryFakeNewsRequest
    {
        [Id(0)]
        public int PageIndex { get; set; } = 1;
        [Id(1)]
        public int PageSize { get; set; } = 20;
        [Id(2)]
        public string? Keyword { get; set; }

        [Id(3)]
        public string? title { get; set; }

        [Id(4)]
        public string? author { get; set; }

        [Id(5)]
        public string? content { get; set; }

        [Id(6)]
        public string? Description { get; set; }

    }

    #endregion
}
