// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-11-22 21:03:51
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using Orleans;
using System.ComponentModel.DataAnnotations;
using FakeMicro.Entities;

namespace FakeMicro.Interfaces.Models.Results
{
    /// <summary>
    /// 创建FakeNews结果
    /// </summary>
    [GenerateSerializer]
    public class CreateFakeNewsResult : BaseResult
    {
        [Id(5)]
        public FakeNewsDto? CreatedFakeNews { get; set; }
        [Id(6)]
        public long? Id { get; set; }

        public static CreateFakeNewsResult CreateSuccess(FakeNewsDto entity, long id)
            => new CreateFakeNewsResult() { Success = true, CreatedFakeNews = entity, Id = id };

        public static CreateFakeNewsResult Failed(string errorMessage, string errorCode = null)
            => new CreateFakeNewsResult() { Success = false, ErrorMessage = errorMessage, ErrorCode = errorCode };

        // 推荐使用示例：Failed("记录未找到", "NOT_FOUND")
        // 推荐使用示例：Failed("资源冲突", "CONFLICT")
        // 推荐使用示例：Failed("无效引用", "INVALID_REFERENCE")
        // 推荐使用示例：Failed(string.Join("；", errors), "VALIDATION_FAILED")
        // 推荐使用示例：Failed("无效的Grain ID", "INVALID_GRAIN_ID")
    }

    /// <summary>
    /// 更新FakeNews结果
    /// </summary>
    [GenerateSerializer]
    public class UpdateFakeNewsResult : BaseResult
    {
        [Id(5)]
        public FakeNewsDto? UpdatedFakeNews { get; set; }
        [Id(6)]
        public long? Id { get; set; }

        public static UpdateFakeNewsResult CreateSuccess(FakeNewsDto entity, long id)
            => new UpdateFakeNewsResult() { Success = true, UpdatedFakeNews = entity, Id = id };

        public static UpdateFakeNewsResult Failed(string errorMessage, string errorCode = null)
            => new UpdateFakeNewsResult() { Success = false, ErrorMessage = errorMessage, ErrorCode = errorCode };

        // 推荐使用示例：Failed("记录未找到", "NOT_FOUND")
        // 推荐使用示例：Failed("资源冲突", "CONFLICT")
        // 推荐使用示例：Failed("无效引用", "INVALID_REFERENCE")
        // 推荐使用示例：Failed(string.Join("；", errors), "VALIDATION_FAILED")
        // 推荐使用示例：Failed("乐观并发错误", "OPTIMISTIC_CONCURRENCY")
        // 推荐使用示例：Failed("无效的Grain ID", "INVALID_GRAIN_ID")
    }

    /// <summary>
    /// 删除FakeNews结果
    /// </summary>
    [GenerateSerializer]
    public class DeleteFakeNewsResult : BaseResult
    {
        [Id(5)]
        public bool IsSoftDeleted { get; set; }
        [Id(6)]
        public long? Id { get; set; }

        public static DeleteFakeNewsResult CreateSuccess(bool isSoftDeleted = false, long? id = null)
            => new DeleteFakeNewsResult() { Success = true, IsSoftDeleted = isSoftDeleted, Id = id };

        public static DeleteFakeNewsResult Failed(string errorMessage, string errorCode = null)
            => new DeleteFakeNewsResult() { Success = false, ErrorMessage = errorMessage, ErrorCode = errorCode };

        // 推荐使用示例：Failed("记录未找到", "NOT_FOUND")
        // 推荐使用示例：Failed("无法删除，存在引用关系", "CANNOT_DELETE_REFERENCED")
        // 推荐使用示例：Failed("无效的Grain ID", "INVALID_GRAIN_ID")
        // 推荐使用示例：Failed("项目已经被删除", "ALREADY_DELETED")
    }

    /// <summary>
    /// 批量更新FakeNews结果
    /// </summary>
    [GenerateSerializer]
    public class BatchUpdateFakeNewsResult : BaseResult
    {
        [Id(5)]
        public int SuccessCount { get; set; }
        [Id(6)]
        public int FailedCount { get; set; }
        [Id(7)]
        public int TotalCount { get; set; }
        [Id(8)]
        public List<string> Errors { get; set; } = new();
        [Id(9)]
        public List<string> ValidationErrors { get; set; } = new();
        [Id(10)]
        public List<string> ConflictErrors { get; set; } = new();

        public double SuccessRate => TotalCount > 0 ? (double)SuccessCount / TotalCount * 100 : 0;

        public static BatchUpdateFakeNewsResult CreateSuccess(int successCount, int totalCount)
            => new BatchUpdateFakeNewsResult() { Success = true, SuccessCount = successCount, TotalCount = totalCount, FailedCount = totalCount - successCount };

        public static BatchUpdateFakeNewsResult Failed(List<string> errors, string errorCode = null, List<string> validationErrors = null, List<string> conflictErrors = null)
            => new BatchUpdateFakeNewsResult() { Success = false, ErrorCode = errorCode, FailedCount = errors?.Count ?? 0, TotalCount = (errors?.Count ?? 0) + (validationErrors?.Count ?? 0) + (conflictErrors?.Count ?? 0), Errors = errors ?? new(), ValidationErrors = validationErrors ?? new(), ConflictErrors = conflictErrors ?? new() };

        public static BatchUpdateFakeNewsResult PartialSuccess(int successCount, int totalCount, List<string> errors)
            => new BatchUpdateFakeNewsResult() { Success = true, SuccessCount = successCount, TotalCount = totalCount, FailedCount = errors?.Count ?? 0, Errors = errors ?? new() };

        // 推荐使用示例：Failed(new List<string>{"无效的Grain ID"}, "INVALID_GRAIN_ID")
        // 推荐使用示例：Failed(new List<string>{"批量更新请求为空"}, "EMPTY_REQUEST")
    }

    /// <summary>
    /// 批量删除FakeNews结果
    /// </summary>
    [GenerateSerializer]
    public class BatchDeleteFakeNewsResult : BaseResult
    {
        [Id(5)]
        public int SuccessCount { get; set; }
        [Id(6)]
        public int FailedCount { get; set; }
        [Id(7)]
        public int TotalCount { get; set; }
        [Id(8)]
        public int SoftDeletedCount { get; set; }
        [Id(9)]
        public int HardDeletedCount { get; set; }
        [Id(10)]
        public List<string> Errors { get; set; } = new();
        [Id(11)]
        public List<string> CannotDeleteReferencedErrors { get; set; } = new();
        [Id(12)]
        public List<string> NotFoundErrors { get; set; } = new();

        public double SuccessRate => TotalCount > 0 ? (double)SuccessCount / TotalCount * 100 : 0;

        public static BatchDeleteFakeNewsResult CreateSuccess(int successCount, int totalCount, int softDeletedCount = 0, int hardDeletedCount = 0)
            => new BatchDeleteFakeNewsResult() { Success = true, SuccessCount = successCount, TotalCount = totalCount, SoftDeletedCount = softDeletedCount, HardDeletedCount = hardDeletedCount, FailedCount = totalCount - successCount };

        public static BatchDeleteFakeNewsResult Failed(List<string> errors, string errorCode = null, List<string> cannotDeleteErrors = null, List<string> notFoundErrors = null)
            => new BatchDeleteFakeNewsResult() { Success = false, ErrorCode = errorCode, FailedCount = errors?.Count ?? 0, TotalCount = (errors?.Count ?? 0) + (cannotDeleteErrors?.Count ?? 0) + (notFoundErrors?.Count ?? 0), Errors = errors ?? new(), CannotDeleteReferencedErrors = cannotDeleteErrors ?? new(), NotFoundErrors = notFoundErrors ?? new() };

        public static BatchDeleteFakeNewsResult PartialSuccess(int successCount, int totalCount, int softDeletedCount, int hardDeletedCount, List<string> errors, List<string> cannotDeleteErrors = null, List<string> notFoundErrors = null)
            => new BatchDeleteFakeNewsResult() { Success = true, SuccessCount = successCount, TotalCount = totalCount, SoftDeletedCount = softDeletedCount, HardDeletedCount = hardDeletedCount, FailedCount = (errors?.Count ?? 0) + (cannotDeleteErrors?.Count ?? 0) + (notFoundErrors?.Count ?? 0), Errors = errors ?? new(), CannotDeleteReferencedErrors = cannotDeleteErrors ?? new(), NotFoundErrors = notFoundErrors ?? new() };

        // 推荐使用示例：Failed(new List<string>{"无效的Grain ID"}, "INVALID_GRAIN_ID")
        // 推荐使用示例：Failed(new List<string>{"批量删除请求为空"}, "EMPTY_REQUEST")
    }

    /// <summary>
    /// FakeNews统计信息
    /// </summary>
    [GenerateSerializer]
    public class FakeNewsStatistics
    {
        [Id(0)]
        public int TotalCount { get; set; }
        [Id(1)]
        public int ActiveCount { get; set; }
        [Id(2)]
        public int CreatedToday { get; set; }
        [Id(3)]
        public int CreatedThisWeek { get; set; }
        [Id(4)]
        public int CreatedThisMonth { get; set; }
        [Id(5)]
        public int UpdatedToday { get; set; }
        [Id(6)]
        public int UpdatedThisWeek { get; set; }
        [Id(7)]
        public int UpdatedThisMonth { get; set; }
        [Id(8)]
        public DateTime? LastCreated { get; set; }
        [Id(9)]
        public DateTime? LastUpdated { get; set; }

        /// <summary>
        /// 活跃率（百分比）
        /// </summary>
        public double ActiveRatio => TotalCount > 0 ? (double)ActiveCount / TotalCount * 100 : 0;

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public FakeNewsStatistics()
        {
            // 初始化所有属性
        }
    }
}
