// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-11-21 13:10:31
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using Orleans;
using System.ComponentModel.DataAnnotations;
using FakeMicro.Entities;

namespace FakeMicro.Interfaces.Models.Results
{
    /// <summary>
    /// 创建FakeNews结果
    /// </summary>
    [GenerateSerializer]
    public class CreateFakeNewsResult : BaseResult
    {
        [Id(5)]
        public FakeNewsDto? CreatedFakeNews { get; set; }
        [Id(6)]
        public long? Id { get; set; }

        public static CreateFakeNewsResult CreateSuccess(FakeNewsDto entity, long id)
            => new() { Success = true, CreatedFakeNews = entity, Id = id };

        public static CreateFakeNewsResult Failed(string errorMessage)
            => new() { Success = false, ErrorMessage = errorMessage };

        public static CreateFakeNewsResult NotFound(string errorMessage)
            => new() { Success = false, ErrorMessage = errorMessage, ErrorCode = "NOT_FOUND" };

        public static CreateFakeNewsResult Conflict(string errorMessage)
            => new() { Success = false, ErrorMessage = errorMessage, ErrorCode = "CONFLICT" };

        public static CreateFakeNewsResult InvalidReference(string errorMessage)
            => new() { Success = false, ErrorMessage = errorMessage, ErrorCode = "INVALID_REFERENCE" };

        public static CreateFakeNewsResult ValidationFailed(List<string> errors)
            => new() { Success = false, ErrorMessage = string.Join("; ", errors), ErrorCode = "VALIDATION_FAILED" };

        public static CreateFakeNewsResult InvalidGrainId()
            => new() { Success = false, ErrorMessage = "无效的Grain ID", ErrorCode = "INVALID_GRAIN_ID" };
    }

    /// <summary>
    /// 更新FakeNews结果
    /// </summary>
    [GenerateSerializer]
    public class UpdateFakeNewsResult : BaseResult
    {
        [Id(5)]
        public FakeNewsDto? UpdatedFakeNews { get; set; }
        [Id(6)]
        public long? Id { get; set; }

        public static UpdateFakeNewsResult CreateSuccess(FakeNewsDto entity, long id)
            => new() { Success = true, UpdatedFakeNews = entity, Id = id };

        public static UpdateFakeNewsResult Failed(string errorMessage)
            => new() { Success = false, ErrorMessage = errorMessage };

        public static UpdateFakeNewsResult NotFound(string errorMessage)
            => new() { Success = false, ErrorMessage = errorMessage, ErrorCode = "NOT_FOUND" };

        public static UpdateFakeNewsResult Conflict(string errorMessage)
            => new() { Success = false, ErrorMessage = errorMessage, ErrorCode = "CONFLICT" };

        public static UpdateFakeNewsResult InvalidReference(string errorMessage)
            => new() { Success = false, ErrorMessage = errorMessage, ErrorCode = "INVALID_REFERENCE" };

        public static UpdateFakeNewsResult ValidationFailed(List<string> errors)
            => new() { Success = false, ErrorMessage = string.Join("; ", errors), ErrorCode = "VALIDATION_FAILED" };

        public static UpdateFakeNewsResult OptimisticConcurrency(string errorMessage)
            => new() { Success = false, ErrorMessage = errorMessage, ErrorCode = "OPTIMISTIC_CONCURRENCY" };

        public static UpdateFakeNewsResult InvalidGrainId()
            => new() { Success = false, ErrorMessage = "无效的Grain ID", ErrorCode = "INVALID_GRAIN_ID" };
    }

    /// <summary>
    /// 删除FakeNews结果
    /// </summary>
    [GenerateSerializer]
    public class DeleteFakeNewsResult : BaseResult
    {
        [Id(5)]
        public bool IsSoftDeleted { get; set; }
        [Id(6)]
        public long? Id { get; set; }

        public static DeleteFakeNewsResult CreateSuccess(bool isSoftDeleted = false, long? id = null)
            => new() { Success = true, IsSoftDeleted = isSoftDeleted, Id = id };

        public static DeleteFakeNewsResult Failed(string errorMessage)
            => new() { Success = false, ErrorMessage = errorMessage };

        public static DeleteFakeNewsResult NotFound(string errorMessage)
            => new() { Success = false, ErrorMessage = errorMessage, ErrorCode = "NOT_FOUND" };

        public static DeleteFakeNewsResult CannotDeleteReferenced(string errorMessage)
            => new() { Success = false, ErrorMessage = errorMessage, ErrorCode = "CANNOT_DELETE_REFERENCED" };

        public static DeleteFakeNewsResult InvalidGrainId()
            => new() { Success = false, ErrorMessage = "无效的Grain ID", ErrorCode = "INVALID_GRAIN_ID" };

        public static DeleteFakeNewsResult AlreadyDeleted()
            => new() { Success = false, ErrorMessage = "项目已经被删除", ErrorCode = "ALREADY_DELETED" };
    }

    /// <summary>
    /// 批量更新FakeNews结果
    /// </summary>
    [GenerateSerializer]
    public class BatchUpdateFakeNewsResult : BaseResult
    {
        [Id(5)]
        public int SuccessCount { get; set; }
        [Id(6)]
        public int FailedCount { get; set; }
        [Id(7)]
        public int TotalCount { get; set; }
        [Id(8)]
        public List<string> Errors { get; set; } = new();
        [Id(9)]
        public List<string> ValidationErrors { get; set; } = new();
        [Id(10)]
        public List<string> ConflictErrors { get; set; } = new();

        public double SuccessRate => TotalCount > 0 ? (double)SuccessCount / TotalCount * 100 : 0;

        public static BatchUpdateFakeNewsResult CreateSuccess(int successCount, int totalCount)
            => new() { Success = true, SuccessCount = successCount, TotalCount = totalCount, FailedCount = totalCount - successCount };

        public static BatchUpdateFakeNewsResult Failed(List<string> errors, List<string> validationErrors = null, List<string> conflictErrors = null)
            => new() { Success = false, FailedCount = errors?.Count ?? 0, TotalCount = (errors?.Count ?? 0) + (validationErrors?.Count ?? 0) + (conflictErrors?.Count ?? 0), Errors = errors ?? new(), ValidationErrors = validationErrors ?? new(), ConflictErrors = conflictErrors ?? new() };

        public static BatchUpdateFakeNewsResult PartialSuccess(int successCount, int totalCount, List<string> errors)
            => new() { Success = true, SuccessCount = successCount, TotalCount = totalCount, FailedCount = errors?.Count ?? 0, Errors = errors ?? new() };

        public static BatchUpdateFakeNewsResult InvalidGrainId()
            => new() { Success = false, ErrorMessage = "无效的Grain ID", ErrorCode = "INVALID_GRAIN_ID" };

        public static BatchUpdateFakeNewsResult EmptyRequest()
            => new() { Success = false, ErrorMessage = "批量更新请求为空", ErrorCode = "EMPTY_REQUEST" };
    }

    /// <summary>
    /// 批量删除FakeNews结果
    /// </summary>
    [GenerateSerializer]
    public class BatchDeleteFakeNewsResult : BaseResult
    {
        [Id(5)]
        public int SuccessCount { get; set; }
        [Id(6)]
        public int FailedCount { get; set; }
        [Id(7)]
        public int TotalCount { get; set; }
        [Id(8)]
        public int SoftDeletedCount { get; set; }
        [Id(9)]
        public int HardDeletedCount { get; set; }
        [Id(10)]
        public List<string> Errors { get; set; } = new();
        [Id(11)]
        public List<string> CannotDeleteReferencedErrors { get; set; } = new();
        [Id(12)]
        public List<string> NotFoundErrors { get; set; } = new();

        public double SuccessRate => TotalCount > 0 ? (double)SuccessCount / TotalCount * 100 : 0;

        public static BatchDeleteFakeNewsResult CreateSuccess(int successCount, int totalCount, int softDeletedCount = 0, int hardDeletedCount = 0)
            => new() { Success = true, SuccessCount = successCount, TotalCount = totalCount, SoftDeletedCount = softDeletedCount, HardDeletedCount = hardDeletedCount, FailedCount = totalCount - successCount };

        public static BatchDeleteFakeNewsResult Failed(List<string> errors, List<string> cannotDeleteErrors = null, List<string> notFoundErrors = null)
            => new() { Success = false, FailedCount = errors?.Count ?? 0, TotalCount = (errors?.Count ?? 0) + (cannotDeleteErrors?.Count ?? 0) + (notFoundErrors?.Count ?? 0), Errors = errors ?? new(), CannotDeleteReferencedErrors = cannotDeleteErrors ?? new(), NotFoundErrors = notFoundErrors ?? new() };

        public static BatchDeleteFakeNewsResult PartialSuccess(int successCount, int totalCount, int softDeletedCount, int hardDeletedCount, List<string> errors, List<string> cannotDeleteErrors = null, List<string> notFoundErrors = null)
            => new() { Success = true, SuccessCount = successCount, TotalCount = totalCount, SoftDeletedCount = softDeletedCount, HardDeletedCount = hardDeletedCount, FailedCount = (errors?.Count ?? 0) + (cannotDeleteErrors?.Count ?? 0) + (notFoundErrors?.Count ?? 0), Errors = errors ?? new(), CannotDeleteReferencedErrors = cannotDeleteErrors ?? new(), NotFoundErrors = notFoundErrors ?? new() };

        public static BatchDeleteFakeNewsResult InvalidGrainId()
            => new() { Success = false, ErrorMessage = "无效的Grain ID", ErrorCode = "INVALID_GRAIN_ID" };

        public static BatchDeleteFakeNewsResult EmptyRequest()
            => new() { Success = false, ErrorMessage = "批量删除请求为空", ErrorCode = "EMPTY_REQUEST" };

        public static BatchDeleteFakeNewsResult NotFound(string errorMessage)
         => new() { Success = false, ErrorMessage = errorMessage, ErrorCode = "NOT_FOUND" };
    }

    /// <summary>
    /// FakeNews统计信息
    /// </summary>
     [GenerateSerializer]
    public class FakeNewsStatistics
    {
        [Id(0)]
        public int TotalCount { get; set; }
        [Id(1)]
        public int ActiveCount { get; set; }
        [Id(2)]
        public int CreatedToday { get; set; }
        [Id(3)]
        public int CreatedThisWeek { get; set; }
        [Id(4)]
        public int CreatedThisMonth { get; set; }
        [Id(5)]
        public DateTime? LastCreated { get; set; }
        [Id(6)]
        public DateTime? LastUpdated { get; set; }
    }
}
