// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-11-20 22:08:21
// </auto-generated>

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.RegularExpressions;
using Orleans.Serialization;
using Orleans;
using System.Collections.Generic;
using System.Linq;

namespace FakeMicro.Interfaces.Models
{
    /// <summary>
    /// FakeStudent数据传输对象
    /// </summary>
    [GenerateSerializer]
    public class FakeStudentDto
    {
        /// <summary>
        /// 班级唯一标识
        /// </summary>
        [Id(0)]
        [Required]
        public long Id { get; set; }

        /// <summary>
        /// 班级名称
        /// </summary>
        [Id(1)]
        [MaxLength(100)]
        public string ClassName { get; set; } = string.Empty;

        /// <summary>
        /// 班级编号
        /// </summary>
        [Id(2)]
        [MaxLength(20)]
        public string ClassCode { get; set; } = string.Empty;

        /// <summary>
        /// 年级
        /// </summary>
        [Id(3)]
        [Required]
        public int Grade { get; set; }

        /// <summary>
        /// 专业
        /// </summary>
        [Id(4)]
        [MaxLength(100)]
        public string Major { get; set; } = string.Empty;

        /// <summary>
        /// 班主任ID
        /// </summary>
        [Id(5)]
        public long? TeacherId { get; set; }

        /// <summary>
        /// 最大学生数
        /// </summary>
        [Id(6)]
        [Required]
        public int MaxStudents { get; set; }

        /// <summary>
        /// 当前学生数
        /// </summary>
        [Id(7)]
        [Required]
        public int CurrentStudents { get; set; }

        /// <summary>
        /// 班级状态(1:正常,2:停课,3:毕业)
        /// </summary>
        [Id(8)]
        [Required]
        public int Status { get; set; }

        /// <summary>
        /// 班级描述
        /// </summary>
        [Id(9)]
        [MaxLength(500)]
        public string? Description { get; set; }

        /// <summary>
        /// 验证DTO数据
        /// </summary>
        /// <returns>验证结果</returns>
        public (bool IsValid, List<string> Errors) Validate()
        {            var errors = new List<string>();

            if (string.IsNullOrWhiteSpace(ClassName))
                errors.Add("ClassName 是必需的");

            if (string.IsNullOrWhiteSpace(ClassCode))
                errors.Add("ClassCode 是必需的");

            if (string.IsNullOrWhiteSpace(Major))
                errors.Add("Major 是必需的");

            if (Description?.Length > 500)
                errors.Add("Description 长度不能超过 500 个字符");

            if (!string.IsNullOrWhiteSpace(ClassCode))
            {
                var codeRegex = new Regex(@"^[A-Z0-9_]+$");
                if (!codeRegex.IsMatch(ClassCode.Trim().ToUpper()))
                    errors.Add("ClassCode 只能包含大写字母、数字和下划线");
            }

            return (errors.Count == 0, errors);
        }

        /// <summary>
        /// 克隆DTO对象
        /// </summary>
        /// <returns>克隆的FakeStudentDto对象</returns>
        public FakeStudentDto Clone()
        {
            return new FakeStudentDto
            {
                Id = this.Id,
                ClassName = this.ClassName,
                ClassCode = this.ClassCode,
                Grade = this.Grade,
                Major = this.Major,
                TeacherId = this.TeacherId,
                MaxStudents = this.MaxStudents,
                CurrentStudents = this.CurrentStudents,
                Status = this.Status,
                Description = this.Description,
            };
        }

        /// <summary>
        /// 转换为字符串表示
        /// </summary>
        /// <returns>字符串表示</returns>
        public override string ToString()
        {
            return $"FakeStudentDto Id = {Id},ClassName = {ClassName},ClassCode = {ClassCode},Grade = {Grade},Major = {Major},TeacherId = {TeacherId},MaxStudents = {MaxStudents},CurrentStudents = {CurrentStudents},Status = {Status},Description = {Description}";
        }

    }

    #region 请求和响应DTO

    /// <summary>
    /// 创建FakeStudent请求
    /// </summary>
    [GenerateSerializer]
    public class CreateFakeStudentRequest
    {
        /// <summary>
        /// ClassName
        /// </summary>
        [Id(0)]
        [MaxLength(100)]
        public string ClassName { get; set; } = string.Empty;

        /// <summary>
        /// ClassCode
        /// </summary>
        [Id(1)]
        [MaxLength(20)]
        public string ClassCode { get; set; } = string.Empty;

        /// <summary>
        /// Grade
        /// </summary>
        [Id(2)]
        [Required]
        public int Grade { get; set; }

        /// <summary>
        /// Major
        /// </summary>
        [Id(3)]
        [MaxLength(100)]
        public string Major { get; set; } = string.Empty;

        /// <summary>
        /// TeacherId
        /// </summary>
        [Id(4)]
        public long? TeacherId { get; set; }

        /// <summary>
        /// MaxStudents
        /// </summary>
        [Id(5)]
        [Required]
        public int MaxStudents { get; set; }

        /// <summary>
        /// CurrentStudents
        /// </summary>
        [Id(6)]
        [Required]
        public int CurrentStudents { get; set; }

        /// <summary>
        /// Status
        /// </summary>
        [Id(7)]
        [Required]
        public int Status { get; set; }

        /// <summary>
        /// Description
        /// </summary>
        [Id(8)]
        [MaxLength(500)]
        public string? Description { get; set; }

    }

    /// <summary>
    /// 更新FakeStudent请求
    /// </summary>
    [GenerateSerializer]
    public class UpdateFakeStudentRequest
    {
        /// <summary>
        /// ClassName
        /// </summary>
        [Id(0)]
        public string? ClassName { get; set; }

        /// <summary>
        /// ClassCode
        /// </summary>
        [Id(1)]
        public string? ClassCode { get; set; }

        /// <summary>
        /// Grade
        /// </summary>
        [Id(2)]
        public int? Grade { get; set; }

        /// <summary>
        /// Major
        /// </summary>
        [Id(3)]
        public string? Major { get; set; }

        /// <summary>
        /// TeacherId
        /// </summary>
        [Id(4)]
        public long? TeacherId { get; set; }

        /// <summary>
        /// MaxStudents
        /// </summary>
        [Id(5)]
        public int? MaxStudents { get; set; }

        /// <summary>
        /// CurrentStudents
        /// </summary>
        [Id(6)]
        public int? CurrentStudents { get; set; }

        /// <summary>
        /// Status
        /// </summary>
        [Id(7)]
        public int? Status { get; set; }

        /// <summary>
        /// Description
        /// </summary>
        [Id(8)]
        public string? Description { get; set; }

    }

    /// <summary>
    /// 查询FakeStudent请求
    /// </summary>
    [GenerateSerializer]
    public class QueryFakeStudentRequest
    {
        [Id(0)]
        public int PageIndex { get; set; } = 1;
        [Id(1)]
        public int PageSize { get; set; } = 20;
        [Id(2)]
        public string? Keyword { get; set; }

        [Id(3)]
        public string? ClassName { get; set; }

        [Id(4)]
        public string? ClassCode { get; set; }

        [Id(5)]
        public string? Major { get; set; }

        [Id(6)]
        public string? Description { get; set; }

    }

    #endregion
}