// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-11-22 21:03:51
//     功能: FakeNews仓储实现类
//     架构: 遵循Orleans最佳实践，继承SqlSugarRepository
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using SqlSugar;
using FakeMicro.DatabaseAccess;
using FakeMicro.DatabaseAccess.Interfaces;
using FakeMicro.Entities;
using FakeMicro.Interfaces.Models;

namespace FakeMicro.DatabaseAccess.Repositories
{
    /// <summary>
    /// FakeNews仓储实现类
    /// 继承SqlSugarRepository，遵循Orleans架构最佳实践
    /// </summary>
    public class FakeNewsRepository : SqlSugarRepository<FakeNews, long>, IFakeNewsRepository
    {
        private readonly ILogger<FakeNewsRepository> _logger;

        /// <summary>
        /// FakeNews仓储构造函数
        /// </summary>
        /// <param name="db">SqlSugar数据库客户端</param>
        /// <param name="logger">日志记录器</param>
        public FakeNewsRepository(ISqlSugarClient db, ILogger<FakeNewsRepository> logger)
            : base(db, logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        #region 基类方法重写

        /// <summary>
        /// 重写获取FakeNews方法，添加性能优化
        /// </summary>
        /// <param name="id">主键值</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>FakeNews实体</returns>
        public new async virtual Task<FakeNews?> GetByIdAsync(long id, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                // 使用SqlSugar的查询优化，添加WITH(NOLOCK)提示
                return await GetSqlSugarClient().Queryable<FakeNews>()
                    .With(SqlWith.NoLock)
                    .Where(entity => entity.Id == id)
                    .FirstAsync(cancellationToken);
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "获取FakeNews失败: {Id}", id);
                throw new DataAccessException("获取FakeNews失败: " + id, ex);
            }
        }

        /// <summary>
        /// 创建FakeNews并返回创建后的实体
        /// </summary>
        /// <param name="entity">FakeNews实体</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>创建后的FakeNews实体</returns>
        public async virtual Task<FakeNews?> CreateAndReturnAsync(FakeNews entity, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (entity == null) throw new ArgumentNullException(nameof(entity));
            
            try
            {
                var result = await GetSqlSugarClient().Insertable(entity).ExecuteReturnEntityAsync();
                _logger.LogInformation("成功创建FakeNews: {Id}", typeof(FakeNews).Name, result.Id);
                return result;
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "创建FakeNews失败");
                throw new DataAccessException("创建FakeNews失败", ex);
            }
        }

        /// <summary>
        /// 更新FakeNews并返回更新后的实体
        /// </summary>
        /// <param name="entity">FakeNews实体</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>更新后的FakeNews实体</returns>
        public async virtual Task<FakeNews?> UpdateAndReturnAsync(FakeNews entity, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (entity == null) throw new ArgumentNullException(nameof(entity));
            
            try
            {
                var result = await GetSqlSugarClient().Updateable(entity).ExecuteReturnEntityAsync();
                _logger.LogInformation("成功更新FakeNews: {Id}", typeof(FakeNews).Name, entity.Id);
                return result;
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "更新FakeNews失败");
                throw new DataAccessException("更新FakeNews失败", ex);
            }
        }

        /// <summary>
        /// 批量创建FakeNews并返回创建后的实体列表
        /// </summary>
        /// <param name="entities">FakeNews实体集合</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>创建后的FakeNews实体列表</returns>
        public async virtual Task<IEnumerable<FakeNews>?> CreateRangeAndReturnAsync(IEnumerable<FakeNews> entities, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (entities == null) throw new ArgumentNullException(nameof(entities));
            var entityList = entities.ToList();
            if (!entityList.Any()) return Enumerable.Empty<FakeNews>();
            
            try
            {
                var affectedRows = await GetSqlSugarClient().Insertable(entityList).ExecuteCommandAsync(cancellationToken);
                _logger.LogInformation("成功批量创建FakeNews，数量: {Count}", affectedRows);
                return entityList;
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "批量创建FakeNews失败，数量: {Count}", entityList.Count);
                throw new DataAccessException("批量创建FakeNews失败", ex);
            }
        }

        #endregion

        #region Orleans Grain特定操作

        /// <summary>
        /// 通过Grain ID获取FakeNews（Orleans特定）
        /// </summary>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>FakeNews实体</returns>
        public async virtual Task<FakeNews?> GetByGrainIdAsync(CancellationToken cancellationToken = default)
        {
            // 注意：此方法在Grain实现中会被重写，用于通过Grain的ID获取实体
            // 默认实现返回null，实际使用时应在Grain上下文中根据具体ID策略实现
            return null;
        }

        /// <summary>
        /// 创建FakeNews（Orleans特定）
        /// </summary>
        /// <param name="entity">FakeNews实体</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>创建后的FakeNews实体</returns>
        public async virtual Task<FakeNews> CreateAsync(FakeNews entity, CancellationToken cancellationToken = default)
        {
            return await CreateAndReturnAsync(entity, cancellationToken);
        }

        #endregion

        #region 同步方法包装

        /// <summary>
        /// 同步更新方法（包装异步方法）
        /// </summary>
        public void Update(FakeNews entity)
        {
            UpdateAsync(entity).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步批量更新方法（包装异步方法）
        /// </summary>
        public void UpdateRange(IEnumerable<FakeNews> entities)
        {
            UpdateRangeAsync(entities).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步删除方法（包装异步方法）
        /// </summary>
        public void Delete(FakeNews entity)
        {
            DeleteAsync(entity).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步批量删除方法（包装异步方法）
        /// </summary>
        public void DeleteRange(IEnumerable<FakeNews> entities)
        {
            DeleteRangeAsync(entities).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步部分更新方法（包装异步方法）
        /// </summary>
        public void UpdatePartial(FakeNews entity, params Expression<Func<FakeNews, object>>[] properties)
        {
            UpdatePartialAsync(entity, properties).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 基于属性的同步方法适配器
        /// </summary>
        /// <summary>
        /// 同步获取FakeNews（根据title）
        /// </summary>
        public FakeNews? GetBytitle(string title)
        {
            return GetBytitleAsync(title).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步检查title是否存在
        /// </summary>
        public bool titleExists(string title, long excludeId = default)
        {
            return titleExistsAsync(title, excludeId).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步获取FakeNews（根据author）
        /// </summary>
        public FakeNews? GetByauthor(string author)
        {
            return GetByauthorAsync(author).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步检查author是否存在
        /// </summary>
        public bool authorExists(string author, long excludeId = default)
        {
            return authorExistsAsync(author, excludeId).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步获取FakeNews（根据content）
        /// </summary>
        public FakeNews? GetBycontent(string content)
        {
            return GetBycontentAsync(content).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步检查content是否存在
        /// </summary>
        public bool contentExists(string content, long excludeId = default)
        {
            return contentExistsAsync(content, excludeId).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步获取FakeNews（根据Description）
        /// </summary>
        public FakeNews? GetByDescription(string description)
        {
            return GetByDescriptionAsync(description).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 同步检查Description是否存在
        /// </summary>
        public bool DescriptionExists(string description, long excludeId = default)
        {
            return DescriptionExistsAsync(description, excludeId).GetAwaiter().GetResult();
        }

        #endregion

        #region 分页查询方法

        /// <summary>
        /// 分页查询FakeNews（Orleans接口兼容）
        /// </summary>
        /// <param name="pageNumber">页码（从1开始）</param>
        /// <param name="pageSize">页大小</param>
        /// <param name="orderBy">排序表达式（可选）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>分页结果</returns>
        public async virtual Task<PagedResult<FakeNews>> GetPagedAsync(int pageNumber, int pageSize, 
            Expression<Func<FakeNews, object>>? orderBy = null, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (pageNumber < 1) pageNumber = 1;
            if (pageSize < 1) pageSize = 20;
            
            try
            {
                // 使用基类的分页方法
                var orderByExpression = orderBy ?? (x => x.Id);
                var result = await base.GetPagedAsync(pageNumber, pageSize, orderByExpression, false, cancellationToken);
                _logger.LogInformation("成功获取FakeNews分页数据，页码: {PageNumber}, 页大小: {PageSize}", pageNumber, pageSize);
                return result;
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "获取FakeNews分页数据失败，页码: {PageNumber}, 页大小: {PageSize}", pageNumber, pageSize);
                throw new DataAccessException("获取FakeNews分页数据失败", ex);
            }
        }

        /// <summary>
        /// 条件分页查询FakeNews（Orleans接口兼容）
        /// </summary>
        /// <param name="predicate">查询条件</param>
        /// <param name="pageNumber">页码（从1开始）</param>
        /// <param name="pageSize">页大小</param>
        /// <param name="orderBy">排序表达式（可选）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>分页结果</returns>
        public async virtual Task<PagedResult<FakeNews>> GetPagedByConditionAsync(
            Expression<Func<FakeNews, bool>> predicate, int pageNumber, int pageSize,
            Expression<Func<FakeNews, object>>? orderBy = null, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (pageNumber < 1) pageNumber = 1;
            if (pageSize < 1) pageSize = 20;
            if (predicate == null) throw new ArgumentNullException(nameof(predicate));
            
            try
            {
                // 使用基类的条件分页方法
                var orderByExpression = orderBy ?? (x => x.Id);
                var result = await base.GetPagedByConditionAsync(predicate, pageNumber, pageSize, orderByExpression, false, cancellationToken);
                _logger.LogInformation("成功获取FakeNews条件分页数据，页码: {PageNumber}, 页大小: {PageSize}", pageNumber, pageSize);
                return result;
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "获取FakeNews条件分页数据失败，页码: {0}, 页大小: {1}", pageNumber, pageSize);
                throw new DataAccessException("获取FakeNews条件分页数据失败", ex);
            }
        }

        #endregion

        #region 业务查询方法

        /// <summary>
        /// 根据title查询FakeNews
        /// </summary>
        /// <param name="title">title</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>FakeNews实体</returns>
        public async Task<FakeNews?> GetBytitleAsync(string title, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                return await GetSqlSugarClient().Queryable<FakeNews>()
                    .Where(entity => entity.title == title)
                    .FirstAsync();
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"根据title获取FakeNews失败: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// 检查title是否存在
        /// </summary>
        /// <param name="title">title</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        public async Task<bool> titleExistsAsync(string title, long excludeId = default, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                var query = GetSqlSugarClient().Queryable<FakeNews>()
                    .Where(entity => entity.title == title);
                
                if (!excludeId.Equals(default(long)))
                {
                    query = query.Where(entity => entity.Id != excludeId);
                }
                
                var count = await query.CountAsync();
                return count > 0;
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"检查FakeNewstitle是否存在失败: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// 根据author查询FakeNews
        /// </summary>
        /// <param name="author">author</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>FakeNews实体</returns>
        public async Task<FakeNews?> GetByauthorAsync(string author, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                return await GetSqlSugarClient().Queryable<FakeNews>()
                    .Where(entity => entity.author == author)
                    .FirstAsync();
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"根据author获取FakeNews失败: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// 检查author是否存在
        /// </summary>
        /// <param name="author">author</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        public async Task<bool> authorExistsAsync(string author, long excludeId = default, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                var query = GetSqlSugarClient().Queryable<FakeNews>()
                    .Where(entity => entity.author == author);
                
                if (!excludeId.Equals(default(long)))
                {
                    query = query.Where(entity => entity.Id != excludeId);
                }
                
                var count = await query.CountAsync();
                return count > 0;
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"检查FakeNewsauthor是否存在失败: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// 根据content查询FakeNews
        /// </summary>
        /// <param name="content">content</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>FakeNews实体</returns>
        public async Task<FakeNews?> GetBycontentAsync(string content, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                return await GetSqlSugarClient().Queryable<FakeNews>()
                    .Where(entity => entity.content == content)
                    .FirstAsync();
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"根据content获取FakeNews失败: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// 检查content是否存在
        /// </summary>
        /// <param name="content">content</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        public async Task<bool> contentExistsAsync(string content, long excludeId = default, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                var query = GetSqlSugarClient().Queryable<FakeNews>()
                    .Where(entity => entity.content == content);
                
                if (!excludeId.Equals(default(long)))
                {
                    query = query.Where(entity => entity.Id != excludeId);
                }
                
                var count = await query.CountAsync();
                return count > 0;
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"检查FakeNewscontent是否存在失败: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// 根据Description查询FakeNews
        /// </summary>
        /// <param name="description">Description</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>FakeNews实体</returns>
        public async Task<FakeNews?> GetByDescriptionAsync(string description, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                return await GetSqlSugarClient().Queryable<FakeNews>()
                    .Where(entity => entity.Description == description)
                    .FirstAsync();
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"根据Description获取FakeNews失败: {ex.Message}", ex);
            }
        }

        /// <summary>
        /// 检查Description是否存在
        /// </summary>
        /// <param name="description">Description</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        public async Task<bool> DescriptionExistsAsync(string description, long excludeId = default, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                var query = GetSqlSugarClient().Queryable<FakeNews>()
                    .Where(entity => entity.Description == description);
                
                if (!excludeId.Equals(default(long)))
                {
                    query = query.Where(entity => entity.Id != excludeId);
                }
                
                var count = await query.CountAsync();
                return count > 0;
            }
            catch (SqlSugarException ex)
            {
                throw new Exception($"检查FakeNewsDescription是否存在失败: {ex.Message}", ex);
            }
        }

        #endregion

    }
}
