// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-12-01
//     功能: FakeNews MongoDB仓储实现类
//     架构: 遵循Orleans最佳实践，继承MongoRepository
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using FakeMicro.DatabaseAccess.Interfaces;
using FakeMicro.Entities;
using Microsoft.Extensions.Logging;
using MongoDB.Driver;

namespace FakeMicro.DatabaseAccess.Repositories
{
    /// <summary>
    /// FakeNews MongoDB仓储实现类
    /// 继承MongoRepository，遵循Orleans架构最佳实践
    /// </summary>
    public class MongoFakeNewsRepository : MongoRepository<FakeNews, long>, IFakeNewsRepository
    {
        private readonly ILogger<MongoFakeNewsRepository> _logger;

        /// <summary>
        /// FakeNews MongoDB仓储构造函数
        /// </summary>
        /// <param name="database">MongoDB数据库</param>
        /// <param name="logger">日志记录器</param>
        public MongoFakeNewsRepository(IMongoDatabase database, ILogger<MongoFakeNewsRepository> logger)
            : base(database, logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        #region Orleans Grain特定操作

        /// <summary>
        /// 通过Orleans Grain ID获取FakeNews实体
        /// </summary>
        /// <param name="id">主键值</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>FakeNews实体</returns>
        public new async virtual Task<FakeNews?> GetByIdAsync(long id, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                return await base.GetByIdAsync(id, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "获取FakeNews失败: {Id}", id);
                throw new DataAccessException("获取FakeNews失败: " + id, ex);
            }
        }

        /// <summary>
        /// 创建FakeNews并返回创建后的实体
        /// </summary>
        /// <param name="entity">FakeNews实体</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>创建后的FakeNews实体</returns>
        public async virtual Task<FakeNews?> CreateAndReturnAsync(FakeNews entity, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (entity == null) throw new ArgumentNullException(nameof(entity));
            
            try
            {
                await AddAsync(entity, cancellationToken);
                _logger.LogInformation("成功创建FakeNews: {Id}", entity.Id);
                return entity;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "创建FakeNews失败");
                throw new DataAccessException("创建FakeNews失败", ex);
            }
        }

        /// <summary>
        /// 更新FakeNews并返回更新后的实体
        /// </summary>
        /// <param name="entity">FakeNews实体</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>更新后的FakeNews实体</returns>
        public async virtual Task<FakeNews?> UpdateAndReturnAsync(FakeNews entity, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (entity == null) throw new ArgumentNullException(nameof(entity));
            
            try
            {
                await UpdateAsync(entity, cancellationToken);
                _logger.LogInformation("成功更新FakeNews: {Id}", entity.Id);
                return entity;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "更新FakeNews失败");
                throw new DataAccessException("更新FakeNews失败", ex);
            }
        }

        /// <summary>
        /// 创建FakeNews（Orleans特定）
        /// </summary>
        /// <param name="entity">FakeNews实体</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>创建后的FakeNews实体</returns>
        public async virtual Task<FakeNews> CreateAsync(FakeNews entity, CancellationToken cancellationToken = default)
        {
            return await CreateAndReturnAsync(entity, cancellationToken);
        }

        #endregion

        #region 批量业务操作

        /// <summary>
        /// 批量创建FakeNews实体并返回创建后的实体
        /// </summary>
        /// <param name="entities">FakeNews实体集合</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>创建后的实体集合</returns>
        public async virtual Task<IEnumerable<FakeNews>> CreateRangeAndReturnAsync(IEnumerable<FakeNews> entities, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (entities == null) throw new ArgumentNullException(nameof(entities));
            var entityList = entities.ToList();
            if (!entityList.Any()) return Enumerable.Empty<FakeNews>();
            
            try
            {
                await AddRangeAsync(entityList, cancellationToken);
                _logger.LogInformation("成功批量创建FakeNews，数量: {Count}", entityList.Count);
                return entityList;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "批量创建FakeNews失败，数量: {Count}", entityList.Count);
                throw new DataAccessException("批量创建FakeNews失败", ex);
            }
        }

        #endregion

        #region 业务查询方法

        /// <summary>
        /// 根据title查询FakeNews
        /// </summary>
        /// <param name="title">title</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>FakeNews实体</returns>
        public async Task<FakeNews?> GetBytitleAsync(string title, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                return await GetByConditionAsync(x => x.title == title, cancellationToken).ContinueWith(t => t.Result.FirstOrDefault(), cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "根据title获取FakeNews失败: {Title}", title);
                throw new DataAccessException($"根据title获取FakeNews失败: {title}", ex);
            }
        }

        /// <summary>
        /// 检查title是否存在
        /// </summary>
        /// <param name="title">title</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        public async Task<bool> titleExistsAsync(string title, long excludeId = default, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                if (excludeId.Equals(default(long)))
                {
                    return await ExistsAsync(x => x.title == title, cancellationToken);
                }
                else
                {
                    return await ExistsAsync(x => x.title == title && x.Id != excludeId, cancellationToken);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "检查FakeNewstitle是否存在失败: {Title}", title);
                throw new DataAccessException($"检查FakeNewstitle是否存在失败: {title}", ex);
            }
        }

        /// <summary>
        /// 根据author查询FakeNews
        /// </summary>
        /// <param name="author">author</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>FakeNews实体</returns>
        public async Task<FakeNews?> GetByauthorAsync(string author, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                return await GetByConditionAsync(x => x.author == author, cancellationToken).ContinueWith(t => t.Result.FirstOrDefault(), cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "根据author获取FakeNews失败: {Author}", author);
                throw new DataAccessException($"根据author获取FakeNews失败: {author}", ex);
            }
        }

        /// <summary>
        /// 检查author是否存在
        /// </summary>
        /// <param name="author">author</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        public async Task<bool> authorExistsAsync(string author, long excludeId = default, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                if (excludeId.Equals(default(long)))
                {
                    return await ExistsAsync(x => x.author == author, cancellationToken);
                }
                else
                {
                    return await ExistsAsync(x => x.author == author && x.Id != excludeId, cancellationToken);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "检查FakeNewsauthor是否存在失败: {Author}", author);
                throw new DataAccessException($"检查FakeNewsauthor是否存在失败: {author}", ex);
            }
        }

        /// <summary>
        /// 根据content查询FakeNews
        /// </summary>
        /// <param name="content">content</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>FakeNews实体</returns>
        public async Task<FakeNews?> GetBycontentAsync(string content, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                return await GetByConditionAsync(x => x.content == content, cancellationToken).ContinueWith(t => t.Result.FirstOrDefault(), cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "根据content获取FakeNews失败");
                throw new DataAccessException("根据content获取FakeNews失败", ex);
            }
        }

        /// <summary>
        /// 检查content是否存在
        /// </summary>
        /// <param name="content">content</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        public async Task<bool> contentExistsAsync(string content, long excludeId = default, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                if (excludeId.Equals(default(long)))
                {
                    return await ExistsAsync(x => x.content == content, cancellationToken);
                }
                else
                {
                    return await ExistsAsync(x => x.content == content && x.Id != excludeId, cancellationToken);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "检查FakeNewscontent是否存在失败");
                throw new DataAccessException("检查FakeNewscontent是否存在失败", ex);
            }
        }

        /// <summary>
        /// 根据Description查询FakeNews
        /// </summary>
        /// <param name="description">Description</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>FakeNews实体</returns>
        public async Task<FakeNews?> GetByDescriptionAsync(string description, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                return await GetByConditionAsync(x => x.Description == description, cancellationToken).ContinueWith(t => t.Result.FirstOrDefault(), cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "根据Description获取FakeNews失败: {Description}", description);
                throw new DataAccessException($"根据Description获取FakeNews失败: {description}", ex);
            }
        }

        /// <summary>
        /// 检查Description是否存在
        /// </summary>
        /// <param name="description">Description</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        public async Task<bool> DescriptionExistsAsync(string description, long excludeId = default, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                if (excludeId.Equals(default(long)))
                {
                    return await ExistsAsync(x => x.Description == description, cancellationToken);
                }
                else
                {
                    return await ExistsAsync(x => x.Description == description && x.Id != excludeId, cancellationToken);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "检查FakeNewsDescription是否存在失败: {Description}", description);
                throw new DataAccessException($"检查FakeNewsDescription是否存在失败: {description}", ex);
            }
        }

        #endregion

        #region Orleans分页查询扩展

        /// <summary>
        /// 获取FakeNews分页列表（包含关联数据）
        /// </summary>
        /// <param name="pageNumber">页码（从1开始）</param>
        /// <param name="pageSize">每页大小</param>
        /// <param name="orderBy">排序表达式</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>分页结果</returns>
        public async virtual Task<PagedResult<FakeNews>> GetPagedAsync(int pageNumber, int pageSize, 
            Expression<Func<FakeNews, object>>? orderBy = null, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (pageNumber < 1) pageNumber = 1;
            if (pageSize < 1) pageSize = 20;
            
            try
            {
                // 使用基类的分页方法
                var orderByExpression = orderBy ?? (x => x.Id);
                var result = await base.GetPagedAsync(pageNumber, pageSize, orderByExpression, false, cancellationToken);
                _logger.LogInformation("成功获取FakeNews分页数据，页码: {PageNumber}, 页大小: {PageSize}", pageNumber, pageSize);
                return result;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "获取FakeNews分页数据失败，页码: {PageNumber}, 页大小: {PageSize}", pageNumber, pageSize);
                throw new DataAccessException("获取FakeNews分页数据失败", ex);
            }
        }

        /// <summary>
        /// 根据条件获取FakeNews分页列表
        /// </summary>
        /// <param name="predicate">查询条件</param>
        /// <param name="pageNumber">页码（从1开始）</param>
        /// <param name="pageSize">每页大小</param>
        /// <param name="orderBy">排序表达式</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>分页结果</returns>
        public async virtual Task<PagedResult<FakeNews>> GetPagedByConditionAsync(
            Expression<Func<FakeNews, bool>> predicate, int pageNumber, int pageSize,
            Expression<Func<FakeNews, object>>? orderBy = null, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (pageNumber < 1) pageNumber = 1;
            if (pageSize < 1) pageSize = 20;
            if (predicate == null) throw new ArgumentNullException(nameof(predicate));
            
            try
            {
                // 使用基类的条件分页方法
                var orderByExpression = orderBy ?? (x => x.Id);
                var result = await base.GetPagedByConditionAsync(predicate, pageNumber, pageSize, orderByExpression, false, cancellationToken);
                _logger.LogInformation("成功获取FakeNews条件分页数据，页码: {PageNumber}, 页大小: {PageSize}", pageNumber, pageSize);
                return result;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "获取FakeNews条件分页数据失败，页码: {PageNumber}, 页大小: {PageSize}", pageNumber, pageSize);
                throw new DataAccessException("获取FakeNews条件分页数据失败", ex);
            }
        }

        #endregion
    }
}