// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-11-19 14:38:27
//     功能: 订单仓储实现类
//     架构: 遵循Orleans最佳实践，继承SqlSugarRepository
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using SqlSugar;
using FakeMicro.DatabaseAccess;
using FakeMicro.DatabaseAccess.Interfaces;
using FakeMicro.Entities;

namespace FakeMicro.DatabaseAccess.Repositories
{
    /// <summary>
    /// 订单仓储实现类
    /// 继承SqlSugarRepository，遵循Orleans架构最佳实践
    /// </summary>
    public class OrderRepository : SqlSugarRepository<Order, long>, IOrderRepository
    {
        private readonly ILogger<OrderRepository> _logger;

        /// <summary>
        /// 订单仓储构造函数
        /// </summary>
        /// <param name="db">SqlSugar数据库客户端</param>
        /// <param name="logger">日志记录器</param>
        public OrderRepository(ISqlSugarClient db, ILogger<OrderRepository> logger)
            : base(db, logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        #region 基类方法重写

        /// <summary>
        /// 重写获取订单方法，添加性能优化
        /// </summary>
        /// <param name="id">主键值</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>订单实体</returns>
        public new async virtual Task<Order?> GetByIdAsync(long id, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                // 使用SqlSugar的查询优化，添加WITH(NOLOCK)提示
                return await GetSqlSugarClient().Queryable<Order>()
                    .With(SqlWith.NoLock)
                    .Where(entity => entity.Id == id)
                    .FirstAsync(cancellationToken);
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "获取订单失败: {Id}", id);
                throw new DataAccessException("获取订单失败: " + id, ex);
            }
        }

        /// <summary>
        /// 创建订单并返回创建后的实体
        /// </summary>
        /// <param name="entity">订单实体</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>创建后的订单实体</returns>
        public async virtual Task<Order> CreateAndReturnAsync(Order entity, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (entity == null) throw new ArgumentNullException(nameof(entity));
            
            try
            {
                var result = await GetSqlSugarClient().Insertable(entity).ExecuteReturnEntityAsync(cancellationToken);
                _logger.LogInformation("成功创建Order: {Id}", typeof(Order).Name, entity.Id);
                return result;
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "创建订单失败");
                throw new DataAccessException("创建订单失败", ex);
            }
        }

        /// <summary>
        /// 软删除订单
        /// </summary>
        /// <param name="id">主键值</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否删除成功</returns>
        public async virtual Task<bool> SoftDeleteAsync(long id, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                var result = await GetSqlSugarClient().Updateable<Order>()
                    .SetColumns(entity => new Order { IsDeleted = true, DeleteTime = DateTime.UtcNow })
                    .Where(entity => entity.Id == id)
                    .ExecuteCommandAsync(cancellationToken);
                
                if (result > 0)
                {
                    _logger.LogInformation("成功软删除订单: {Id}", id);
                    return true;
                }
                
                return false;
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "软删除订单失败: {Id}", id);
                throw new DataAccessException("软删除订单失败: " + id, ex);
            }
        }

        #endregion

        #region Orleans Grain特定操作

        /// <summary>
        /// 通过Grain ID获取订单（Orleans特定）
        /// </summary>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>订单实体</returns>
        public async virtual Task<Order?> GetByGrainIdAsync(CancellationToken cancellationToken = default)
        {
            // 注意：此方法需要在Grain上下文中调用，通过Grain的ID获取实体
            // 具体实现取决于Grain的ID策略
            throw new NotImplementedException("需要在Grain上下文中实现GetByGrainIdAsync方法");
        }

        /// <summary>
        /// 创建订单（Orleans特定）
        /// </summary>
        /// <param name="entity">订单实体</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>创建后的订单实体</returns>
        public async virtual Task<Order> CreateAsync(Order entity, CancellationToken cancellationToken = default)
        {
            return await CreateAndReturnAsync(entity, cancellationToken);
        }

        #endregion

        #region 业务查询方法

        /// <summary>
        /// 根据OrderNo查询订单
        /// </summary>
        /// <param name="orderno">OrderNo</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>订单实体列表</returns>
        public async virtual Task<List<Order>> GetByOrderNoAsync(string orderno, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (string.IsNullOrEmpty(orderno)) throw new ArgumentException("Value cannot be null or empty", nameof(orderno));
            try
            {
                return await GetSqlSugarClient().Queryable<Order>()
                    .With(SqlWith.NoLock)
                    .Where(entity => entity.OrderNo == orderno)
                    .ToListAsync(cancellationToken);
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "根据OrderNo查询订单失败: {orderno}", orderno);
                throw new DataAccessException("根据OrderNo查询订单失败: " + orderno, ex);
            }
        }

        /// <summary>
        /// 根据CustomerName查询订单
        /// </summary>
        /// <param name="customername">CustomerName</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>订单实体列表</returns>
        public async virtual Task<List<Order>> GetByCustomerNameAsync(string customername, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (string.IsNullOrEmpty(customername)) throw new ArgumentException("Value cannot be null or empty", nameof(customername));
            try
            {
                return await GetSqlSugarClient().Queryable<Order>()
                    .With(SqlWith.NoLock)
                    .Where(entity => entity.CustomerName == customername)
                    .ToListAsync(cancellationToken);
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "根据CustomerName查询订单失败: {customername}", customername);
                throw new DataAccessException("根据CustomerName查询订单失败: " + customername, ex);
            }
        }

        /// <summary>
        /// 分页查询订单
        /// </summary>
        /// <param name="pageNumber">页码</param>
        /// <param name="pageSize">页大小</param>
        /// <param name="orderBy">排序表达式</param>
        /// <param name="isDescending">是否降序</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>分页结果</returns>
        public async virtual Task<PaginatedResult<Order>> GetPagedAsync(int pageNumber, int pageSize, 
            Expression<Func<Order, object>>? orderBy = null, bool isDescending = false, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (pageNumber < 1) throw new ArgumentException("Page number must be greater than 0", nameof(pageNumber));
            if (pageSize < 1) throw new ArgumentException("Page size must be greater than 0", nameof(pageSize));
            
            try
            {
                var query = GetSqlSugarClient().Queryable<Order>()
                    .With(SqlWith.NoLock);
                
                // 添加排序
                if (orderBy != null)
                {
                    query = isDescending ? query.OrderBy(orderBy, OrderByType.Desc) : query.OrderBy(orderBy, OrderByType.Asc);
                }
                else
                {
                    query = query.OrderBy(entity => entity.Id, OrderByType.Desc);
                }
                
                // 执行分页查询
                var totalCount = await query.CountAsync(cancellationToken);
                var items = await query.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToListAsync(cancellationToken);
                
                return new PaginatedResult<Order>
                {
                    Items = items,
                    TotalCount = totalCount,
                    PageNumber = pageNumber,
                    PageSize = pageSize,
                    TotalPages = (int)Math.Ceiling((double)totalCount / pageSize)
                };
            }
            catch (SqlSugarException ex)
            {
                _logger.LogError(ex, "分页查询订单失败");
                throw new DataAccessException("分页查询订单失败", ex);
            }
        }

        #endregion

    }
}
