// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-11-24 12:57:32
//     功能: Email仓储接口定义
// </auto-generated>

using System;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq.Expressions;
using FakeMicro.DatabaseAccess.Interfaces;
using FakeMicro.Utilities;
using FakeMicro.Entities;

namespace FakeMicro.DatabaseAccess.Interfaces
{
    /// <summary>
    /// Email仓储接口
    /// 遵循DDD原则，集成SqlSugar ORM和Orleans架构
    /// </summary>
    public interface IEmailRepository
        : IRepository<Email, long>
    {
        #region Orleans Grain特定操作

        /// <summary>
        /// 通过Orleans Grain ID获取Email实体
        /// </summary>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>实体对象，如果不存在则返回null</returns>
        new Task<Email?> GetByIdAsync(long id, CancellationToken cancellationToken = default);

        /// <summary>
        /// 创建Email实体并返回创建后的实体
        /// </summary>
        /// <param name="entity">Email实体</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>创建后的实体对象</returns>
        Task<Email?> CreateAndReturnAsync(Email entity, CancellationToken cancellationToken = default);

        /// <summary>
        /// 更新Email实体并返回更新后的实体
        /// </summary>
        /// <param name="entity">Email实体</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>更新后的实体对象</returns>
        Task<Email?> UpdateAndReturnAsync(Email entity, CancellationToken cancellationToken = default);

        #endregion


        #region 批量业务操作

        /// <summary>
        /// 批量创建Email实体并返回创建后的实体
        /// </summary>
        /// <param name="entities">Email实体集合</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>创建后的实体集合</returns>
        Task<IEnumerable<Email>> CreateRangeAndReturnAsync(IEnumerable<Email> entities, CancellationToken cancellationToken = default);

        #endregion

        /// <summary>
        /// 根据title获取Email
        /// </summary>
        /// <param name="title">title</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>Email实体</returns>
        Task<Email?> GetBytitleAsync(string title, CancellationToken cancellationToken = default);

        /// <summary>
        /// 检查title是否存在
        /// </summary>
        /// <param name="title">title</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        Task<bool> titleExistsAsync(string title, long excludeId = default, CancellationToken cancellationToken = default);

        /// <summary>
        /// 根据sendTo获取Email
        /// </summary>
        /// <param name="sendto">sendTo</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>Email实体</returns>
        Task<Email?> GetBysendToAsync(string sendto, CancellationToken cancellationToken = default);

        /// <summary>
        /// 检查sendTo是否存在
        /// </summary>
        /// <param name="sendto">sendTo</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        Task<bool> sendToExistsAsync(string sendto, long excludeId = default, CancellationToken cancellationToken = default);

        /// <summary>
        /// 根据Major获取Email
        /// </summary>
        /// <param name="major">Major</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>Email实体</returns>
        Task<Email?> GetByMajorAsync(string major, CancellationToken cancellationToken = default);

        /// <summary>
        /// 检查Major是否存在
        /// </summary>
        /// <param name="major">Major</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        Task<bool> MajorExistsAsync(string major, long excludeId = default, CancellationToken cancellationToken = default);

        /// <summary>
        /// 根据Description获取Email
        /// </summary>
        /// <param name="description">Description</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>Email实体</returns>
        Task<Email?> GetByDescriptionAsync(string description, CancellationToken cancellationToken = default);

        /// <summary>
        /// 检查Description是否存在
        /// </summary>
        /// <param name="description">Description</param>
        /// <param name="excludeId">排除的ID（用于更新时验证）</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>是否存在</returns>
        Task<bool> DescriptionExistsAsync(string description, long excludeId = default, CancellationToken cancellationToken = default);


        #region Orleans分页查询扩展

        /// <summary>
        /// 获取Email分页列表（包含关联数据）
        /// </summary>
        /// <param name="pageNumber">页码（从1开始）</param>
        /// <param name="pageSize">每页大小</param>
        /// <param name="orderBy">排序表达式</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>分页结果</returns>
        new Task<PagedResult<Email>> GetPagedAsync(int pageNumber, int pageSize, 
            Expression<Func<Email, object>>? orderBy = null, CancellationToken cancellationToken = default);

        /// <summary>
        /// 根据条件获取Email分页列表
        /// </summary>
        /// <param name="predicate">查询条件</param>
        /// <param name="pageNumber">页码（从1开始）</param>
        /// <param name="pageSize">每页大小</param>
        /// <param name="orderBy">排序表达式</param>
        /// <param name="cancellationToken">取消令牌</param>
        /// <returns>分页结果</returns>
        new Task<PagedResult<Email>> GetPagedByConditionAsync(
            Expression<Func<Email, bool>> predicate, int pageNumber, int pageSize,
            Expression<Func<Email, object>>? orderBy = null, CancellationToken cancellationToken = default);

        #endregion
    }
}
