// <auto-generated>
//     此代码由代码生成器生成，请勿手动修改
//     生成时间: 2025-11-24 12:57:32
// </auto-generated>

using System;
using System.ComponentModel.DataAnnotations;
using SqlSugar;
using Orleans;

namespace FakeMicro.Entities
{
    /// <summary>
    /// Email
    /// </summary>
    [GenerateSerializer]
    [SugarTable("email")]
    public class Email
    {
        /// <summary>
        /// 唯一标识
        /// </summary>
        [Id(0)]
        [Required]
        [SugarColumn(IsPrimaryKey = true)]
        public long Id { get; set; }

        /// <summary>
        /// 主题
        /// </summary>
        [Id(1)]
        [Required]
        [MaxLength(100)]
        public string title { get; set; }

        /// <summary>
        /// 发送给谁
        /// </summary>
        [Id(2)]
        [Required]
        [MaxLength(20)]
        public string sendTo { get; set; }

        /// <summary>
        /// 专业
        /// </summary>
        [Id(3)]
        [Required]
        [MaxLength(100)]
        public string Major { get; set; }

        /// <summary>
        /// 状态(1:正常,2:停课,3:毕业)
        /// </summary>
        [Id(4)]
        [Required]
        public int status { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        [Id(5)]
        [MaxLength(500)]
        public string Description { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [Id(6)]
        [SugarColumn(IsOnlyIgnoreUpdate = true)]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// 更新时间
        /// </summary>
        [Id(7)]
        [SugarColumn(IsOnlyIgnoreInsert = true)]
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    }
}
